### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by manicmachiavelli** [ethicalhack3r/DVWA#100]
I keep getting the cannot connect to database error when setting up dvwa, I've checked the config, I've made sure I have the right version of PHP, and MySQL works just fine on its own through xampp, I've even tried setting the host to localhost. The console isn't giving me information, I'm outta ideas here. Any tips?

**Comment by mike-bailey** [comment]
Hello, was this resolved? Do you still need help?

_Please note as it is a relatively old issue after 2 weeks of this comment I will be closing this issue._
