### ISSUE TITLE
Sql injection vulnerability in low.php

### ISSUE THREAD

**Issue by EhsanCod3r** [ethicalhack3r/DVWA#101]
Hello.
I fonud an sql injection vulnerability in this file:
`vulnerabilities/brute/source/low.php`

Vulnerable code 
5: `$user = $_GET['username'];`
8: `$pass = $_GET['password'];`
12: `$query = "SELECT * FROM `users` WHERE user = '$user' AND password = '$pass';";`
13: `mysql_query $result = mysql_query($query) or die ('<pre>' . mysql_error() . '</pre>');`

Ashiyane Digital Security Team
Please fix this.
Good Luck/

**Comment by erwanlr** [comment]
Lol, RTFM maybe ?

**Comment by ragtek** [comment]
You've found only 1 vulnerability here? I would suggest to take a look at https://github.com/ethicalhack3r/DVWA/blob/master/docs/DVWA_v1.3.pdf ;)

**Comment by EhsanCod3r** [comment]
this vulnerability should be don't in the file because this is a test for brute force no sql injection.
good luck/

**Comment by lazec** [comment]
Srsly dude?

**Comment by n0tty** [comment]
Damn this vulnerable web application! Everything has got hax0r'd by Ashiyane Digital Security Team.

**Comment by kaitcoa** [comment]
oh, well. Give him a Oscar..

**Comment by connordavison** [comment]
I'm thinking perhaps that @EhsanCod3r's point has been misunderstood. The file is supposed to highlight vulnerability to brute force (as I understood it); however, it also highlights SQL injection vulnerabilities - which go on to be fixed later. Focusing on fixing one problem at a time is less likely to confuse the reader.

**Comment by rfgiusti** [comment]
That would make sense. But the manual specifies that `vulnerabilities/brute/` is also supposed to contain source files that are vulnerable to SQL injection.

**Comment by AliFarshad** [comment]
Lol😂.  Please fix this !

**Comment by kakumanivrn** [comment]
Oh My God, SQL fucking Injection? Dude you are super awesome!!!

**Comment by HarshilPatel007** [comment]
LoLxD :neckbeard: 
@EhsanCod3r Please Check For XSS I Think It Maybe Possible ....... :neckbeard:

**Comment by n1arash** [comment]
@EhsanCod3r
Nice Found LoL 😂😂😂😅😅

**Comment by carlosgprado** [comment]
GREAT JOB

**Comment by phackwer** [comment]
n00b VV4n4!33

**Comment by mpourismaiel** [comment]
Can we please keep this issue as an example to RTFM? Maybe add some labels regarding it?!

**Comment by heticor915** [comment]
Yeah, We should add the labels as @mpourismaiel  suggest

**Comment by lnxg33k** [comment]
Hahhahahahahahahahahaahhahahahhahahahahahaah

**Comment by SymbianSyMoh** [comment]
Pffffffff 👎

**Comment by diegofreijo** [comment]
OMG do you mean I shouldn´t use this app in a production enviroment? 😂

**Comment by OneSourceCat** [comment]
good job man!

**Comment by AliFarshad** [comment]
I found vulnerability in base64 
Please fix this  ! 
<?php echo base64_decode("aA==");?> 
😑😂
