### ISSUE TITLE
Cross Site Scripting in view_source.php

### ISSUE THREAD

**Issue by EhsanCod3r** [ethicalhack3r/DVWA#102]
Hello.
#Proof of Content:
`http://localhost/dvwa/vulnerabilities/view_source.php?id="><script>alert(1)</script>`

#Vulnerable code:
`63: <input type=\"button\" value=\"Compare All Levels\" onclick=\"window.location.href='view_source_all.php?id=$id'\">`

#Fix:
`<input type=\"button\" value=\"Compare All Levels\" onclick=\"window.location.href='view_source_all.php?id=" . htmlspecialchars($id) . "'\">`

Good Luck/

**Comment by digininja** [comment]
Well done on finding things but they are supposed to be there, it is a
deliberately vulnerable application which contains published and
unpublished vulns for people to learn from.

**Comment by EhsanCod3r** [comment]
@digininja 
this file isn't a part vulnerability challenges , this file is out of challenges and this vulnerability don't be in this.

**Comment by erwanlr** [comment]
RTFM: "Please note, there are *both documented and undocumented
vulnerability* with this software. This is intentional. You are encouraged
to try and discover as many issues as possible."

**Comment by digininja** [comment]
The clue is in the name, it is a vulnerable application, not just a
collection of challenges. The whole application has issues, both the ones
in the challenges and the rest.
