### ISSUE TITLE
SQLI bug in famous springer.com website

### ISSUE THREAD

**Issue by stand2015** [ethicalhack3r/DVWA#105]
hello,
I fonud a sql injection bug in famous publisher **springer** website
http://eproofing.springer.com/books/mainpage.php?token=aRcT6QZIyUSNIAGbFKw-hiIRudmkLaaw6AGptcbLxx0  'order by 12--+

number of columns are 12. but i couldn't  continue to inject, the database is not mysql i think.
maybe any one can continue...
thanks

**Comment by ethicalhack3r** [comment]
> hello,
I fonud a sql injection bug in famous publisher springer website
http://eproofing.springer.com/books/mainpage.php?token=aRcT6QZIyUSNIAGbFKw-hiIRudmkLaaw6AGptcbLxx0 'order by 12--+

> number of columns are 12. but i couldn't continue to inject, the database is not mysql i think.
> maybe any one can continue...
> thanks

Please do not post information about your illegal activities here. It's very, very stupid.
