### ISSUE TITLE
erreur plugin

### ISSUE THREAD

**Issue by legageyt** [ethicalhack3r/DVWA#106]
hello I would like to know how I can do to settle this problem infact when I want to register on its dvwa puts me this:

Setup Check
Operating system: Windows
Backend database: MySQL
PHP Version: 5.6.24

Web Server SERVER_NAME: localhost

PHP function display_errors Enabled (Easy Mode!)
PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled
PHP function allow_url_fopen Enabled
PHP magic_quotes_gpc function: Disabled
PHP php-gd module Installed

reCAPTCHA key: landry

Writable folder C: \ xampp \ htdocs \ dvwa / hackable / uploads /: Yes)
Writable file C: \ xampp \ htdocs \ dvwa / external / PHPIDS / 0.6 / lib / IDS / tmp / phpids_log.txt: Yes

Status in red, indicate indication there will be an end to full When try trying Some modules.

and "PHP function allow_url_include: Disabled" is red then qque tou I have done it right

**Comment by mike-bailey** [comment]
This is a question on StackOverflow actually.
Make sure after you make changes to restart XAMPP. Please note your reCaptcha key is wrong based on what I see as well.
Feel free to open another issue if you find problems in the project.


https://stackoverflow.com/questions/34274492/dvwa-setup-php-function-allow-url-include-disabled
