### ISSUE TITLE
help out with this....../

### ISSUE THREAD

**Issue by hareeshharidias007** [ethicalhack3r/DVWA#107]
Database Setup

Click on the 'Create / Reset Database' button below to create or reset your database.
If you get an error make sure you have the correct user credentials in: /var/www/html/dvwa/config/config.inc.php

If the database already exists, it will be cleared and the data will be reset.
You can also use this to reset the administrator credentials ("admin // password") at any stage.

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 5.6.17-1

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Missing

reCAPTCHA key: Missing

Writable folder /var/www/html/dvwa/hackable/uploads/: No
Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: No

Status in red, indicate there will be an issue when trying to complete some modules.

how to solve this issue....
i installed php-gd aftr that what to do????/

**Comment by digininja** [comment]
What is the problem you are having?

**Comment by hareeshharidias007** [comment]
HP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Missing

reCAPTCHA key: Missing

Writable folder /var/www/html/dvwa/hackable/uploads/: No
Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: No
it is showing all these errors
c

**Comment by digininja** [comment]
Have you tried this?

http://lmgtfy.com/?q=allow_url_include+enable
