### ISSUE TITLE
Security Level in DVWA not really changing 

### ISSUE THREAD

**Issue by rexxturbo** [ethicalhack3r/DVWA#108]
Hi,

I have DVWA set up on a target computer. I changed the Security level to "low", when I refresh the page, the security level remains low.

Here is the problem. 

When I connect to the target PC from my attack box and intercept traffic with Burp, DVWA shows that security is set to "impossible". I have tried resetting the security multiple times, but no luck.

Any ideas?

Thanks

GET /login.php HTTP/1.1
Host: 172.16.1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://172.16.1.130/login.php
Cookie: PHPSESSID=cv9f2p4mfd33hvkknbigio4ao2; security=impossible
Connection: close
Cache-Control: max-age=0

**Comment by digininja** [comment]
The level is per session so if you are logging in from a new session then
the level will go back to impossible. Use a Burp search and replace to
downgrade it.

**Comment by mike-bailey** [comment]
Answered 8 months ago without response. Assuming it's resolved.
