### ISSUE TITLE
Object Not Found!

### ISSUE THREAD

**Issue by Phillbert** [ethicalhack3r/DVWA#111]
On a Fedora machine I am getting a Object Not Found! Error 404

**Comment by digininja** [comment]
You need to give us a little more to work with than that. 404 is not found,
did you install DVWA yet?

**Comment by Phillbert** [comment]
Yes, I've followed all instructions up to logging in and am getting the above error. Sorry for the lack of information, I'm new to GitHub.

**Comment by digininja** [comment]
Doesn't matter where you are, when asking for help, always give as much
info as you can.

What OS?
What server software?
How did you install it?
What do the web server logs say?
What directory are you trying access?
Were there any errors when you did the install?
What have you tried to do to fix it?

**Comment by Phillbert** [comment]
Fedora Workstation 24
XAMPP
Made installer executable then ran it.
Installed DVWA into \opt\lampp\htdocs
127.0.0.1/dvwa.login.php
No errors while installing.
I tried editing config.inc.php P@ssword as described in the file.
How does one check the web server logs? I can't seem to get the XAMPP
control panel up at the moment. I ran the commands in terminal and Apache,
MySQL and ProFTPD have started. I only started using Linux when I started
the course I am doing and only really used Kali. I couldn't get DVWA to
work on my Windows 10 machine.

**Comment by digininja** [comment]
I don't use xamp so can't help to much but Google for where it stores the
web logs and then check in there.

**Comment by Phillbert** [comment]
Is there an alternative to XAMPP I could use with instructions for DVWA?

**Comment by digininja** [comment]
I run it through a raw Apache, php, MySQL install. You don't need something
specific to DVWA, just google getting a LAMP stack installed then drop the
files in the right directory.
