### ISSUE TITLE
PHP module gd: Missing

### ISSUE THREAD

**Issue by anon2903** [ethicalhack3r/DVWA#112]
Everything is green apart from this. I'm using php5.

**Comment by digininja** [comment]
Have you tried searching for installing gd in php 5?

**Comment by anon2903** [comment]
I tried sudo apt-get install php5-gd but I get this
![image](https://cloud.githubusercontent.com/assets/20747722/20458071/28cc645a-ae92-11e6-854b-99005736e27b.png)

**Comment by digininja** [comment]
Did you update with apt-get update and apt-get dist-upgrade first?

**Comment by anon2903** [comment]
Just did that now. Still getting the error

**Comment by digininja** [comment]
Most solutions I can see suggest uninstalling php5 and putting it all in
again starting with the gd library.

**Comment by mike-bailey** [comment]
Looks like it depends on a later version of PHP5, can you not update it any higher? 

To clarify, also, apt-get update then apt-get upgrade. dist-upgrade would upgrade the entire distro. You just need the new version of PHP5.

**Comment by digininja** [comment]
upgrade or dist-upgrade just depends on how up-to-date you want to be.
dist-upgrade would force everything to the latest version and so is more
likely to pull the packages into line to fix dependencies.

**Comment by lotfiking** [comment]
any solution for php5-gd i tried searching

**Comment by mike-bailey** [comment]
@lotfiking what did you already try system-wise? What OS?

**Comment by lotfiking** [comment]
@mike-bailey  Linux kali 4.3.0-kali1-amd64 on virtualbox

**Comment by mike-bailey** [comment]
What have you tried so far?  What happens when you `apt-cache search php|grep gd`

**Comment by theprofi** [comment]
This command fixed the issue for me:
`apt-get install php7.0-gd -y && service apache2 restart`

**Comment by digininja** [comment]
The 7.0 in that package is for PHP 7, he is asking about PHP 5.

**Comment by mike-bailey** [comment]
It does work for PHP7. We don’t have much control over internet tutorials, most of them aren’t even right.

**Comment by kimchoyoung** [comment]
apt-get install php7.0-gd -y && service apache2 restart. it also works for me

**Comment by digininja** [comment]
Again, that is the PHP 7 package, he is asking about PHP 5.
