### ISSUE TITLE
Blank login and wrong permissions

### ISSUE THREAD

**Issue by M3rcurio** [ethicalhack3r/DVWA#115]
I installed DVWA on apache2 but, when I try to go to localhost/dvwa in the browser it sends me to the localhost/dvwa/login.php web page which is blank. I've manually typed localhost/dvwa/setup.php in the browser and it shows "var/www/html/dvwa/hackable/uploads/" and "var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt" are not writable, even if i give them writable permissions (chmod +w ...).
This is what setup.php shows: http://pastebin.com/0J8YeeAa.
I also watch apache error log which is full of errors: http://pastebin.com/6wC0ZJmi

**Comment by digininja** [comment]
Based on those errors I'd say you don't have the MySQL libraries installed.

The chmod you've done, I think, just sets the write flag for you, you need
a+w to set it for all.

**Comment by M3rcurio** [comment]
..but when i type "mysql" on command line it opens mysql shell and it works fine, what libraries are missing?

**Comment by digininja** [comment]
that means you have mysql installed, you need the php mysql libraries.

Use your google skills to work that out and get it sorted, understanding
how the underlying server works is part of the learning process.

**Comment by prmdsngh** [comment]
please see the php version u using is either 5 or 7.0

**Comment by M3rcurio** [comment]
I found the issue: php v7.0 doesn't support functions like msql_connect(...) which is used in dvwa because they are deprecated. I'm using php v7.
I've already had php-mysql.
For testing php-mysql i tried to make my own db with a tabel called "users" which contains (fake) users and passwords. After that i created a php login for that db and works fine.
The question now is: do i have to downgrade php or exist a dvwa for latest php version?

**Comment by digininja** [comment]
You need to use the latest github version of DVWA. It works fine with the
latest php and MySQL

https://github.com/ethicalhack3r/DVWA/issues/117

**Comment by M3rcurio** [comment]
Downloaded github dvwa but setup.php says "PHP module mysql: Missing".
When i type "apt-get install php-mysql" on command line the answer is "php-mysql is already the newest version (1:7.0+46)."
Also my own fake login works...

**Comment by digininja** [comment]
If you have the pdo MySQL that is fine

**Comment by M3rcurio** [comment]
Ok, it works now! (Even if setup.php says module php is missing)

**Comment by digininja** [comment]
I think we need to put a note to say one or the other is required.

**Comment by GroupT00** [comment]
顶一下，我来自china

**Comment by Jayed2016** [comment]
I spent all day today to fix this mysterious problem and still the login.php page is blank. Here's my error log texts 
"[Wed Aug 23 06:19:07.384776 2017] [mpm_prefork:notice] [pid 2479] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 06:19:07.385834 2017] [core:notice] [pid 2479] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 06:49:23.603062 2017] [:error] [pid 3049] [client ::1:56850] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 471
[Wed Aug 23 06:50:19.184459 2017] [:error] [pid 2481] [client ::1:56858] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 471
[Wed Aug 23 06:55:45.551287 2017] [:error] [pid 2485] [client ::1:56878] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 471
[Wed Aug 23 07:16:53.801819 2017] [:error] [pid 3047] [client ::1:57092] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/DVWA-1.9/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/DVWA-1.9/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/DVWA-1.9/dvwa/includes/dvwaPage.inc.php on line 461, referer: http://localhost/dvwa/
[Wed Aug 23 07:16:57.823530 2017] [:error] [pid 3049] [client ::1:57098] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/DVWA-1.9/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/DVWA-1.9/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/DVWA-1.9/dvwa/includes/dvwaPage.inc.php on line 461, referer: http://localhost/dvwa/
[Wed Aug 23 07:23:44.658337 2017] [:error] [pid 2842] [client ::1:57108] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 07:24:19.795316 2017] [:error] [pid 2483] [client ::1:57112] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:16:30.053332 2017] [:error] [pid 2482] [client 127.0.0.1:55394] PHP Notice:  Undefined index: user_token in /var/www/html/dvwa/setup.php on line 14
[Wed Aug 23 08:16:30.059521 2017] [:error] [pid 2482] [client 127.0.0.1:55394] PHP Notice:  Undefined index: session_token in /var/www/html/dvwa/setup.php on line 14
[Wed Aug 23 08:17:43.144377 2017] [:error] [pid 2484] [client 127.0.0.1:55420] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:18:17.918573 2017] [:error] [pid 2485] [client 127.0.0.1:55432] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:18:18.901836 2017] [:error] [pid 3048] [client 127.0.0.1:55434] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:22:42.289105 2017] [mpm_prefork:notice] [pid 2479] AH00169: caught SIGTERM, shutting down
[Wed Aug 23 08:22:42.808462 2017] [mpm_prefork:notice] [pid 4997] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 08:22:42.810606 2017] [core:notice] [pid 4997] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 08:39:28.243351 2017] [mpm_prefork:notice] [pid 4997] AH00169: caught SIGTERM, shutting down
[Wed Aug 23 08:39:29.135568 2017] [mpm_prefork:notice] [pid 14783] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 08:39:29.138861 2017] [core:notice] [pid 14783] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 08:42:32.524178 2017] [:error] [pid 14789] [client ::1:57342] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Aug 23 08:42:44.025787 2017] [:error] [pid 14790] [client 127.0.0.1:55562] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:42:45.893969 2017] [:error] [pid 14866] [client 127.0.0.1:55564] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:42:52.307240 2017] [:error] [pid 14868] [client 127.0.0.1:55566] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:43:16.794884 2017] [:error] [pid 14786] [client ::1:57352] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Aug 23 11:07:34.409973 2017] [mpm_prefork:notice] [pid 1718] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 11:07:34.430021 2017] [core:notice] [pid 1718] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 11:13:45.954033 2017] [:error] [pid 1724] [client ::1:50846] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:13:58.673977 2017] [:error] [pid 2063] [client ::1:50848] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:13:59.580196 2017] [:error] [pid 1720] [client ::1:50850] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:14:18.926629 2017] [:error] [pid 2093] [client ::1:50852] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:28:56.390308 2017] [:error] [pid 1721] [client ::1:51406] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:28:57.934712 2017] [:error] [pid 1722] [client ::1:51408] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:28:58.760863 2017] [:error] [pid 1723] [client ::1:51410] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:48:17.527570 2017] [:error] [pid 1724] [client ::1:51546] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:48:18.851588 2017] [:error] [pid 2063] [client ::1:51548] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:48:20.102998 2017] [:error] [pid 1720] [client ::1:51550] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:48:26.645339 2017] [:error] [pid 2093] [client ::1:51552] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:15:18.202270 2017] [:error] [pid 1721] [client ::1:51570] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:15:19.017644 2017] [:error] [pid 1722] [client ::1:51572] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:23:07.915111 2017] [:error] [pid 1724] [client ::1:51582] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:23:09.586994 2017] [:error] [pid 2063] [client ::1:51584] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:23:37.736667 2017] [:error] [pid 1720] [client ::1:51586] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:23:38.778974 2017] [:error] [pid 2093] [client ::1:51588] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 14:21:57.575111 2017] [mpm_prefork:notice] [pid 1718] AH00169: caught SIGTERM, shutting down
[Wed Aug 23 14:21:58.560609 2017] [mpm_prefork:notice] [pid 4965] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 14:21:58.597133 2017] [core:notice] [pid 4965] AH00094: Command line: '/usr/sbin/apache2'
"

**Comment by digininja** [comment]
Based on this:

Call to undefined function mysql_connect()

you are using an out of date version of the code as all instances have now
been changed to mysqli_connect(). Use the version from the Git repo and
everything should work. Any problems, create a new ticket.

**Comment by Jayed2016** [comment]
I actually cloned DVWA from git repo.

**Comment by mike-bailey** [comment]
Do you mind please:
1. Providing the exact command you used to clone
2. Running `git rev-parse HEAD` to get the latest HEAD SHA and letting us know here?

**Comment by Jayed2016** [comment]
1. git clone https://github.com/ethicalhack3r/DVWA.git
2. after running git rev-prase HEAD I got this error "fatal: Not a git repository (or any of the parent directories): .git"

**Comment by mike-bailey** [comment]
Sorry, to clarify, run this in the project root: DVWA folder

**Comment by Jayed2016** [comment]
994441df931edcaae09ac658fe336397a8c3177b
