### ISSUE TITLE
Call to undefined function mysql_connect

### ISSUE THREAD

**Issue by jens1o** [ethicalhack3r/DVWA#116]
DVWA is too insecure for php, therefore it is not possible using PHP 7.1 to use DVWA.

**Comment by digininja** [comment]
Interesting as it is running on 7 fine for me.

**Comment by jens1o** [comment]
https://secure.php.net/manual/en/function.mysql-connect.php

It has been removed in php7, so php 7.1 does not have it.

**Comment by digininja** [comment]
We upgraded to the latest MySQL libraries months ago

**Comment by jens1o** [comment]
Okey. What to do? 
![image](https://cloud.githubusercontent.com/assets/11234139/20858554/4fac505c-b947-11e6-8faf-0c1e8783ba8e.png)

**Comment by digininja** [comment]
Are you running the latest from github?

**Comment by jens1o** [comment]
Yes, I do. I've cloned it a few hours ago.

**Comment by digininja** [comment]
We must have missed one then, change it to the mysqli equivalent and it
should work

**Comment by jens1o** [comment]
Okey, thank you.

**Comment by digininja** [comment]
Not sure what you cloned but I just cloned master and this is line 9
of dvwa/includes/DBMS/MySQL.php which definitely uses mysqli_connect and
not mysql_connect.

```
  9 if( !@($GLOBALS["___mysqli_ston"] = mysqli_connect( $_DVWA[ 'db_server'
],  $_DVWA[ 'db_user' ],  $_DVWA[ 'db_password' ] )) ) {
```

**Comment by mike-bailey** [comment]
Closing as no comments in half a year and @digininja responded.
