### ISSUE TITLE
DVWA works fine in PHP7

### ISSUE THREAD

**Issue by digininja** [ethicalhack3r/DVWA#117]
I'm creating this issue in the hope that people will find it when complaining that DVWA doesn't work in PHP7 and with the new MySQL drivers.

As I've said in lots of other tickets, IT DOES.

I've just done a fresh install of Ubuntu, installed "PHP Version 7.0.8-0ubuntu0.16.04.3" and its associated MySQL drivers and it worked straight off.

There is a little config required if you want to enable all the features but the setup page displayed fine, the database was created correctly and I could log in.

So, if you have problems with DVWA, please do not complain that it doesn't work in PHP7, it does, it is where I run it on all my machines. The upgrades have been done so it works with mysqli_ instead of mysql_.

There may be the odd bug here or there but the fundamentals work.

I'm going to leave this open for a short while so that it gets indexed and people can see it then I'll close it and hope that google can do its magic and show people that it does work.

**Comment by OzanKurt** [comment]
Since you're so upset with people complaining about DVWA not working with PHP7 you should create a release with the name "PHP7 Compatibility Update".

In the website it automatically downloads the `1.9` release from 2015.

If you care about the package to create an issue yourself telling people not to create issues, consider what you can do to prevent people from creating those issues...

**Comment by digininja** [comment]
I'm only a user who answers questions, I'm not an author and have no
control over the website or repository.

**Comment by ethicalhack3r** [comment]
Updated link on dvwa.co.uk to point to master zip download

**Comment by OzanKurt** [comment]
Great! Thanks you.

**Comment by tastypastryyum** [comment]
Hey so if this is possible which I hope to god it is, how do I make it happen? I'm having a heck of a time trying to find a way to install php5.6 on Kali Linux and keep running into error after error despite everything I try.

You mention there is a little config required which I dont care if there's a lot required just as long as I Can get this to start working :) Where would I Find this and is it possible to make dvwa work with php7.0 on Kali Linux, most recent version ?

**Comment by digininja** [comment]
Why are you trying to get 5.6 installed? It works fine with 7.

**Comment by Beeq1** [comment]
how to i create a new ticket for Dvwa

**Comment by mike-bailey** [comment]
@Beeq1 https://github.com/ethicalhack3r/DVWA/issues/new

**Comment by DirtyWhite17** [comment]
Still giving me a blank page.

**Comment by mike-bailey** [comment]
@DirtyWhite17 what do your error logs say?

**Comment by ahusmc** [comment]
You'll need these dependencies: 
apt-get install libapache2-mod-php7.0 libapache2-mod-fastcgi php7.0-fpm php7.0 php-mysql php7.0-mbstring.
