### ISSUE TITLE
Could not connect to the database. Please check the config file.

### ISSUE THREAD

**Issue by BubbleZZ** [ethicalhack3r/DVWA#119]
Setup Check

Operating system: *nix
Backend database: MySQL
PHP version: 5.6.29-1+deb.sury.org~xenial+1

Web Server SERVER_NAME: 192.168.152.131

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Installed

reCAPTCHA key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 

Writable folder /var/www/html/dvwa/hackable/uploads/: Yes)
Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes
-------------------------------------------------------------------------------------------------------------------
TUT FOLLOWED
https://www.youtube.com/watch?v=5BG6iq_AUvM
NOTE-Jack does not know how to fix this because i went to the comments and people were having the same issue and he didn't know how to help/ or didn't reply at all.
-------------------------------------------------------------------------------------------------------------------
Solutions tried (Nothing has worked
Set 'db_password' ] ''; 
Changed 'db_server' ] = 'localhost' ; as well as tried 127.0.0.1
Changing port to 3306
adding port to 127.0.0.1 like 127.0.0.1;3306
-------------------------------------------------------------------------------------------------------------------
Please help been trying multiple things nothing is working ;(

**Comment by mike-bailey** [comment]
Please provide the latest entries in error.log and access.log from whatever web server you're using (it looks like the tutorial is Linux so if it's apache2, it's under /var/log/apache2/error.log & access.log if I recall) and provide it here.

**Comment by digininja** [comment]
Also send the results of logging in to the database using the username and password you are putting into the config file, i.e. if you are using root and no password in the config file, use the mysql command line client to connect using those creds to prove that they work.

**Comment by uzair-alvi** [comment]
@digininja I'm having almost the same issue. At first I was unable to create the database then I change the password to blank. It does create a database but then it takes me login screen.
I tried the username as root and kept the password as blank, it gives me an error "login failed".

Please help. Thanks


![screenshot from 2017-01-27 14-04-48](https://cloud.githubusercontent.com/assets/10295145/22388508/d96b1598-e4ae-11e6-8f68-20bd2d486cd5.png)
![screenshot from 2017-01-27 16-34-07](https://cloud.githubusercontent.com/assets/10295145/22388509/d96c4e04-e4ae-11e6-9bd6-b55f3e533b71.png)

**Comment by digininja** [comment]
I assume you tried the default login credentials

https://github.com/ethicalhack3r/DVWA/blob/master/README.md

**Comment by mike-bailey** [comment]
I'm gonna assume the README wasn't read since those aren't the login credentials. Feel free to open an issue if after reading and following the README and making a good faith effort to research the problem yourself you cannot find a solution. Thank you!

**Comment by SaadBilal** [comment]
@uzair-alvi: found any solution?

**Comment by AAB94** [comment]
https://stackoverflow.com/a/11216911/2464664 This answer may help solve the issue, MySql via command line gives an error too ERROR 1045 (28000) the answer may help solve both issues

**Comment by digininja** [comment]
Can we please stop trying to resurrect closed topics. The login problem
will likely be the use of incorrect credentials as the ones provided in the
message were not the default ones.

If you have your own issue, create a new ticket, don't hijack existing ones.
