### ISSUE TITLE
phpids bypass

### ISSUE THREAD

**Issue by ilk3r** [ethicalhack3r/DVWA#120]
Hi all.

i have come across an issue with phpids. i have been able to disable the service via sqli. 
all that seems to be required is injecting into the security field e.g 
Cookie: security=low''; PHPSESSID=g3du7t21hr27ss3o853la8h602 
this disables the phpids service even when the security level is set to impossible.

**Comment by digininja** [comment]
The security field sets the security level so if you change the level like
this then it is no longer impossible. I don't know what it defaults to but
if you can bypass things then it probably goes to low.

**Comment by ilk3r** [comment]
thats correct one the injection is passed the security level is set to low

**Comment by digininja** [comment]
and so why are you reporting this?

**Comment by ilk3r** [comment]
you can put in anything eg Cookie: security=low apple;

**Comment by ilk3r** [comment]
cause if the level is set to medium, high or impossible with phpids enabled you can disable the ids and set the level to low.

**Comment by digininja** [comment]
That is correct. This is not a bug or a problem, it is the way the system
works

**Comment by ethicalhack3r** [comment]
This is expected. Phpids is an optional additional feature.

**Comment by digininja** [comment]
I think he has found a bug, I'll have a look at it if I get chance

**Comment by digininja** [comment]
Found it, in here:

./dvwa/includes/dvwaPage.inc.php

If the security level passed in is not one of the allowed values then the IDS value is set to whatever the default is, which is false by default.

So if you pass "lowx" as as the security level the IDS is disabled.

```
20 // Valid security levels
 21 $security_levels = array('low', 'medium', 'high', 'impossible');
 22 if( !isset( $_COOKIE[ 'security' ] ) || !in_array( $_COOKIE[ 'security' ], $security_levels ) ) {
 23     // Set security cookie to impossible if no cookie exists
 24     if( in_array( $_DVWA[ 'default_security_level' ], $security_levels) ) {
 25         dvwaSecurityLevelSet( $_DVWA[ 'default_security_level' ] );
 26     }
 27     else {
 28         dvwaSecurityLevelSet( 'impossible' );
 29     }
 30 
 31     if( $_DVWA[ 'default_phpids_level' ] == 'enabled' )
 32         dvwaPhpIdsEnabledSet( true );
 33     else
 34         dvwaPhpIdsEnabledSet( false );
 35 }
 36 
```

Should probably set enabled and disabled in the session rather than set or not set then if the session value doesn't exist it can be set to the default but if it is set then it can be left alone.
