### ISSUE TITLE
Dvaw Folder is at Same Level as Config Folder?

### ISSUE THREAD

**Issue by russ6100** [ethicalhack3r/DVWA#122]
I just dled dvwa to throw on XAMPP and all the instructions I've seen say to put the dvwa folder in your htdocs. The problem is, if you do as instructed, you will not even have the config folder in your installation, hence the app will have no access to config.inc.php! The dvwa folder comes wrapped in to higher level folders, both named DVWA-master. What is the solution here? Who wants to have a path like: localhost/DVWA-master/DVWA-master/etc..? Do I remove the read-only permission from the whole mess and then remove the highest DVWA-master folder, then rename the next DVWA-master folder to 'dvwa' or??

**Comment by russ6100** [comment]
I removed the top-level folder (DVWA-master), changed the next level folder to 'dvwa', edited the config files for 'root' with password:''. I removed the read-only permissions from the whole thing. I stopped using 'localhost' in the address bar and I'm using 127.0.0.1. I also commented out the line to assign the db port number in the config file (it's for postgresSL, don't know why only the comment was commented out). Everthing seems like it should be fine. Mutillidae works without issue.

I'm getting these error messages:

`Notice: Undefined variable: DBMS_errorFunc in C:\xampp\htdocs\dvwa\dvwa\includes\dvwaPage.inc.php on line 465

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\dvwa\dvwa\includes\dvwaPage.inc.php:465) in C:\xampp\htdocs\dvwa\dvwa\includes\dvwaPage.inc.php on line 489`

Is this able to run on MySQL 5.1.41?

**Comment by mike-bailey** [comment]
DVWA-master is what you get when you download a ZIP from GitHub. It's to make sure nobody unzips in their workstation and it explodes in their Desktop or something. The config of this project has changed recently but if there's an issue feel free to open a new one.
