### ISSUE TITLE
Cannot set up database

### ISSUE THREAD

**Issue by scblakely** [ethicalhack3r/DVWA#123]
Setting up on Ubuntu 14.04

Completed php and mysql configuration but getting the following error in the apache2 error.log 

`[:error] [pid 7797] [client 10.0.0.134:49130] PHP Notice:  Undefined index: session_token in /var/www/html/dvwa/setup.php on line 14, referer: http://172.16.0.139/dvwa/setup.php
`

**Comment by digininja** [comment]
It's not an error it's a notice which can probably be ignored as they don't
stop things from working.
