### ISSUE TITLE
error 500 in login page

### ISSUE THREAD

**Issue by icees8** [ethicalhack3r/DVWA#124]
after creating the table when i go to login page it shows me error 500 what should i do
Operating system: Windows
Backend database: MySQL
PHP version: 5.6.27

Web Server SERVER_NAME: localhost

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: ******
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: Missing

**Comment by digininja** [comment]
Check the web server logs to see what the error is.

**Comment by icees8** [comment]
i am not able to understand it please help

[Thu Dec 29 20:53:00.638437 2016] [:error] [pid 4104:tid 1180] [client ::1:49973] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in D:\\bitnami\\apache2\\htdocs\\DVWA-master\\DVWA-master\\dvwa\\includes\\dvwaPage.inc.php:469\nStack trace:\n#0 D:\\bitnami\\apache2\\htdocs\\DVWA-master\\DVWA-master\\dvwa\\includes\\dvwaPage.inc.php(469): PDO->__construct('mysql:host=loca...', 'root', '123654')\n#1 D:\\bitnami\\apache2\\htdocs\\DVWA-master\\DVWA-master\\login.php(8): dvwaDatabaseConnect()\n#2 {main}\n  thrown in D:\\bitnami\\apache2\\htdocs\\DVWA-master\\DVWA-master\\dvwa\\includes\\dvwaPage.inc.php on line 469

**Comment by mike-bailey** [comment]
> Access denied for user 'root'@'localhost' (using password: YES)
Pretty sure you got your login credentials wrong. [There's plenty of documentation on the internet on this error.](http://stackoverflow.com/questions/6445917/connect-failed-access-denied-for-user-rootlocalhost-using-password-yes)

**Comment by digininja** [comment]
This pretty much says it all:

"'SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using
password: YES)'"

you've got the database password wrong.

**Comment by hasnain-malik007** [comment]
HI, first of all, thank you my brother for making such an amazing technology where students like me can learn and practice.
I am facing an issue on dvwa, which is, after entering username and password under bruteforce vuln..  when I click on login button it shows nothing,  just a blank page, and the URL looks like this: "http://127.0.0.1/dvwa/vulnerabilities/brute/#"

also in the chromium-browser, it shows an error 500 internal server error kindly help me to solve this issue!
