### ISSUE TITLE
php code injection

### ISSUE THREAD

**Issue by legomygodamnegoo** [ethicalhack3r/DVWA#127]
even tho THIS APPLICATION IS MEANT TO BE VULNERABLE I GET IT there is a php code injection in view_help.php in the vulnerabilities folder if you look closely when it runs eval it includes the string id which id is a get string meaning it get the string from the url (or get request) this is bad because you can inject php code. 
code:

$id       = $_GET[ 'id' ];
$security = $_GET[ 'security' ];

ob_start();
eval( '?>' . file_get_contents( DVWA_WEB_PAGE_TO_ROOT . "vulnerabilities/{$id}/help/help.php" ) . '<?php ' );
$help = ob_get_contents();
ob_end_clean();

(theory: if i ran this in my browser (YOURSITE)/DVWA/vulnerabilities/view_help.php?id=(YOURE CODE) it would echo your inputed code but you would have to include the php start and the end sequence)
i might be wrong so dont rant on me plz :'(

**Comment by legomygodamnegoo** [comment]
ik ik

**Comment by legomygodamnegoo** [comment]
do you think someone has already found this?

**Comment by mike-bailey** [comment]
I have already found this. @legomygodanegoo

**Comment by legomygodamnegoo** [comment]
k

**Comment by digininja** [comment]
Lots of people have found it, there have been some very thorough audits
done over many years.
