### ISSUE TITLE
Wrong code in sqli & sqli_blind causes parse error

### ISSUE THREAD

**Issue by wushangwei** [ethicalhack3r/DVWA#129]
I set up the newest version of DVWA (Version 1.10 *Development*) using XMAPP successfully. And when I clicked into SQL Injection or SQL Injection (Blind), it returns a error:

> Parse error: syntax error, unexpected '[' in D:\xampp\htdocs\DVWA\vulnerabilities\sqli\index.php on line 65

> Parse error: syntax error, unexpected '[' in D:\xampp\htdocs\DVWA\vulnerabilities\sqli_blind\index.php on line 65

And I looked into the index.php mentioned, I noticed this at line 65:
`$num    = mysqli_fetch_row( $result )[0];`

And I edited it into:
`$num    = mysqli_fetch_row( $result );`

And all went correct.

**Comment by hcw5014** [comment]
You can switch php version to PHP 5.6

**Comment by mike-bailey** [comment]
@hcw5014 Though ideally you'd want to support the latest version of PHP, so this is an appropriate issue.

**Comment by digininja** [comment]
Can anyone confirm if this is working in Windows?

**Comment by digininja** [comment]
@mike-bailey Suggest you give this another couple of days then close it. If it didn't work in Windows I'm sure we'd have a few more people complaining about it.

**Comment by SnowJF** [comment]
I test this in windows 2008,   it works   ^-^
