### ISSUE TITLE
SQL Injection in Security Level Medium causes fatal error

### ISSUE THREAD

**Issue by wushangwei** [ethicalhack3r/DVWA#130]
If I set the security level into low then the SQL Injection and SQL Injection (Blind) work just fine.
But when I set the level into medium, then when I click into the SQL Injection or SQL injection (Blind), I get high CPU usage, and after a while it returns a fatal error like below:
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 133431312 bytes) in D:\xampp\htdocs\DVWA\vulnerabilities\sqli_blind\index.php on line 67`

I'm using xampp. How to fix it? Thanks!

**Comment by VIVEK2000** [comment]
<script>alert("This site has been hacked")</script>

**Comment by mike-bailey** [comment]
How many users did you have? It could be a memory leak but it seems related to users.

**Comment by digininja** [comment]
What version of DVWA was being used?

**Comment by mike-bailey** [comment]
Please note after about a week I'll be closing this issue.

**Comment by mike-bailey** [comment]
Closing as non-responsive
