### ISSUE TITLE
Medium CSRF is effectively the same as easy

### ISSUE THREAD

**Issue by travissuel** [ethicalhack3r/DVWA#131]
Judging from how CSRF works at the medium security level in the current release version, I believe the check of the HTTP Referer header should be as follows:
`if( stripos( $_SERVER[ 'HTTP_REFERER' ] ,$_SERVER[ 'SERVER_NAME' ])!==false ) {`
rather than:
`if( stripos( $_SERVER[ 'HTTP_REFERER' ] ,$_SERVER[ 'SERVER_NAME' ])!=-1 ) {`

Being PHP, the return type of `stripos` changes depending on the result because why not. It returns an integer should the second argument be found in the first argument, but, if the second argument is **not** found in the first, it returns a boolean false. I mean, what's the point of weak typing if you don't make hilariously terrible use of it in the official API.

So currently, all requests are allowed regardless of the contents of the Referer header. The change above preserves the current release version's behavior.

**Comment by digininja** [comment]
Seems ok to me.
