### ISSUE TITLE
Cannot change Security Level from Impossible

### ISSUE THREAD

**Issue by dbeare** [ethicalhack3r/DVWA#132]
I cannot change the security level from 'impossible.

I have changed config.inc.php to 
$_DVWA[ 'default_security_level' ] = 'low';
but the database always starts as impossible. 

Can you assist, please?

David

**Comment by digininja** [comment]
Have you already got a cookie set at impossible?

**Comment by dbeare** [comment]
I'll check later. I'm at a conference right now.

David

**Comment by dbeare** [comment]
It sorted itself out by the following day and it now in ‘low’. Thanks for the help.

 

David

**Comment by mike-bailey** [comment]
@dbeare you mind closing this if it's resolved?

**Comment by dbeare** [comment]
Hi Michael,

 

No, I don’t mind. It was very useful.

 

David
