### ISSUE TITLE
xss possible with sql injection

### ISSUE THREAD

**Issue by legomygodamnegoo** [ethicalhack3r/DVWA#133]
Now I personally think this is AWESOME, but this really isn't an issue. I just wanted to share this with other people. It is possible to produce xss when you use sql injection section of DVWA. the following code should produce the xss: (Your web server)/DVWA/vulnerabilities/sqli/?id='+or+1%3D1+%23+<script>alert("XSS")%3B<%2Fscript>&Submit=Submit# if you are logged in, and you type or copy that into your url bar, and press enter  it will pop up at least 6 XSS alerts. (YOU MUST HAVE SECURITY LEVEL ON LOW IN ORDER FOR THIS TO WORK!)

**Comment by digininja** [comment]
This type of thing is all over the app, XSS in here and SQLi in there, it
is all part of the learning experience.

**Comment by legomygodamnegoo** [comment]
I know I just wanted to share this with other people who didn't know

**Comment by legomygodamnegoo** [comment]
also you guys should add a login sql injection I would like that better than the one that is currently there

**Comment by g0tmi1k** [comment]
Feel free to make a pull request

**Comment by mike-bailey** [comment]
Does it not exist already? for instance https://github.com/ethicalhack3r/DVWA/blob/master/login.php#L33

**Comment by legomygodamnegoo** [comment]
I have tried already sql injecting the login but it never works for me.

**Comment by mike-bailey** [comment]
@digininja @g0tmi1k this can be closed
