### ISSUE TITLE
Unable to change difficulty

### ISSUE THREAD

**Issue by Kibouo** [ethicalhack3r/DVWA#136]
Changing `$_DVWA[ 'default_security_level' ] = 'impossible';` from 'impossible' to 'medium' in file `DVWA-master/config/config.inc.php` doesn't change actual difficulty (stays on 'impossible').

**Comment by digininja** [comment]
someone else reported this but it fixed itself when they cleared their
cookies. Give that a try and see.

**Comment by Kibouo** [comment]
Thanks a lot, this works!
