### ISSUE TITLE
vulnerabilities sqli php parse error

### ISSUE THREAD

**Issue by m00zh33** [ethicalhack3r/DVWA#137]
PHP Parse error: syntax error, unexpected '[' /var/www/html/DVWA-master/vulnerabilities/sqli/index.php on line 65,
original: $num = mysql_fetch_row( $result )[0];

$num = mysql_fetch_row( $result[0] ); // It works

**Comment by mike-bailey** [comment]
Considering there are not even any references currently of `mysql_fetch_row` I'm going to assume this was patched and it's just an old issue. Thank you for reporting. Feel free to open another if you find an error.
