### ISSUE TITLE
PHP module gd: Missing 

### ISSUE THREAD

**Issue by ask1234560** [ethicalhack3r/DVWA#138]
hi i am installing dvwa on my kali linux ,but when i open the server it shows php module gd : missing 
please any suggestions , thankyou in advance

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 7.0.16-3

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Missing
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: *blank*
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: 6LdK7xITAAzzAAJQTfL7fu6I-0aPl8KHHieAT_yJg

[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: No
[User: root] Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: No

Status in red, indicate there will be an issue when trying to complete some modules

**Comment by digininja** [comment]
In Ubuntu it is

php7.0-gd

so should be something very similar in Kali.

**Comment by ask1234560** [comment]
thank u sir it worked i used (apt-get php7.0-gd) ,great job.....
