### ISSUE TITLE
feature request: weak session IDs

### ISSUE THREAD

**Issue by digininja** [ethicalhack3r/DVWA#140]
I've just covered identifying weak session (or similar) IDs in class and was thinking it would be nice to add it as an issue.

As a primary session ID it would be hard but I think it would be possible to add a new section that had a button to fake a login and set a new "fake" session ID. Doing it that way would allow the security level to be taken into consideration, low would be incremental, medium maybe time based, high some hashed incremental value and then impossible a true random number.

If I get chance I'll try to write something up but thought I'd document it while I was thinking about it in case someone else had some spare time.

**Comment by digininja** [comment]
I found time, check my master branch.

https://github.com/digininja/DVWA

Still needs the help file writing but seems to work.

**Comment by ethicalhack3r** [comment]
Added some comments to your commit :)

**Comment by digininja** [comment]
If you've no other comments I'll write the help pages, add the flags and then do the PR. Going to see if I can add DOM based XSS next, I've got a working demo and ideas for levels.

**Comment by mike-bailey** [comment]
Looks like weak session IDs and DOM XSS are features in latest DVWA. Closing. Either of you can open if I'm mistaken.
