### ISSUE TITLE
rename config file

### ISSUE THREAD

**Issue by digininja** [ethicalhack3r/DVWA#144]
To stop the config file from being overwritten on an update or accidentally being pushed into Github, I suggest we rename config/config.inc.php to config/config.inc.php.dist and have people copy it to put their changes in.

Add a check in the source to throw a warning if the actual config file hasn't been created.

We can then add a .gitignore file to prevent the config file with creds in it ending up on the repo.

**Comment by mike-bailey** [comment]
I'm interested in picking this up unless there's protests.
>Add a check in the source to throw a warning if the actual config file hasn't been created.

And if that check fails but detects the .dist, use the .dist? Or just not? I'd expect it to be a hard fail (effectively a die()) if it can't detect a config, no?

**Comment by ethicalhack3r** [comment]
I believe this was addressed in this commit https://github.com/ethicalhack3r/DVWA/pull/147/commits/84da38a7ca63cde4a4309613d021369e83e0a380

**Comment by digininja** [comment]
Like Ryan says, I've already implemented it but thanks for the offer.
