### ISSUE TITLE
Got 403-Forbidden

### ISSUE THREAD

**Issue by CloudStrifeHan** [ethicalhack3r/DVWA#149]
I installed all essential packets, when I open 127.0.0.1 on webrowser but I got 403-forbidden when i tried 127.0.0.0/dvwa

Please give me solutions! I'm newbie!

**Comment by digininja** [comment]
Going to sound elitist but go away from DVWA and learn some basic sys admin
stuff first then come back.

Knowing how to debug things like this and understand what causes them will
help you understand the environment you are testing much better.

As a start I'll say go a look at the Apache logs.

**Comment by SuperSuperSuperSuper5** [comment]
this is because you web server not in right limits, if you are use the linux web server of apache, check the /var/www/html/ is the owned by apache user and apache group, if not ,use this command:

```
cd /var/www/
chown -R apache:apache html/
```
then flush the web view

**Comment by mike-bailey** [comment]
This isn't the same in all OSes. For instance many are owned by www-data. It also isn't automatically the only problem. It could be a permission (chmod) issue, etc. I agree with @digininja.

**Comment by manav014** [comment]
I was facing the same problem 
I opened htdocs folder in terminal and entered the command 
"sudo chmod 755 -R dvwa"
and then the problem was solved
