### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by ams67** [ethicalhack3r/DVWA#150]
Hello all,
I have just installed DVWA following all instructions provided by the video. It all went as described by the video but when I connect via browser to the DVWA site I get the following error:

DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment.

Any help is highly appreciated.

Thanks
T

**Comment by mike-bailey** [comment]
At the risk of sounding obvious, did you copy the config.inc.php file?
Is it in the config dir?

On Apr 25, 2017, at 7:04 PM, ams67 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello all,
I have just installed DVWA following all instructions provided by the video. It all went as described by the video but when I connect via browser to the DVWA site I get the following error:

DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment.

Any help is highly appreciated.

Thanks
T

**Comment by digininja** [comment]
I didn't think I needed to write that error message any clearer, obviously
I underestimated.

**Comment by ams67** [comment]
In all installation and configuration videos and documentation the process highlighted in the error message is not included. Hence the intention in my question was to understand was did go wrong in a fresh installation of ubuntu server and DVWA. 
Some people give too many things for granted...
I overestimated...

**Comment by digininja** [comment]
All videos are now out of date, the way the config works had changed. Read
the message and follow the instructions.

**Comment by younes7programing** [comment]
* ***Create the DVWA configuration file* ***

I suggest you doing this:

erase the file dvwa which is in the directory /var/www/html/dvwa/ and copy it again in this directory

  

>  cd /var/www/html
> 
>    sudo rm -rf dvwa/                 #to delete the file

Now go to the destination of your dvwa file that you downloaded For example for me I put it in the Desktop

    
> cd Desktop
> 
>     sudo cp -r ./dvwa/ /var/www/html/dvwa/
> 
>     cd /var/www/html/dvwa/config/
> 
>     sudo cp config.inc.php.dist  config.inc.ph

So config.inc.php will be created and most importantly do not forget to check the passwords in this file (config.inc.php).

**Comment by mike-bailey** [comment]
This can definitely be closed.

**Comment by StuartRoberts40** [comment]
younes7programing - THANK YOU!
I am just starting out with this ethical hacking and Linux stuff, following tutorials to the letter but unfortunately there are often part that are out dated and people need to take to the forums to find solutions. 

In amongst the bickering and put downs from the more experienced users you simply provided the right answer for a noob to follow. It just saved me a lot of time!! 

Thank you for that.

**Comment by Atiyasharf** [comment]
Hello all,
I have just installed DVWA following all instructions provided by the video. It all went as described by the video but when I connect via browser to the DVWA site I get the following error:

DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment.

Any help is highly appreciated.

Thanks

**Comment by mike-bailey** [comment]
@atiyasharf Did you read this thread before commenting?

**Comment by Atiyasharf** [comment]
yes

**Comment by Atiyasharf** [comment]
but i can't get my solution from above thread

**Comment by mike-bailey** [comment]
As it says, videos are out of date (except I believe @ethicalhack3r did one)

Did you copy the config.inc.php file?

**Comment by Atiyasharf** [comment]
yes copy the config.inc.php file and edit it

**Comment by mike-bailey** [comment]
Can you screenshot the config folder and post it here so I can see what you have/don't have here? Not asking for the actual file contents, just the listing

**Comment by Atiyasharf** [comment]
![windows 7 own-2017-07-14-10-55-37](https://user-images.githubusercontent.com/25964220/28200036-0e3402fa-6883-11e7-8b1d-8f0efa161884.png)

**Comment by Atiyasharf** [comment]
![windows 7 own-2017-07-14-10-57-31](https://user-images.githubusercontent.com/25964220/28200075-437f3632-6883-11e7-8b8a-1eb0f71c9c20.png)

**Comment by mike-bailey** [comment]
Your system is set up so it doesn't show the last extension of a file (as indicated by it saying "DIST File" in Type column, if curious see: https://www.howtohaven.com/system/show-file-extensions-in-windows-explorer.shtml). In Notepad hit File > Save As, make sure you have the dropdown set to "All Files" and save it as config.inc.php in the config folder.

**Comment by Atiyasharf** [comment]
ok thank you so much .

**Comment by mike-bailey** [comment]
No problem
 
 
 
>  
>  
>  
>      
>    
>  
>

**Comment by digininja** [comment]
The other problem you might have, if you have Mariadb rather than MySQL you can't use the root user so will have to set up another use for DVWA to use. There are other threads in the issues talking about that.

**Comment by rev3nant** [comment]
Truthfully, it's way easier to just remove ".dist" from the end of the 'config.inc.php.dist' file and save it like that if you're using a Windows environment.  Hope that helps!

**Comment by mike-bailey** [comment]
.dist does not appear for him based on his setup @rev3nant

**Comment by islamhakim97** [comment]
SIMPLY 👍  
1- Just copy the content of config.inc.php (which its type is "dist" as shown) .
2- create new text document  and rename it as config.inc.php 
3- past that content in that new file and save it
finally it works b happy 🥇

**Comment by Astrelysee2016** [comment]
> 
> 
> SIMPLY 👍
> 1- Just copy the content of config.inc.php (which its type is "dist" as shown) .
> 2- create new text document and rename it as config.inc.php
> 3- past that content in that new file and save it
> finally it works b happy 🥇

it worked for me  thank you !!

**Comment by mike-bailey** [comment]
For reference - it's this way because in most cases people have to make configuration changes to the file. Locking for contribution as this has been explained in multiple ways and has run it's course. Thanks all 😄
