### ISSUE TITLE
trying to install DVWA on my windows 10 machine but get error msg DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment.

### ISSUE THREAD

**Issue by smj41** [ethicalhack3r/DVWA#151]
I have install XAMPP and have downloaded DVWA and extracted it to my desktop, and after copied the DVMA-master file to C://xampp/htcdocs and renamed it dvma.  When I run localhost/ iin my browser it goes to the xampp site, but then when I run localhost/dvwa/ I get the following error:  DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment., ...When I open the "config" file in the dvwa folder it shows the "config" file and when I open it it shows the config.inc.php.dist file in it........I am at a loss of what I need to do????any help appreciated....

**Comment by digininja** [comment]
Have you followed the instructions and copied config.inc.php.dist to
config.inc.php as it says in the message?

**Comment by smj41** [comment]
I must be doing something wrong, when I extracted the dvwa.zip file it give me a file DVWA-master, which I renamed to just dvwa and the took that file and pasted it into the C://xampp/htdocs/ folder, when I open the htdocs folder it has the "dvwa" file in in and when I open it if see the "config" folder and when I open it I see "config.inc.php" file in it and it is listed as a DIST type.  I can open the file using "notepad++" and read it,  I have to admit I am not sure of what or how I am to proceed in order to get the dvwa program to open?
I am sorry that I am not more aware of how to proceed with what you are asking, and I will be very greatful for any assistance.....[terrible to get old and try and learn all this at my age 76]

**Comment by digininja** [comment]
Do you understand the concept of file extensions?

And what are you hoping to learn from DVWA?

**Comment by digininja** [comment]
And why have you created a repo on github called dvwa?

**Comment by mike-bailey** [comment]
If the listed as DIST type you probably have the extension hidden and it is the default config.inc.php.dist. You need to follow the instruction provided in the original error, then fill config.inc.php with your DB details. You aren't getting much help because the error describes exactly what is wrong and what you need to do.

Also unrelated but in the future under Windows I personally recommend having it show extensions if you're in CS or IT or related STEM fields.

**Comment by smj41** [comment]
"digininja", think I understand concept of file extensions, but who knows for sure, the reason I am trying to look at "DVWA" is that I am trying to learn about "Ethical Hacking" and in the video's I am watching they say that to download it and XAMPP, what I have, and as far as last question I don't know, guess that I misunderstood the questions when I signed up on this site, please forgive me, I am trying to do things right just taking me a little more time.

**Comment by mike-bailey** [comment]
@smj41 the videos are likely out of date
Please follow the latest one

@digininja I know this is a bandaid for until you make the next change but I think I'll come out with a new DVWA video lol

**Comment by smj41** [comment]
"mike-bailey" thanks for your info, appreciate words, will work on what you said.

**Comment by mike-bailey** [comment]
This can be closed now. The issues tab is really for issues with the codebase. Evidently this is not one.

On May 8, 2017, at 6:55 PM, smj41 <notifications@github.com<mailto:notifications@github.com>> wrote:


"mike-bailey" thanks for your info, appreciate words, will work on what you said.

**Comment by smj41** [comment]
Thanks to all for assistance, but still no luck, I am at a lose at this time, I have checked the  "config.inc.php.dist" file in the C/: xampp/htdocs/dvwa/config folder and the one that is in the in C:/ xampp/htdocs/dvwa/ directory and they both match....the only other thing that I did was change the "db--user" to "smj" and the "db--passwd to ( ) as was shown on another video I watched???  I am trying to do some studies in "Ethical Hacking" and the video said to download and use "XAMPP & DVWA", if I don't know if I need to do that or is there something that I can do???  thanks again for assistance

**Comment by mike-bailey** [comment]
Did you rename the config.inc.php.dist file like both I, digininja, and the error said? Stop relying on the videos, this was a new change that likely isn't in them.

On May 8, 2017, at 10:48 PM, smj41 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks to all for assistance, but still no luck, I am at a lose at this time, I have checked the "config.inc.php.dist" file in the C/: xampp/htdocs/dvwa/config folder and the one that is in the in C:/ xampp/htdocs/dvwa/ directory and they both match....the only other thing that I did was change the "db--user" to "smj" and the "db--passwd to ( ) as was shown on another video I watched??? I am trying to do some studies in "Ethical Hacking" and the video said to download and use "XAMPP & DVWA", if I don't know if I need to do that or is there something that I can do??? thanks again for assistance

**Comment by smj41** [comment]
mike-bailey:  if you and digininja to me about renaming the "config.inc.php.disp" file I never saw it and I don't think the error told me to either?????  I could be wrong but I am at a loss now as I have not the slightest idea of what you are telling me I need to do.....sorry, for being such a pest....thanks for your help

**Comment by mike-bailey** [comment]
In literally the first message you posted:
>Copy config/config.inc.php.dist to config/config.inc.php 

Digininja:
>Have you followed the instructions and copied config.inc.php.dist to
config.inc.php as it says in the message?

Me:
>You need to follow the instruction provided in the original error, then fill config.inc.php with your DB details

config.inc.php, not config.inc.php.dist.

**Comment by digininja** [comment]
I've suggested this to quite a few other people a don't take this
personally, but I'd recommend brushing up on your basic IT skills before
trying to look at any security related things.

Without a good solid base level, you'll struggle to understand the things
you need for DVWA. For example, you can't understand file inclusion without
understanding the file structure.

**Comment by smj41** [comment]
digininja & mike-bailey:  My thanks to both of your for your assistance, I will take you much welcomed thoughts and will do some more brushing up before digging too deep, thanks again for you thoughts  SMJ

**Comment by pslokhande** [comment]
smj41, 
I got the solution for " DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment"

I faced same problem and struggled for 3 days to solve it, and finally got the solution.
If you still in search of the solution ping me.

**Comment by digininja** [comment]
I'll give you a clue, the answer is in the error message:

"Copy config/config.inc.php.dist to config/config.inc.php and configure to
your environment"

**Comment by mike-bailey** [comment]
@ethicalhack3r please close this

**Comment by reddyes** [comment]
rename config.inc.php.dist to config.inc.php

**Comment by Objectivesmilan** [comment]
Hi. Have you solved this problem? I have the same trouble with you...

**Comment by pslokhande** [comment]
Yes solved the problem

**Comment by mike-bailey** [comment]
@Objectivesmilan did you rename the config file?

**Comment by pslokhande** [comment]
No I haven't renamed the file. I downloaded the software again from website
and reinstalled it.
And my problem is solved.


On 30-Jul-2017 11:03 PM, "Michael Bailey" <notifications@github.com> wrote:

@Objectivesmilan <https://github.com/objectivesmilan> did you rename the
config file?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ethicalhack3r/DVWA/issues/151#issuecomment-318916726>,
or mute the thread

**Comment by mike-bailey** [comment]
Just a heads up - you're probably running an out of date version

The latest version requires you rename config.inc.php.dist to config.inc.php and configure it

If you run out of date any bugs you find locally won't be supported by us

**Comment by y784439328** [comment]
Rename config.inc.php.dist to config.inc.php
