### ISSUE TITLE
SQL Injection  error “Warning: mysqli_query() expects at least 2 parameters, 1 given in”

### ISSUE THREAD

**Issue by yaoyi2008** [ethicalhack3r/DVWA#153]
When I test the SQL Injection，I got these errors：

1. low

```
Warning: mysqli_query() expects at least 2 parameters, 1 given in /home/wwwroot/default/dvwa/vulnerabilities/sqli/source/low.php on line 9
```

and I see the line 9:

`
$result = mysqli_query($query ) or die( '<pre>' . mysqli_connect_error() . '</pre>' );
`
2.  medium
```
Warning: mysqli_real_escape_string() expects exactly 2 parameters, 1 given in /home/wwwroot/default/dvwa/vulnerabilities/sqli/source/medium.php on line 6

Warning: mysqli_query() expects at least 2 parameters, 1 given in /home/wwwroot/default/dvwa/vulnerabilities/sqli/source/medium.php on line 10
```

3. high
```
Warning: mysqli_query() expects at least 2 parameters, 1 given in /home/wwwroot/default/dvwa/vulnerabilities/sqli/source/high.php on line 9
Something went wrong.
```

But in `impossible` or in `SQL Injection (Blind) `all mode，it's fine.

My environment is LNMP：
```
- DVWA 1.10
- CentOS CentOS release 6.9 (Final) 2.6.32-642.el6.x86_64
- PHP 5.4.45 (cli) (built: Apr 17 2017 15:11:30)
```

**Comment by digininja** [comment]
What version are you running?

**Comment by digininja** [comment]
To say I hate git would be an understatement, I've fixed this issue yet somehow the wrong files ended up in the pull request. Can you try checking out from here and see if it works

https://github.com/digininja/DVWA/tree/mysql_tidy

It works for me but who knows what ends up in git, you might get Shakespeare if the monkeys in the backend all work together.

**Comment by mike-bailey** [comment]
@yaoyi2008 Was your problem solved?
@digininja If you https://github.com/ethicalhack3r/DVWA/commit/086d116b19e3762f1c8fab952c2b155f60ff6995

**Comment by mike-bailey** [comment]
Accidentally hit enter and closed this with a partial message - sorry for any confusion. Great start to my contrib status! lol

**Comment by mike-bailey** [comment]
Non-responsive for about a month. Feel free to open a new issue if you tried it and it didn't work.
