### ISSUE TITLE
Could not connect to MySQL Service NEW - NOT FIXED

### ISSUE THREAD

**Issue by happsdev** [ethicalhack3r/DVWA#155]
Hi guys,

This is my 3rd time setting DVWA up - all other times has gone smoothly with no issues whatsoever, this time has taken me 4 hours and still not working!

Firstly, I've tried everything everyone's suggested. Changed /var/www/html/config/config.inc.php from 127.0.0.1 to localhost, with a SQL password (which I've verified through the CLI), without a password - I'm honestly a "tryer" and I've given it my best shot for ages!

I'm setting this up through Kali 2.0 (rolling) have have the same setup with the same OS, same PHP version (7.0, works fine on other setup). MySQL service and Apache2 running and verified through netstat -antupe

I've read through everything I can find online, have tried to hone instructions that people have given for XXAMP into Kali but nothing I do seems to work!

Does anyone, possibly @ethicalhack3r or @digininja have any idea? I truly believe in OffSec's "try harder" and I really have, I'm out of ideas!

Any help would be greatly appreciated. Setup is as follows:

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 7.0.16-3

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: *blank*
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: Missing

[User: www-data] Writable folder /var/www/html/hackable/uploads/: Yes
[User: www-data] Writable file /var/www/html/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

Status in red, indicate there will be an issue when trying to complete some modules.

Could not connect to the MySQL service.
Please check the config file.

**Comment by digininja** [comment]
Show the result of running this on the command line

mysql -u root -e select * from users;

**Comment by happsdev** [comment]
Thanks for getting back to me so quickly. 

I've copy and pasted the whole lot, in the interest of transparency, knowing that you're gonna think "why on earth has this idiot posted the whole lot?!" But, despite that, here's the whole thing!

Also, just cross referenced with my working instance on another machine and seems to be the same.

OUTPUT:

root@kali:~# mysql -u root -e select * from users;
mysql  Ver 15.1 Distrib 10.1.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Usage: mysql [OPTIONS] [database]

Default options are read from the following files in the given order:
/etc/my.cnf /etc/mysql/my.cnf ~/.my.cnf 
The following groups are read: mysql client client-server client-mariadb
The following options may be given as the first argument:
--print-defaults        Print the program argument list and exit.
--no-defaults           Don't read default options from any option file.
--defaults-file=#       Only read default options from the given file #.
--defaults-extra-file=# Read this file after the global files are read.

  -?, --help          Display this help and exit.
  -I, --help          Synonym for -?
  --abort-source-on-error 
                      Abort 'source filename' operations in case of errors
  --auto-rehash       Enable automatic rehashing. One doesn't need to use
                      'rehash' to get table and field completion, but startup
                      and reconnecting may take a longer time. Disable with
                      --disable-auto-rehash.
                      (Defaults to on; use --skip-auto-rehash to disable.)
  -A, --no-auto-rehash 
                      No automatic rehashing. One has to use 'rehash' to get
                      table and field completion. This gives a quicker start of
                      mysql and disables rehashing on reconnect.
  --auto-vertical-output 
                      Automatically switch to vertical output mode if the
                      result is wider than the terminal width.
  -B, --batch         Don't use history file. Disable interactive behavior.
                      (Enables --silent.)
  --character-sets-dir=name 
                      Directory for character set files.
  --column-type-info  Display column type information.
  -c, --comments      Preserve comments. Send comments to the server. The
                      default is --skip-comments (discard comments), enable
                      with --comments.
  -C, --compress      Use compression in server/client protocol.
  -#, --debug[=#]     This is a non-debug version. Catch this and exit.
  --debug-check       Check memory and open file usage at exit.
  -T, --debug-info    Print some debug info at exit.
  -D, --database=name Database to use.
  --default-character-set=name 
                      Set the default character set.
  --delimiter=name    Delimiter to be used.
  -e, --execute=name  Execute command and quit. (Disables --force and history
                      file.)
  -E, --vertical      Print the output of a query (rows) vertically.
  -f, --force         Continue even if we get an SQL error. Sets
                      abort-source-on-error to 0
  -G, --named-commands 
                      Enable named commands. Named commands mean this program's
                      internal commands; see mysql> help . When enabled, the
                      named commands can be used from any line of the query,
                      otherwise only from the first line, before an enter.
                      Disable with --disable-named-commands. This option is
                      disabled by default.
  -i, --ignore-spaces Ignore space after function names.
  --init-command=name SQL Command to execute when connecting to MySQL server.
                      Will automatically be re-executed when reconnecting.
  --local-infile      Enable/disable LOAD DATA LOCAL INFILE.
  -b, --no-beep       Turn off beep on error.
  -h, --host=name     Connect to host.
  -H, --html          Produce HTML output.
  -X, --xml           Produce XML output.
  --line-numbers      Write line numbers for errors.
                      (Defaults to on; use --skip-line-numbers to disable.)
  -L, --skip-line-numbers 
                      Don't write line number for errors.
  -n, --unbuffered    Flush buffer after each query.
  --column-names      Write column names in results.
                      (Defaults to on; use --skip-column-names to disable.)
  -N, --skip-column-names 
                      Don't write column names in results.
  --sigint-ignore     Ignore SIGINT (CTRL-C).
  -o, --one-database  Ignore statements except those that occur while the
                      default database is the one named at the command line.
  --pager[=name]      Pager to use to display results. If you don't supply an
                      option, the default pager is taken from your ENV variable
                      PAGER. Valid pagers are less, more, cat [> filename],
                      etc. See interactive help (\h) also. This option does not
                      work in batch mode. Disable with --disable-pager. This
                      option is disabled by default.
  -p, --password[=name] 
                      Password to use when connecting to server. If password is
                      not given it's asked from the tty.
  -P, --port=#        Port number to use for connection or 0 for default to, in
                      order of preference, my.cnf, $MYSQL_TCP_PORT,
                      /etc/services, built-in default (3306).
  --progress-reports  Get progress reports for long running commands (like
                      ALTER TABLE)
                      (Defaults to on; use --skip-progress-reports to disable.)
  --prompt=name       Set the mysql prompt to this value.
  --protocol=name     The protocol to use for connection (tcp, socket, pipe,
                      memory).
  -q, --quick         Don't cache result, print it row by row. This may slow
                      down the server if the output is suspended. Doesn't use
                      history file.
  -r, --raw           Write fields without conversion. Used with --batch.
  --reconnect         Reconnect if the connection is lost. Disable with
                      --disable-reconnect. This option is enabled by default.
                      (Defaults to on; use --skip-reconnect to disable.)
  -s, --silent        Be more silent. Print results with a tab as separator,
                      each row on new line.
  -S, --socket=name   The socket file to use for connection.
  --ssl               Enable SSL for connection (automatically enabled with
                      other flags).
  --ssl-ca=name       CA file in PEM format (check OpenSSL docs, implies
                      --ssl).
  --ssl-capath=name   CA directory (check OpenSSL docs, implies --ssl).
  --ssl-cert=name     X509 cert in PEM format (implies --ssl).
  --ssl-cipher=name   SSL cipher to use (implies --ssl).
  --ssl-key=name      X509 key in PEM format (implies --ssl).
  --ssl-crl=name      Certificate revocation list (implies --ssl).
  --ssl-crlpath=name  Certificate revocation list path (implies --ssl).
  --ssl-verify-server-cert 
                      Verify server's "Common Name" in its cert against
                      hostname used when connecting. This option is disabled by
                      default.
  -t, --table         Output in table format.
  --tee=name          Append everything into outfile. See interactive help (\h)
                      also. Does not work in batch mode. Disable with
                      --disable-tee. This option is disabled by default.
  -u, --user=name     User for login if not current user.
  -U, --safe-updates  Only allow UPDATE and DELETE that uses keys.
  -U, --i-am-a-dummy  Synonym for option --safe-updates, -U.
  -v, --verbose       Write more. (-v -v -v gives the table output format).
  -V, --version       Output version information and exit.
  -w, --wait          Wait and retry if connection is down.
  --connect-timeout=# Number of seconds before connection timeout.
  --max-allowed-packet=# 
                      The maximum packet length to send to or receive from
                      server.
  --net-buffer-length=# 
                      The buffer size for TCP/IP and socket communication.
  --select-limit=#    Automatic limit for SELECT when using --safe-updates.
  --max-join-size=#   Automatic limit for rows in a join when using
                      --safe-updates.
  --secure-auth       Refuse client connecting to server if it uses old
                      (pre-4.1.1) protocol.
  --server-arg=name   Send embedded server this as a parameter.
  --show-warnings     Show warnings after every statement.
  --plugin-dir=name   Directory for client-side plugins.
  --default-auth=name Default authentication client-side plugin to use.
  --binary-mode       By default, ASCII '\0' is disallowed and '\r\n' is
                      translated to '\n'. This switch turns off both features,
                      and also turns off parsing of all clientcommands except
                      \C and DELIMITER, in non-interactive mode (for input
                      piped to mysql or loaded using the 'source' command).
                      This is necessary when processing output from mysqlbinlog
                      that may contain blobs.

Variables (--variable-name=value)
and boolean options {FALSE|TRUE}  Value (after reading options)
--------------------------------- ----------------------------------------
abort-source-on-error             FALSE
auto-rehash                       TRUE
auto-vertical-output              FALSE
character-sets-dir                (No default value)
column-type-info                  FALSE
comments                          FALSE
compress                          FALSE
debug-check                       FALSE
debug-info                        FALSE
database                          (No default value)
default-character-set             utf8mb4
delimiter                         ;
vertical                          FALSE
force                             FALSE
named-commands                    FALSE
ignore-spaces                     FALSE
init-command                      (No default value)
local-infile                      FALSE
no-beep                           FALSE
host                              (No default value)
html                              FALSE
xml                               FALSE
line-numbers                      TRUE
unbuffered                        FALSE
column-names                      TRUE
sigint-ignore                     FALSE
port                              0
progress-reports                  FALSE
prompt                            \N [\d]> 
quick                             FALSE
raw                               FALSE
reconnect                         FALSE
socket                            (No default value)
ssl                               FALSE
ssl-ca                            (No default value)
ssl-capath                        (No default value)
ssl-cert                          (No default value)
ssl-cipher                        (No default value)
ssl-key                           (No default value)
ssl-crl                           (No default value)
ssl-crlpath                       (No default value)
ssl-verify-server-cert            FALSE
table                             FALSE
user                              root
safe-updates                      FALSE

**Comment by digininja** [comment]
Try it with quotes round the select statement

**Comment by happsdev** [comment]
Just tried in ' - same output. On further inspection, it is a slightly different output to my working version (default char set) although nothing that jumps out to me as being integral.

**Comment by digininja** [comment]
That was running?

mysql -u root -e "select * from users;"

If you get that output from running that I'll have to check the syntax
later.

**Comment by ethicalhack3r** [comment]
The syntax checks out on my machine, might need to select the database if
you have more than one though:

mysql -u root -p -e "use dvwa; select * from users;"

**Comment by happsdev** [comment]
root@kali:~# mysql -u root -e "select * from users;"
ERROR 1046 (3D000) at line 1: No database selected

I manually created dvwa to see if it would make a difference, knowing that dvwa will overwrite and delete. Selected dvwa and returned:

root@kali:~# mysql -u root -D dvwa -e "select * from users;"
ERROR 1146 (42S02) at line 1: Table 'dvwa.users' doesn't exist

I'm assuming this won't be an issue tho, as long as MySQL's running then dvwa handles the creation and overwriting?

**Comment by digininja** [comment]
You can use -d or -D to set the database rather than the use command as
well.

Wouldn't expect the help dump unless the quotes were missing or messed up.

**Comment by happsdev** [comment]
With your syntax:

root@kali:~# mysql -u root -p -e "use dvwa; select * from users;"
Enter password: <return pressed, no password entered>
ERROR 1146 (42S02) at line 1: Table 'dvwa.users' doesn't exist

**Comment by digininja** [comment]
That says that root has no password so that should be ok. Now post the
lines from the config file that have the database connection info.

**Comment by happsdev** [comment]
From config:

# Database management system to use
$DBMS = 'MySQL';
#$DBMS = 'PGSQL'; // Currently disabled

# Database variables
#   WARNING: The database specified under db_database WILL BE ENTIRELY DELETED during setup.
#   Please use a database dedicated to DVWA.
$_DVWA = array();
$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = '';

# Only used with PostgreSQL/PGSQL database selection.
$_DVWA[ 'db_port'] = '5432';

**Comment by digininja** [comment]
Looks like it should work. Look back a ticket or so and I've posted a few
lines of php that can be used to test the connection. Drop that in the dvwa
root directory and browse to it and see what happens.

**Comment by happsdev** [comment]
Cool, will have a look through the files now. Any idea of search terms? Thanks again :-)

**Comment by digininja** [comment]
Just look at the last ticket or two

**Comment by happsdev** [comment]
Ok, think I found what you were referring to, uploaded it, navigated to it, got this (which I was surprised about, wasn't expecting to see access denied). 

Any ideas based on that?

string(9) "127.0.0.1"
string(4) "dvwa"
string(4) "root"
string(0) ""
Error: Unable to connect to MySQL.
Debugging errno: 1698
Debugging error: Access denied for user 'root'@'localhost'

**Comment by digininja** [comment]
When I asked you to run:

mysql -u root -e "use dvwa; select * from users;"

you ran:

mysql -u root -p -e "use dvwa; select * from users;"

and it asked you for a password and you gave it one, am I right?

**Comment by digininja** [comment]
Drop the -p and I bet you can't connect. Give root a password and try that, see if it fixes the problem.

**Comment by ethicalhack3r** [comment]
Shouldn't db_port in the config file be commented out or set to the MySQL
default? (3306)


On 20 May 2017 23:28, "Robin Wood" <notifications@github.com> wrote:

Drop the -p and I bet you can't connect. Give root a password and try that,
see if it fixes the problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethicalhack3r/DVWA/issues/155#issuecomment-302899851>,
or mute the thread

**Comment by happsdev** [comment]
Morning guys,

Ryan: db_port - have tried commenting it out and also changing to 3306 etc. Also questioned the default MySQL port but am very lucky to have another working instance so cross checked and the working on is set to 0 on SQL side and 5432 on the config, not commented out. So hopefully shouldn't make too much difference.

Robin: Dropped the -p, seemed to connect. Output below. Going to designate a MySQL password, drop that into the config and see what happens. Fingers crossed!

root@kali:~# mysql -u root -e "use dvwa; select * from users;"
ERROR 1146 (42S02) at line 1: Table 'dvwa.users' doesn't exist

**Comment by happsdev** [comment]
Ok, update.

Changed MySQL password to 123456, dropped that into the DVWA config file, still got the same thing!

Current structure on DVWA:

MySQL username: root
MySQL password: ******
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: 6LcASSIUAAAAAMnCxZGyi01XmlETN-vin9QhnkiC

[User: www-data] Writable folder /var/www/html/hackable/uploads/: Yes
[User: www-data] Writable file /var/www/html/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

Status in red, indicate there will be an issue when trying to complete some modules.

Could not connect to the MySQL service.
Please check the config file.

**Comment by digininja** [comment]
I've no idea what you've done.

Last thoughts, check the apace error logs to see if that contain anything
interesting. You've also got display errors disabled, enable that and see
if it says anything.

**Comment by happsdev** [comment]
Well that makes two of us! Honestly have no idea - this is the same setup as my working version (VMware, Kali 2.0, same Apache and MariaDB).

Have provided the tail of Apache error.log and access.log

ERROR.log:

[Sat May 20 20:45:34.676796 2017] [:error] [pid 2538] [client 127.0.0.1:44570] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/includes/dvwaPage.inc.php on line 471
[Sat May 20 20:45:41.049892 2017] [:error] [pid 2534] [client 127.0.0.1:44574] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/includes/dvwaPage.inc.php on line 471
[Sat May 20 21:23:04.600455 2017] [:error] [pid 2534] [client 127.0.0.1:47016] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/includes/dvwaPage.inc.php on line 471
[Sat May 20 21:32:52.700483 2017] [:error] [pid 2537] [client 127.0.0.1:49052] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/includes/dvwaPage.inc.php on line 471
[Sat May 20 21:35:10.299649 2017] [mpm_prefork:notice] [pid 1886] AH00169: caught SIGTERM, shutting down
[Sat May 20 21:35:10.606001 2017] [mpm_prefork:notice] [pid 25910] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Sat May 20 21:35:10.606078 2017] [core:notice] [pid 25910] AH00094: Command line: '/usr/sbin/apache2'
[Sat May 20 21:35:42.498247 2017] [:error] [pid 25912] [client 127.0.0.1:49960] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/includes/dvwaPage.inc.php on line 471

ACCESS.log:

127.0.0.1 - - [20/May/2017:21:32:55 +0100] "GET /setup.php HTTP/1.1" 200 1900 "http://127.0.0.1/setup.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [20/May/2017:21:35:42 +0100] "GET / HTTP/1.1" 302 337 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [20/May/2017:21:35:42 +0100] "GET /login.php HTTP/1.1" 302 476 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [20/May/2017:21:35:42 +0100] "GET /setup.php HTTP/1.1" 200 1894 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [20/May/2017:21:35:46 +0100] "POST /setup.php HTTP/1.1" 302 337 "http://127.0.0.1/setup.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [20/May/2017:21:35:46 +0100] "GET /setup.php HTTP/1.1" 200 1917 "http://127.0.0.1/setup.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [20/May/2017:21:39:49 +0100] "POST /setup.php HTTP/1.1" 302 338 "http://127.0.0.1/setup.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [20/May/2017:21:39:49 +0100] "GET /setup.php HTTP/1.1" 200 1917 "http://127.0.0.1/setup.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"

**Comment by happsdev** [comment]
Gonna investigate 471 in /var/www/html/dvwa/includes/dvwaPage.inc.php

**Comment by happsdev** [comment]
SQL's not my strong point but nothing jumps out as being wrong. Only thing is Connection Error // out but am assuming that's intentional:

// Database Management --

if( $DBMS == 'MySQL' ) {
	$DBMS = htmlspecialchars(strip_tags( $DBMS ));
	$DBMS_errorFunc = 'mysql_error()';
}
elseif( $DBMS == 'PGSQL' ) {
	$DBMS = htmlspecialchars(strip_tags( $DBMS ));
	$DBMS_errorFunc = 'pg_last_error()';
}
else {
	$DBMS = "No DBMS selected.";
	$DBMS_errorFunc = '';
}

//$DBMS_connError = '
//	<div align="center">
//		<img src="' . DVWA_WEB_PAGE_TO_ROOT . 'dvwa/images/logo.png" />
//		<pre>Unable to connect to the database.<br />' . $DBMS_errorFunc . '<br /><br /></pre>
//		Click <a href="' . DVWA_WEB_PAGE_TO_ROOT . 'setup.php">here</a> to setup the database.
//	</div>';

function dvwaDatabaseConnect() {
	global $_DVWA;
	global $DBMS;
	//global $DBMS_connError;
	global $db;

	if( $DBMS == 'MySQL' ) {
		if( !@($GLOBALS["___mysqli_ston"] = mysqli_connect( $_DVWA[ 'db_server' ],  $_DVWA[ 'db_user' ],  $_DVWA[ 'db_password' ] ))
		|| !@((bool)mysqli_query($GLOBALS["___mysqli_ston"], "USE " . $_DVWA[ 'db_database' ])) ) {
			//die( $DBMS_connError );
			dvwaLogout();
			dvwaMessagePush( 'Unable to connect to the database.<br />' . $DBMS_errorFunc );
			dvwaRedirect( DVWA_WEB_PAGE_TO_ROOT . 'setup.php' );
		}
		// MySQL PDO Prepared Statements (for impossible levels)
		$db = new PDO('mysql:host=' . $_DVWA[ 'db_server' ].';dbname=' . $_DVWA[ 'db_database' ].';charset=utf8', $_DVWA[ 'db_user' ], $_DVWA[ 'db_password' ]);
		$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
		$db->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
	}
	elseif( $DBMS == 'PGSQL' ) {
		//$dbconn = pg_connect("host={$_DVWA[ 'db_server' ]} dbname={$_DVWA[ 'db_database' ]} user={$_DVWA[ 'db_user' ]} password={$_DVWA[ 'db_password' ])}"
		//or die( $DBMS_connError );
		dvwaMessagePush( 'PostgreSQL is not yet fully supported.' );
		dvwaPageReload();
	}
	else {
		die ( "Unknown {$DBMS} selected." );
	}
}

// -- END (Database Management)

**Comment by digininja** [comment]
Bug there, change mysql_error to mysqli_error and try that.

**Comment by happsdev** [comment]
Well spotted. Tried changing mysql_error to mysqli_error - same response.

Opened with bluefish instead of nano, id'd 471 as:

			dvwaMessagePush( 'Unable to connect to the database.<br />' . $DBMS_errorFunc );

But can't see that would cause any initial connection issue?

I know this all sounds like a bit of a waste of time as I've got another working version of DVWA, but I hate not getting things working and am determined to do so! It's even more frustrating that I've set this up from scratch without guides a number of times on the same setup and hardware so the fact that I can't get this to work is fecking frustrating!

**Comment by digininja** [comment]
Try localhost and the IP address of the machine instead.

**Comment by happsdev** [comment]
Tried localhost in config, same issue.
Tried machine IP in config, same issue.

Assuming you meant in the DVWA config file and trying them separately?

**Comment by digininja** [comment]
Ye.

I'm out of ideas. Will be some silly little thing like an extra an extra
space in something or a missing config setting.

**Comment by happsdev** [comment]
Yeah, I'm with you on that, so I've tried the following:

-: Transferred my existing (working) config file from Machine 1 (working) to Machine 2 (this one, not working). Tried setting up DB via DVWA, no success.

-: Compared MYSQL folders and found that /etc/mysql/ had a my.cnf link which went to /etc/alternatives/my.cnf which, again, was a link to /etc/mysql/mysql.cnf. Tidied some of that up, checked DVWA still working, all good.

-: Copied mysql directory from M1 to M2, checked and verified. Renamed old mysql folder to mysqlOLD so as to easily go back if required. Reconfigured DVWA conf file to have blank password as per M1's setup (now on M2).

-: Ran netstat -antupe, MySQL and Apache both listening and working as they should.

-: Went back to DVWA, refreshed browser, conf looked good, hit create / reset DB and... same issue!

I'm still trying but, with the config I'm now trying working on M1, I'm struggling to work out why this isn't working. Did think it could be a conflict between MySQL (which M1 is running fine) and MariaDB on M2 (which has never worked). Starting to wonder if it's worth going to the hassle of removing MariaDB and trying to set up a base version of MySQL but, knowing that MariaDB is highly compatible, can't help but think that might be a bit of a waste of time.

**Comment by happsdev** [comment]
Just set up on Ubuntu, now home page format isn't right, got all packages so time to solve that before moving back to this issue. You know some days you wonder why you work with computers... I'm having one of those weeks!

**Comment by happsdev** [comment]
Not looked into it yet but this is what I'm now getting on the Ubuntu install:

http://stackoverflow.com/questions/39257188/issue-with-dvwa-website-displaying

**Comment by digininja** [comment]
Different ticket. Work on one thing at a time.

**Comment by happsdev** [comment]
Agreed but trying to get a working instance up on another Linux box so I can copy / compare the config of MySQL and PHP. Not had much time this week but gonna get back on it later today / tomorrow. Did some reviews of configs etc the other day and nothing jumped out so next couple of days should be interesting!

**Comment by paaaz** [comment]
@happsdev I have the same problem as you! Did you find something new?
My setup: Kali Linux Rolling 2.0 on a Raspberry 3.0, PHP 7.0.18-1, MariaDB 10.1.23

**Comment by digininja** [comment]
I've found the problem...

I've just done a fresh Ubuntu install and put MariaDB on it. I ran the mysql_secure_installation script and set a password for root.

In a terminal logged in as root I can connect to MariaDB as root with the password I supplied. As any other user I can't connect as root. This is giving the correct username and password and trying localhost and 127.0.0.1.

I added a second user to the system and could log into that as either my normal user or as root.

If I put the root user and password in the DVWA config file I got an error that the site could not connect, if I change it to the new user I added then the connection is fine.

The take away, you can't use the root database user to connect to the database on an out-of-the-box MariaDB installation, you must create a new user.

One way to do this is:

create user dvwa;
grant all on *.* to dvwa identified by "p@ssword";
flush privileges;

This gives almost full power to the dvwa user so don't reuse these commands when adding users to other systems.

**Comment by happsdev** [comment]
IT WORKS!!
I identified the same issue but didn't get around to trying it before seeing your post. Thanks a lot for the info and the perseverance :-)

I used similar syntax to achieve the same thing but, after creating dvwa (user & DB), I used:

GRANT ALL ON dvwa.* TO 'dvwa'@'%';
FLUSH PRIVILEGES;

All is now up and running. Happy hacking :-)

**Comment by digininja** [comment]
The grant line is just explicitly saying that dvwa can connect from
anywhere not just local host and that it doesn't have a password.

Glad it is working.

**Comment by mike-bailey** [comment]
Seems resolved. Marking as closed.

**Comment by Darksoul101** [comment]
Thanks

**Comment by ak121150** [comment]
Hello gugs.. If you get error 
Unable to connect MySql then Please change to msql password by these commands

-} service mysql stop 
-} mysqld_safe --skip-grant-tables & 
-} mysql -uroot 
-} use mysql; 
-} update user set password=PASSWORD("enter_new_password")where user='root'; -} flush privileges; 
-} service mysql start 
-} mysql -u root -p 

.....:)
