### ISSUE TITLE
Security Setting issue

### ISSUE THREAD

**Issue by jasonfbenton** [ethicalhack3r/DVWA#16]
I'm using DVWA 1.0.7 and I'm experiencing a strange issue. The security
settings for XSS Stored page are always set to "High" no matter what I do.
I've tried changing them to low and it works for every other page but that
one.

I've restarted Apache and MySQL with no luck. I'm on Mountain Lion 10.9.2
using XAMMP 1.8.3-3.

**Comment by g0tmi1k** [comment]
This is an odd bug. 
I've had it happen to me a few times - not sure how I managed todo it tho!

What is happening, a new cookie value is being set, however it is just for that page (able to check with Firebug). 
How/why this is happening - I am not sure. Will see if I can do something for v1.10 ;).

**Comment by ethicalhack3r** [comment]
Please try the latest master version, I believe @digininja found and fixed this issue a few commits back
