### ISSUE TITLE
login page blank

### ISSUE THREAD

**Issue by Maczidane** [ethicalhack3r/DVWA#161]
Ive updated my system,installed php5.6,downloaded DVWA ,reconfigured the confic.inc.php,given permissions to the dvwa folder but when i try to access the dvwa login page through my browser,the page is blank.
Even when i try 127.0.0.1/dvwa/ ,i am immediately redirected to this localhost/dvwa/login.php page which is blank.
When i change the login.php in the url to setup.php ,the set up opens

PLEASE I NEED HELP

**Comment by digininja** [comment]
What do your error logs say?

**Comment by mike-bailey** [comment]
[admin note] Please note after 7 days I'm closing out this issue

**Comment by mike-bailey** [comment]
Close enough
