### ISSUE TITLE
one way to correct the error of the aplication

### ISSUE THREAD

**Issue by cristobalcw** [ethicalhack3r/DVWA#162]
if have a problem like DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment. you can use old versions of the aplication like 1.0.8 you can find them in the repositoy https://github.com/ethicalhack3r/DVWA/releases/tag/v1.0.8 and download the zip with the source code of the aplication

**Comment by mike-bailey** [comment]
Is this a question?
The solution to the problem is to do what it says, which is to move the dist file as it tells you to in the actual error. This is intended behavior.

**Comment by mike-bailey** [comment]
To be clear, you should not use v1.0.8, you should do as the error says and:
>Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment.

**Comment by cristobalcw** [comment]
If you can clarify where the file is to copy it in the path indicated in the message

**Comment by mike-bailey** [comment]
The file is config/config.inc.php.dist. We do not copy it by default as having a `.dist` file is to make sure people actually set up their environments, rather than just running with the default `config.inc.php` and file issues when it doesn't work. `.dist` files are relatively common.

**Comment by mike-bailey** [comment]
For more: https://stackoverflow.com/questions/16843080/what-does-dist-used-as-an-extension-of-some-source-code-file-mean

**Comment by cristobalcw** [comment]
ok thanks for the help

**Comment by mike-bailey** [comment]
No problem.
