### ISSUE TITLE
DVWA looks strange

### ISSUE THREAD

**Issue by FedeHR** [ethicalhack3r/DVWA#164]
I installed DVWA on Kali Linux and it seems to be working normally, just that it looks like if it didn't load correctly...
I leave this screenshots, the first should be the login page and the second the setup page.
Thanks in advance

![screenshot from 2017-07-13 15-24-03](https://user-images.githubusercontent.com/20077620/28184067-e3e988e2-67df-11e7-9515-094643f96393.png)
![screenshot from 2017-07-13 15-24-32](https://user-images.githubusercontent.com/20077620/28184069-e4017b1e-67df-11e7-9918-c21c2a58d2c8.png)

**Comment by mike-bailey** [comment]
Looks as though your LAMP stack, probably PHP, isn't installed successfully so it's just interpreting as HTML. Recommend reinstalling PHP.

**Comment by FedeHR** [comment]
Mhhh, I tried deleting and downloading php7.0 again, but it looks the same... Have you or someone else got another idea what could be the problem?

**Comment by digininja** [comment]
The problem is that php isn't installed or enabled, without knowing a lot
more about your environment it is hard to debug it. Which LAMP stack are
you trying to use?

**Comment by mike-bailey** [comment]
And assuming it's Apache, did you actually enable PHP in Apache?

**Comment by FedeHR** [comment]
OHHHHHHH I'M SO ASHAMED! Well, I for some reason I had disabled the php7.0 mod, such a dumb mistake...
Well thanks a lot to everybody, sorry for waisting your time
