### ISSUE TITLE
problem with php_allow_url on PHP 7 

### ISSUE THREAD

**Issue by webkodex** [ethicalhack3r/DVWA#165]
Hi, i have tried multiple times to fix this one issue related to php_allow_url inside php.ini file, its not working 
 first i set it to allow_url_include = On, this didn't work, later i tried allow_url_include = 1, even this didn't work. my php version is PHP 7.0.19-1. kindly suggest me a fix. 

DVWA running on Debian 9 VM, nginx server,mariadb 

Regards
skorpinok
![img1](https://user-images.githubusercontent.com/15958581/28241743-25b04cbc-69ab-11e7-89f7-583257941331.PNG)
![img2](https://user-images.githubusercontent.com/15958581/28241744-25bb411c-69ab-11e7-8e43-45463498f929.PNG)
![img3](https://user-images.githubusercontent.com/15958581/28241786-3f926d76-69ac-11e7-9e64-5d206ff552df.PNG)

**Comment by digininja** [comment]
I had trouble with this one as well, from memory there is a second setting
you need to enable with this one for it to work. Will check my setting
later if I remember.

**Comment by webkodex** [comment]
@digininja thank you sir, please post that setting so that i can get it fixed.

**Comment by digininja** [comment]
This is my php.ini file which works for me, see if you can pick out of it the bit you are missing:

https://pastebin.com/072SDMVk

If you want a similar, cut down version of yours, you can use this command:

```
grep -v "^;" /etc/php/7.0/apache2/php.ini|sed  '/^$/d' 
```

**Comment by webkodex** [comment]
@digininja Thank you digninja for suggestion & help, **now its fixed**. the main culprit was this inside php7.0. 


**display_errors = Off**
**display_startup_errors = Off**

Change both display errors to **On**

**Comment by digininja** [comment]
That shouldn't affect the setting up had problems with, they are for error
reporting.

**Comment by webkodex** [comment]
@digininja, yup. but it worked for me i after saw in pastebin. didn't alter anything other than this.

**Comment by mike-bailey** [comment]
Sounds like you had the setting wrong, didn't reboot the service so it didn't refresh the config, changed the other settings, rebooted the service, then all settings took effect

**Comment by webkodex** [comment]
@mike-bailey YES you are right ! that's correct...spot on

**Comment by Caroline0071** [comment]
*display_errors = Off*
 *display_startup_errors = Off*

 Change both display errors to *On*

I also changed on，but my allow_url_include didn't work

**Comment by digininja** [comment]
Those two settings won't fix the problem but they are needed. Have you
tried diffing your config with the one I posted on pastebin?

**Comment by kaliusar** [comment]
I tried to install dvwa on my kali system which is installed in VM ware and after trying so much i finally got that installed but now I am not getting the usual dvwa login page  isntead i am getting this : 

![dvwa](https://user-images.githubusercontent.com/41067973/42521268-00c5a534-842e-11e8-9f48-fb0526270b5e.jpg)

and some things are listed as "Disabled and Missing" and my php.ini file setting are this : 

![php](https://user-images.githubusercontent.com/41067973/42520638-505bec2c-842c-11e8-8159-dc7b38cf9e73.png)

I dont know how to fix this, I tried to update the required softwares too but that also did'nt work; I am a beginner so I dont know much. 
NEED HELP !!

**Comment by digininja** [comment]
@kaliusar please don't hijack other people's issues, create your own for your problems.

**Comment by mike-bailey** [comment]
Locking conversation so people don’t hijack
