### ISSUE TITLE
DVWA locked me out

### ISSUE THREAD

**Issue by Confizzeled** [ethicalhack3r/DVWA#170]
Not sure what happened exactly. 

I wasn't tinkering with anything at the time. I just fired XAMPP up and navigated to DVWA. I logged in and was reading an article from the links found under one of the attack vectors. Early I that  day I was working with DVWA and it was working fine. 

Anyways I accidentally closed my browser. So,  I navigated back to the DVWA login page and now the default creds won't allow me to log in the only error i see is "failed login". If anyone has ran into this issues or has any advice please reach out. I would love to get back to it!!!

**Comment by mike-bailey** [comment]
What creds were you using? Any error logs?

**Comment by Confizzeled** [comment]
I used "admin" and "password" and no nothing in the logs

**Comment by digininja** [comment]
Just hit the setup page and reset them, probably the easiest thing to do.

**Comment by Confizzeled** [comment]
Yea i was hoping to avoid, but its looking like my only option. Thanks anyways!

**Comment by digininja** [comment]
you could just log in as one of the other users, there are a few of them.

Line 51 onwards:

https://github.com/digininja/DVWA/blob/master/dvwa/includes/DBMS/MySQL.php

**Comment by mike-bailey** [comment]
How did this go? I'll be tagging it as non-responsive and ultimately close if I don't get an answer.
