### ISSUE TITLE
Blank Login.php page

### ISSUE THREAD

**Issue by Jayed2016** [ethicalhack3r/DVWA#171]
I've cloned the DVWA from git repo and still getting blank login page. Here's the error.log 
`[Wed Aug 23 06:19:07.384776 2017] [mpm_prefork:notice] [pid 2479] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 06:19:07.385834 2017] [core:notice] [pid 2479] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 06:49:23.603062 2017] [:error] [pid 3049] [client ::1:56850] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 471
[Wed Aug 23 06:50:19.184459 2017] [:error] [pid 2481] [client ::1:56858] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 471
[Wed Aug 23 06:55:45.551287 2017] [:error] [pid 2485] [client ::1:56878] PHP Notice:  Undefined variable: DBMS_errorFunc in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 471
[Wed Aug 23 07:16:53.801819 2017] [:error] [pid 3047] [client ::1:57092] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/DVWA-1.9/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/DVWA-1.9/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/DVWA-1.9/dvwa/includes/dvwaPage.inc.php on line 461, referer: http://localhost/dvwa/
[Wed Aug 23 07:16:57.823530 2017] [:error] [pid 3049] [client ::1:57098] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/DVWA-1.9/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/DVWA-1.9/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/DVWA-1.9/dvwa/includes/dvwaPage.inc.php on line 461, referer: http://localhost/dvwa/
[Wed Aug 23 07:23:44.658337 2017] [:error] [pid 2842] [client ::1:57108] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 07:24:19.795316 2017] [:error] [pid 2483] [client ::1:57112] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:16:30.053332 2017] [:error] [pid 2482] [client 127.0.0.1:55394] PHP Notice:  Undefined index: user_token in /var/www/html/dvwa/setup.php on line 14
[Wed Aug 23 08:16:30.059521 2017] [:error] [pid 2482] [client 127.0.0.1:55394] PHP Notice:  Undefined index: session_token in /var/www/html/dvwa/setup.php on line 14
[Wed Aug 23 08:17:43.144377 2017] [:error] [pid 2484] [client 127.0.0.1:55420] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:18:17.918573 2017] [:error] [pid 2485] [client 127.0.0.1:55432] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:18:18.901836 2017] [:error] [pid 3048] [client 127.0.0.1:55434] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:22:42.289105 2017] [mpm_prefork:notice] [pid 2479] AH00169: caught SIGTERM, shutting down
[Wed Aug 23 08:22:42.808462 2017] [mpm_prefork:notice] [pid 4997] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 08:22:42.810606 2017] [core:notice] [pid 4997] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 08:39:28.243351 2017] [mpm_prefork:notice] [pid 4997] AH00169: caught SIGTERM, shutting down
[Wed Aug 23 08:39:29.135568 2017] [mpm_prefork:notice] [pid 14783] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 08:39:29.138861 2017] [core:notice] [pid 14783] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 08:42:32.524178 2017] [:error] [pid 14789] [client ::1:57342] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Aug 23 08:42:44.025787 2017] [:error] [pid 14790] [client 127.0.0.1:55562] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:42:45.893969 2017] [:error] [pid 14866] [client 127.0.0.1:55564] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:42:52.307240 2017] [:error] [pid 14868] [client 127.0.0.1:55566] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Aug 23 08:43:16.794884 2017] [:error] [pid 14786] [client ::1:57352] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Aug 23 11:07:34.409973 2017] [mpm_prefork:notice] [pid 1718] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 11:07:34.430021 2017] [core:notice] [pid 1718] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 11:13:45.954033 2017] [:error] [pid 1724] [client ::1:50846] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:13:58.673977 2017] [:error] [pid 2063] [client ::1:50848] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:13:59.580196 2017] [:error] [pid 1720] [client ::1:50850] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:14:18.926629 2017] [:error] [pid 2093] [client ::1:50852] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:28:56.390308 2017] [:error] [pid 1721] [client ::1:51406] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:28:57.934712 2017] [:error] [pid 1722] [client ::1:51408] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:28:58.760863 2017] [:error] [pid 1723] [client ::1:51410] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:48:17.527570 2017] [:error] [pid 1724] [client ::1:51546] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:48:18.851588 2017] [:error] [pid 2063] [client ::1:51548] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:48:20.102998 2017] [:error] [pid 1720] [client ::1:51550] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 11:48:26.645339 2017] [:error] [pid 2093] [client ::1:51552] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:15:18.202270 2017] [:error] [pid 1721] [client ::1:51570] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:15:19.017644 2017] [:error] [pid 1722] [client ::1:51572] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa1/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa1/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:23:07.915111 2017] [:error] [pid 1724] [client ::1:51582] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:23:09.586994 2017] [:error] [pid 2063] [client ::1:51584] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:23:37.736667 2017] [:error] [pid 1720] [client ::1:51586] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 12:23:38.778974 2017] [:error] [pid 2093] [client ::1:51588] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 467
[Wed Aug 23 14:21:57.575111 2017] [mpm_prefork:notice] [pid 1718] AH00169: caught SIGTERM, shutting down
[Wed Aug 23 14:21:58.560609 2017] [mpm_prefork:notice] [pid 4965] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 14:21:58.597133 2017] [core:notice] [pid 4965] AH00094: Command line: '/usr/sbin/apache2'`

**Comment by digininja** [comment]
From this:

Call to undefined function mysqli_connect()

You haven't got the php MySQL library installed. Will be called
php7.0-mysql or similar.
