### ISSUE TITLE
Could not connect to the MySQL service. Please check the config file.

### ISSUE THREAD

**Issue by HasaanCh** [ethicalhack3r/DVWA#172]
Tried Every Possible Solution.
`http://i.imgur.com/U10stnd.png`

**Comment by digininja** [comment]
You can't use the root db user it the database is mariadb. Create a new
user and use that.

**Comment by HasaanCh** [comment]
Okay so i created a new user DB. DVWA by 
`mysql -u root -p
Password:
create user DVWA;
grant all on dvwa.* to DVWA@localhost identified by 'p@ssword';
flush privileges;
`
This time getting this Error 
http://i.imgur.com/Z41ZwPF.png

**Comment by digininja** [comment]
Prove you can log in on the command line using the credentials you put in
the config file. Bet there is a typo in there.

**Comment by HasaanCh** [comment]
Okay So, I take it in Working.
First of all i created a new user in mysql as "DVWA" using Root user.
After that i created new database as "DVWA" with Root user.
Then i connected the database "DVWA" with the User "DVWA".
Then changed the config file. And it worked. Thanks for the advice.

**Comment by digininja** [comment]
Glad it works.

Please close the ticket.

**Comment by nitinraavi** [comment]
@HasaanCh 
CAN u please send the commands for this processes?

Okay So, I take it in Working.
First of all i created a new user in mysql as "DVWA" using Root user.
After that i created new database as "DVWA" with Root user.
Then i connected the database "DVWA" with the User "DVWA".
Then changed the config file. And it worked. Thanks for the advice.

**Comment by mike-bailey** [comment]
Just follow https://github.com/ethicalhack3r/DVWA#database-setup

**Comment by mike-bailey** [comment]
instead of 'xxx' replace with your password

**Comment by bezoris** [comment]
> Just follow https://github.com/ethicalhack3r/DVWA#database-setup

I know this is an old thread, but have been banging my head trying to reinstall on a new box... This fixed it!

Many thanks

**Comment by ak121150** [comment]
Hello gugs.. If you get error 
Unable to connect MySql then Please change to msql password by these commands

-} service mysql stop 
-} mysqld_safe --skip-grant-tables & 
-} mysql -uroot 
-} use mysql; 
-} update user set password=PASSWORD("enter_new_password")where user='root'; -} flush privileges; 
-} service mysql start 
-} mysql -u root -p 

.....:)

**Comment by ifconfig-me** [comment]
Not sure, if anyone still facing this issue in Winx64 environments. If so,

Go to DVWA Directory >> Config >> open **config.inc.php**  and then edit $_DVWA[ 'db_password' ] = 'p@ssw0rd'; change the password to **"BLANK"**

**Comment by digininja** [comment]
That will only work if your database password is blank.
