### ISSUE TITLE
PHP module gd -- Missing

### ISSUE THREAD

**Issue by lems24** [ethicalhack3r/DVWA#174]
I've looked at the other threads but none of those issues work for me. Everything else is green for me besides the 'PHP module gd:'. I've tried 'apt-get install' on php7-gd and php7.0-gd. The error I get is 'E: Unable to loate package php7-gd.' Just wondering if someone can help me out.
![image](https://user-images.githubusercontent.com/22061721/30343233-49168b72-97c2-11e7-9632-e77decf16331.png)

**Comment by digininja** [comment]
Try

apt-cache search gd | grep php

and see what it suggests

**Comment by lems24** [comment]
When I do that nothing comes up.

**Comment by digininja** [comment]
Odd, does for me:

$ apt-cache search gd | grep php
php-gd - GD module for PHP [default]
php-horde-image - Horde Image API
php-image-text - Image_Text - Advanced text maipulations in images
php-numbers-words - PEAR module providing methods for spelling numerals in
words
php7.0-gd - GD module for PHP

**Comment by mike-bailey** [comment]
Cache may be out of date, `apt-get update` first

**Comment by lems24** [comment]
when I do apt-get update is does one line and says complete.

**Comment by lems24** [comment]
This was a fresh install but I noticed my two sources in my /etc/apt/sources.list were commented out. Explains why it was not updating. Now that I took them out apt-get update works but everything it updates it says 'is configured multiple times'.

**Comment by lems24** [comment]
I only had the two sources that came with and they were the live install ones. Just added the 'http://kali.org/kali' source and now I was able to update and install the php7.0-gd. Thanks guys :D

**Comment by mike-bailey** [comment]
No problem!

**Comment by VNSH4CK3R** [comment]
Operating system: *nix
Backend database: MySQL
PHP version: 7.0.16-3

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Enabled (Easy Mode!)
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
*PHP module gd: Missing - Only an issue if you want to play with captchas*
PHP module mysql: Installed
PHP module pdo_mysql: Installed

**Comment by digininja** [comment]
And? What is your problem or question?

**Comment by VNSH4CK3R** [comment]
thank you for your reply☺
and sorry for delay msg

i wanna be like you as coder, bug tester as ,white hacker
cause i'm new in a hacking field
can you help me...!

**Comment by christianlehnert** [comment]
type this: `sudo apt-get install php5.6-gd`

**Comment by mike-bailey** [comment]
@christianlehnert that only works if you're on PHP 5.6, which is a bit old.

**Comment by demondandy** [comment]
Setup Check
Web Server SERVER_NAME: localhost

Operating system: Windows

PHP version: 8.2.4
PHP function display_errors: Enabled
PHP function display_startup_errors: Enabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP module gd: Missing - Only an issue if you want to play with captchas
PHP module mysql: Installed
PHP module pdo_mysql: Installed


how do i recify this issue: PHP module gd: Missing - Only an issue if you want to play with captchas

**Comment by digininja** [comment]
Do you want to play with captchas? Did you read the README?
