### ISSUE TITLE
Mysql Database failed to start

### ISSUE THREAD

**Issue by kevincam3** [ethicalhack3r/DVWA#175]
![image](https://user-images.githubusercontent.com/870934/31096227-ceeff1be-a791-11e7-9956-680c03f9f3fa.png)

**Comment by mike-bailey** [comment]
Where did you get that Docker container? We don't maintain that Docker image as far as I know unless you built locally...?

**Comment by kevincam3** [comment]
I got it following this link in your Read Me here: https://hub.docker.com/r/vulnerables/web-dvwa/

**Comment by mike-bailey** [comment]
My mistake, pulling down and debugging now.

**Comment by kevincam3** [comment]
![image](https://user-images.githubusercontent.com/870934/31289868-c109d7a6-aaa0-11e7-8e7b-46a80a7ce0d9.png)

**Comment by mike-bailey** [comment]
That image looks out of date. I'll try to push one soon.

**Comment by acgpiano** [comment]
I got the same question.

**Comment by mike-bailey** [comment]
I haven’t forgotten about this, I’m just in midterms. Planning on fixing it in time for hacktoberfest though...

On Oct 12, 2017, 11:49 PM -0400, acgpiano <notifications@github.com>, wrote:

I got the same question.

**Comment by zhixiong-wan-sphinx** [comment]
Hi. Any news?

**Comment by acgpiano** [comment]
@zhixiong-wan-sphinx You can try this one.
https://hub.docker.com/r/acgpiano/dvwa/

**Comment by mike-bailey** [comment]
I got most of it done, still fixing a few minor things.

**Comment by MNWPRO** [comment]
![image](https://user-images.githubusercontent.com/29529706/33519467-1a5f081c-d7e2-11e7-91a0-4c766f4af956.png)
@mike-bailey

**Comment by mike-bailey** [comment]
Yep.

**Comment by mike-bailey** [comment]
To elaborate for people on what I'm hung up on - my mysql service won't start in the VM but literally everything else is done

**Comment by MNWPRO** [comment]
When can you fix it?
@mike-bailey

**Comment by MNWPRO** [comment]
![image](https://user-images.githubusercontent.com/29529706/33519637-d4cb3f88-d7e5-11e7-81e2-f801e1627782.png)

**Comment by mike-bailey** [comment]
Not sure, but I don't own the /vulnerables/ library, so I'd be pushing it via my own.

**Comment by MNWPRO** [comment]
So can we contact the owner of it
@mike-bailey

**Comment by MNWPRO** [comment]
or  you will  pushing a new and change the link of it

**Comment by mike-bailey** [comment]
This is the repository for the docker image if you want to talk to the owner > https://github.com/opsxcq/docker-vulnerable-dvwa

I will be pushing my own one and probably changing the link in the README though.

**Comment by mike-bailey** [comment]
So I actually figured this out. @MNWPRO is your storage driver set to AUFS for Docker? How about @kevincam3? 

Run `docker info` and note the Storage Driver

**Comment by kevincam3** [comment]
@mike-bailey My Storage driver is set to overlay2

![image](https://user-images.githubusercontent.com/870934/33520193-2504b1c6-d79d-11e7-888c-66be72995f28.png)

**Comment by mike-bailey** [comment]
That’s the issue. It needs to be aufs due an issue well beyond our project.

**Comment by kevincam3** [comment]
@mike-bailey It's not possible to change the storage driver on Docker for Windows

**Comment by mike-bailey** [comment]
Seems like it is -> https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon
Nevertheless, it's not a DVWA bug, it's wayyyy upstream, at either moby or mysql. See: https://github.com/moby/moby/issues/34390

**Comment by mike-bailey** [comment]
Closing since it's not a DVWA bug but I won't lock conversation.

**Comment by MNWPRO** [comment]
My Storage driver is set to overlay2
@mike-bailey  ,
The official recommends us to use it，It has a better performance.
![image](https://user-images.githubusercontent.com/29529706/33520739-b7c8edfc-d7fb-11e7-9752-fec988fdd552.png)

**Comment by mike-bailey** [comment]
Okay, but as I said there's an issue with using it in conjunction with mysql on Docker.

**Comment by MNWPRO** [comment]
So this is the question of MySQL, what about maraidb? Maybe MySQL needs to be updated
@mike-bailey

**Comment by mike-bailey** [comment]
Updating was part of the build and I tried the same with MariaDB. Unsurprisingly because MariaDB is just a fork so it didn’t work.

**Comment by MNWPRO** [comment]
I think so, too.This means that the new version of your release will also have this problem.Bad news

**Comment by mike-bailey** [comment]
MariaDB doesn’t work, I tested. I’m not releasing my version because there isn’t anything wrong with the main version, the issue lies with Docker+mysql incompatibilities.

**Comment by MNWPRO** [comment]
Maybe we should go to the maraidb community to ask this question，or mysql

**Comment by mike-bailey** [comment]
I don’t personally have interest in it but you are more than welcome to.

**Comment by mike-bailey** [comment]
You may also have better luck if you do a host mount to /var/lib/mysql  but I haven’t tested that and don’t really plan to.

**Comment by MNWPRO** [comment]
But there are no problems with other applications that use mysql.Confusing

**Comment by mike-bailey** [comment]
That isn't true. Scroll up where I linked the moby link.

**Comment by MNWPRO** [comment]
OK，thanks
@mike-bailey

**Comment by salvacarrion** [comment]
As it's been said above, it's not a DVWA problem. But anyway, to fix it set the storage-driver of your Docker daemon to "aufs". Go to _Docker → Preferences → Daemon → Advanced_ and type:
```
{
  "storage-driver" : "aufs"
}
```
**More:** [https://stackoverflow.com/questions/39455764/change-storage-driver-for-docker-on-os-x](https://stackoverflow.com/questions/39455764/change-storage-driver-for-docker-on-os-x)
