### ISSUE TITLE
im having a problem with setting it up

### ISSUE THREAD

**Issue by Beeq1** [ethicalhack3r/DVWA#176]
when I try to start up the Dvwa pack with curl --data 'create db=create+%2F+Reset+Database' http://127.0.0.1/dvwa/setup.php# --cookie PHPSESSID=1
Then i looked it my error logs and i got this 
[Thu Oct 05 23:35:48.146847 2017] [core:notice] [pid 5163] AH00094: Command line: '/usr/sbin/apache2'
[Thu Oct 05 23:51:27.550113 2017] [core:error] [pid 5198] (13)Permission denied: [client 127.0.0.1:55000] AH00035: access to /dvwa/setup.php denied (filesystem path '/var/www/html/dvwa/setup.php') because search permissions are missing on a component of the path
[Thu Oct 05 23:51:43.449639 2017] [core:error] [pid 5165] (13)Permission denied: [client 127.0.0.1:55002] AH00035: access to /dvwa/setup.php denied (filesystem path '/var/www/html/dvwa/setup.php') because search permissions are missing on a component of the path
[Fri Oct 06 07:05:11.980068 2017] [core:error] [pid 5167] (13)Permission denied: [client 127.0.0.1:55276] AH00035: access to /dvwa/index.html denied (filesystem path '/var/www/html/dvwa/index.html') because search permissions are missing on a component of the path
[Fri Oct 06 07:05:11.980163 2017] [core:error] [pid 5167] (13)Permission denied: [client 127.0.0.1:55276] AH00035: access to /dvwa/index.cgi denied (filesystem path '/var/www/html/dvwa/index.cgi') because search permissions are missing on a component of the path
[Fri Oct 06 07:05:11.980218 2017] [core:error] [pid 5167] (13)Permission denied: [client 127.0.0.1:55276] AH00035: access to /dvwa/index.pl denied (filesystem path '/var/www/html/dvwa/index.pl') because search permissions are missing on a component of the path
[Fri Oct 06 07:05:11.980270 2017] [core:error] [pid 5167] (13)Permission denied: [client 127.0.0.1:55276] AH00035: access to /dvwa/index.php denied (filesystem path '/var/www/html/dvwa/index.php') because search permissions are missing on a component of the path
[Fri Oct 06 07:05:11.980324 2017] [core:error] [pid 5167] (13)Permission denied: [client 127.0.0.1:55276] AH00035: access to /dvwa/index.xhtml denied (filesystem path '/var/www/html/dvwa/index.xhtml') because search permissions are missing on a component of the path
[Fri Oct 06 07:05:11.980377 2017] [core:error] [pid 5167] (13)Permission denied: [client 127.0.0.1:55276] AH00035: access to /dvwa/index.htm denied (filesystem path '/var/www/html/dvwa/index.htm') because search permissions are missing on a component of the path

**Comment by mike-bailey** [comment]
Try:

find /var/www -type d -exec chmod 755 {} \;
find /var/www -type f -exec chmod 644 {} \;

Also could be SELinux, see if `getenforce` returns "Enforcing"



(From AskUbuntu/Stack exchange)

**Comment by mike-bailey** [comment]
Please let us know here when you do and how it went.

**Comment by mike-bailey** [comment]
Marking as closed as the original poster said it's working now when they filed other issues.
