### ISSUE TITLE
allow_url_include = on

### ISSUE THREAD

**Issue by Beeq1** [ethicalhack3r/DVWA#177]
Hello there my dvwa is working fine but there is only one problem it says PHP function allow_url_include: Disabled iv changed the php.ini to allow_url_include = on and i restart mysql and apache2 but is still says in disabled please help

**Comment by mike-bailey** [comment]
Create a page called test.php in your web root, with just: `<?php phpinfo(); ?>` please and report back it's results.

**Comment by digininja** [comment]
Search the closed issues, people have had this problem before and I've
given an answer that fixed it for them.

**Comment by mike-bailey** [comment]
^ Correct
https://github.com/ethicalhack3r/DVWA/issues/134 seems most relevant

**Comment by Beeq1** [comment]
iv tried everything 
allow_url_fopen = On
allow_url_fopen = 1

allow_url_open = On
allow_url_open = 1
and it still wont work cant you sent me to right format for the php.ini

**Comment by digininja** [comment]
Are you restarting Apache between each change?

**Comment by Beeq1** [comment]
yes i have

**Comment by Beeq1** [comment]
@mike-bailey  i put it in my html folder my dvwa folder and my www folder and i even tried to chmod it and I still get the same error

**Comment by digininja** [comment]
You were supposed to browse to the page Mike told you to create and then
tell us the results.

**Comment by mike-bailey** [comment]
So..... you have the results?
