### ISSUE TITLE
php7.0-gd & php5-gd seem to be depreciated

### ISSUE THREAD

**Issue by petachew** [ethicalhack3r/DVWA#178]
![gd](https://user-images.githubusercontent.com/17328073/31346124-ee154b4e-accc-11e7-8c02-b2a6f8a9b15c.jpeg)

**Comment by petachew** [comment]
none of the past issues have fixed my issues thus far

**Comment by digininja** [comment]
and what are your issues thus far?

**Comment by petachew** [comment]
I've updated and upgraded, but my DVWA still lists the php-gd as red. I currently can't find a way to install it

**Comment by digininja** [comment]
Run this, see what comes back

```
apt-cache search php |grep gd
```

**Comment by petachew** [comment]
![a](https://user-images.githubusercontent.com/17328073/31347027-d61cf0a2-accf-11e7-881b-7d7fb72b74f5.jpeg)

**Comment by digininja** [comment]
Your apt sources are broken. Check you have them all set up and working correctly.

**Comment by petachew** [comment]
Should this be what's inside my sources.list (/etc/apt/sources.list)? :
   deb http://http.kali.org/kali kali-rolling main contrib non-free

**Comment by digininja** [comment]
No idea, I'm not a Kali user.

**Comment by mike-bailey** [comment]
A cursory search in Kali shows php-gd isn't available in Kali's default main non-free repo. Please add a repo you know (based on research) has gd in it, `apt-get update`, then install. Not a project issue though.

**Comment by sbcdave** [comment]
apt-cache search php | grep gd worked for me. Thanks.

Not sure if it matters, but my sources.list entry has contrib and non-free backwards compared to theirs.
deb http://http.kali.org/kali kali-rolling main non-free contrib

And the package names apt-cache search showed me were php-gd and php7.2-gd, I was trying php7.0-gd
