### ISSUE TITLE
recaptcha key missing

### ISSUE THREAD

**Issue by AissaouiD** [ethicalhack3r/DVWA#179]
![screenshot from 2017-10-13 21-00-32](https://user-images.githubusercontent.com/32780400/31564107-f54ff358-b061-11e7-8b84-47e2140a0330.png)

**Comment by digininja** [comment]
Assume this is a question about why the recaptcha key is marked as missing and not just a statement.

Have you set your recaptcha keys in the config file?

**Comment by AissaouiD** [comment]
yes

**Comment by digininja** [comment]
Yes to which, you have set the keys or yes it is a question?

Do you want to use the recaptcha stuff or are you just concerned about red
boxes. I can't remember where they are used but not having them won't
affect 99% of the features.

**Comment by mike-bailey** [comment]
>I can't remember where they are used
Literally just the weak captcha lesson

**Comment by digininja** [comment]
I've just set this in my config file and the box is no longer red. If you
want to get rid of the warning but aren't bothered about the weak captcha
lesson then just do this and the red will disappear.

 26 $_DVWA[ 'recaptcha_public_key' ]  = 'xx';
 27 $_DVWA[ 'recaptcha_private_key' ] = 'yy';

**Comment by AissaouiD** [comment]
digininja it work thnx 
but what about other red flags

**Comment by mike-bailey** [comment]
Did you enable allow_url_include?

**Comment by digininja** [comment]
raise a ticket per question.

Close this if you are happy with the answer

**Comment by mike-bailey** [comment]
>Close this if you are happy with the answer

It's objectively resolved, I can close.

**Comment by AissaouiD** [comment]
yes i enabled it but still red
