### ISSUE TITLE
 PHP function allow_url_include: Disabled

### ISSUE THREAD

**Issue by AissaouiD** [ethicalhack3r/DVWA#180]
i need help plz
![screenshot from 2017-10-13 21-29-54](https://user-images.githubusercontent.com/32780400/31565169-17462f14-b066-11e7-80bb-bfb1ee88a577.png)

**Comment by digininja** [comment]
Have you read the various other discussions that have been had on this
forum about this issue and tried all the solutions?

**Comment by AissaouiD** [comment]
yes i tried them all

**Comment by digininja** [comment]
I don't know the exact location of your php.ini file but post a copy of the
result of the equivalent of this from your box:

```
grep allow_ /etc/php/7.0/apache2/php.ini
```

It should have these two lines in it

```
allow_url_fopen = On
allow_url_include = On
```

**Comment by AissaouiD** [comment]
yes i found it

**Comment by digininja** [comment]
And....?

You aren't very talkative for someone who wants help.

**Comment by AissaouiD** [comment]
thnx for ur help

**Comment by qwertylmao** [comment]
Did Also nothing has changed, please help
