### ISSUE TITLE
Could not connect to the MySQL service.

### ISSUE THREAD

**Issue by AissaouiD** [ethicalhack3r/DVWA#181]
i need help 
![screenshot from 2017-10-13 22-43-03](https://user-images.githubusercontent.com/32780400/31567562-6890efa8-b070-11e7-89ff-ce40ab72328a.png)

**Comment by digininja** [comment]
Without seeing any detailed errors I'm going to guess that you are running MariaDB, have set a password on the root user and are trying to connect with that which you can't do. Read the issues, I've got a post about it somewhere.

**Comment by AissaouiD** [comment]
first am bad in English sorry about that 
and yes i use MariaDB

**Comment by digininja** [comment]
Create a new db user, give it full access, set a password, use that in the
config. Full details are kicking around in the closed issues somewhere as
this has been worked through before.

**Comment by AissaouiD** [comment]
i do that but still the same problem
![screenshot from 2017-10-13 23-05-44](https://user-images.githubusercontent.com/32780400/31568303-df58c27a-b073-11e7-84e1-ba82806fc71d.png)

**Comment by digininja** [comment]
have you set those credentials in the config file?

**Comment by AissaouiD** [comment]
thank u so much 
thank for ur time
