### ISSUE TITLE
CSRF token is incorrect

### ISSUE THREAD

**Issue by AissaouiD** [ethicalhack3r/DVWA#182]
i need help
![screenshot from 2017-10-14 14-54-08](https://user-images.githubusercontent.com/32780400/31576294-15dc2844-b0f8-11e7-92a9-d576d65e98a1.png)

**Comment by digininja** [comment]
At this point you are just asking for answers. Go learn about SQL
injection, then about blind SQLi and then you should be able to answer the
labs.
