### ISSUE TITLE
Generate multiple installation of DVWA

### ISSUE THREAD

**Issue by GoldraK** [ethicalhack3r/DVWA#184]
Hello,
I have created a script to generate multiple installations of DVWA for when I give web security workshops and not have to do it by hand, so that each student has his own DVWA and I can break with total freedom.

https://github.com/GoldraK/DVWA-Instan

A greeting.

**Comment by digininja** [comment]
Don't forget to set the permissions of phpids as well.

Looks good though.

**Comment by lotfiking** [comment]
i have problem with php-gd the version i use is : PHP 5.6.17-1 (cli) because php7.0 and php7.1 give me many problem with DBmaria database any suggestion or solution here

**Comment by digininja** [comment]
DVWA works fine in PHP 7 and 7.1. If your question is about DVWA in general rather than asking about this script, raise a new issue and people can look into it.

For this script, just update it to reference the appropriate v5 packages rather than the 7 ones.

**Comment by GoldraK** [comment]
Then I prepare an update for old systems that work with php5

**Comment by mike-bailey** [comment]
Another option for this is to use Docker. I'm pushing the image soon.

Closing this as it isn't an issue, but I agree this is cool.
