### ISSUE TITLE
i cant solve it

### ISSUE THREAD

**Issue by Irfan06** [ethicalhack3r/DVWA#185]
Could not connect to the MySQL service.
Please check the config file.

**Comment by digininja** [comment]
Have you checked the config file and the credentials?

**Comment by Irfan06** [comment]
what are the things I have to check?

**Comment by mike-bailey** [comment]
@Irfan06 make sure config/config.inc.php.dist has the proper MySQL credentials and settings, then copy it to config/config.inc.php

**Comment by Irfan06** [comment]
this is my config file

**Comment by digininja** [comment]
Try again.

You need to check you can log into MySQL as the user you put in the config
file and, if you are using mariadb, don't use root, create a new user.

**Comment by Irfan06** [comment]
How do I check I'm using MariaDB or MySQL in kali linux?

**Comment by mike-bailey** [comment]
Which did you install? Did you install either of them?

**Comment by digininja** [comment]
If you really want to learn about security then I strongly suggest learning
some Linux admin skills first. It might seem a bit more boring than playing
with a vulnerable web app but it will make things so much easier in the
long run.

If you don't want to learn, you'll be running mariadb.

**Comment by Irfan06** [comment]
I install nothing in kali linux
I thought byDefault It has Apache2 and Mysql

**Comment by mike-bailey** [comment]
It does not. You'd need to run a LAMP stack. Try this: https://sujaykundu.blogspot.com/2017/02/how-to-install-lamp-stack-on-kali-linux.html

**Comment by mike-bailey** [comment]
Any progress?

**Comment by Irfan06** [comment]
Ya, I got it by using Xampp

**Comment by digininja** [comment]
Good.

Please close this ticket.
