### ISSUE TITLE
server problem

### ISSUE THREAD

**Issue by 85tomandjerry** [ethicalhack3r/DVWA#186]
i am unable to connect to apache2 and mysql server. it's showing that "Could not connect to the MySQL service. Please check the config file."

**Comment by digininja** [comment]
Have you read through these issues and tried the things suggested that fix
this problem for everyone else?

**Comment by 85tomandjerry** [comment]
yes, i have read.
i have sent the screen short. Please check this.
https://ibb.co/f0S1rR

**Comment by digininja** [comment]
Document what you have tried so far so we don't waste our time telling you
to try things you've already done.

**Comment by 85tomandjerry** [comment]
when i'm trying to create/reset database, the error showing (Could not connect to the MySQL service.
Please check the config file). And i'm not able to open dvwa login page.

**Comment by 85tomandjerry** [comment]
could you tell me how can i overcome from this problem?

**Comment by digininja** [comment]
And again...

Document what you have tried so far so we don't waste our time telling you
to try things you've already done

Tell us everything you've done to try to fix the problem, not what the
problem is, then we can help you.

**Comment by 85tomandjerry** [comment]
i am not able to connect mySql server, when trying to open dvwa

**Comment by digininja** [comment]
Yes, you've said that. I asked you to read through the closed issues in the
forum and try other fixes suggested, you said you'd tried them and they
hadn't worked. What I'm asking you to do is to say what you've tried so we
don't waste our time suggestion things you've already done.

**Comment by 85tomandjerry** [comment]
i run the command- service apache2 start and service mysql start

**Comment by digininja** [comment]
Ok, so you haven't read through the closed issues have you?

Go read those, the answers will be in there.

**Comment by 85tomandjerry** [comment]
i follow all the steps , mentioned in read me file. But still it does not work.
in terminal command is executed successfully. And i opened the http://localhost/dvwa/setup.php page. after that the following error occurred. Please see the screen short.

https://ibb.co/f0S1rR

**Comment by digininja** [comment]
I'll try once more, READ THE CLOSED ISSUES, THE ANSWERS ARE IN THERE.

Go to github, select issues, select closed, read.

**Comment by 85tomandjerry** [comment]
Thanks
