### ISSUE TITLE
maybe send X-XSS-Protection: 0?

### ISSUE THREAD

**Issue by maltek** [ethicalhack3r/DVWA#188]
Most browsers (but not Firefox) have XSS filters nowadays, that make it hard to test for reflected XSS. I'm thinking the XSS challenges should send `X-XSS-Protection: 0` to disable those. (Possibly only on some levels?)

**Comment by mike-bailey** [comment]
I agree with this, @ethicalhack3r thoughts?

**Comment by digininja** [comment]
Sounds good to me. Set it on all but impossible for reflected. Never tested
to see if chrome honours it or not though.

**Comment by mike-bailey** [comment]
Chrome does, quite aggressively at that.

**Comment by digininja** [comment]
I meant does it honour it when set to 0. I.e. does it disable all
protections?

**Comment by mike-bailey** [comment]
I believe so if memory serves. I used to muck with that header and I only use Chrome so it's a safe assumption.

**Comment by digininja** [comment]
Let's set it and see then.

**Comment by digininja** [comment]
I've just done a pull request in #189. It does seem to work for me with Chrome as it allowed a basic reflected alert box in low security.

**Comment by mike-bailey** [comment]
Sounds like it's solved then.
