### ISSUE TITLE
DVWA 

### ISSUE THREAD

**Issue by root-technical** [ethicalhack3r/DVWA#191]
Please **
![screenshot from 2017-11-08 12-05-36](https://user-images.githubusercontent.com/26339358/32562775-821f9a16-c47d-11e7-9d08-7c9e1057d894.png)
help** me to fix these issues on **DVWA** setup

PHP function allow_url_include: Disabled
PHP module gd: Missing

Thank you!

**Comment by digininja** [comment]
Read the closed issues, both of these have been asked many many times and
answered in full.

**Comment by root-technical** [comment]
I have edited the php.ini file correctly. But it shows the same error.
![screenshot from 2017-11-08 12-28-57](https://user-images.githubusercontent.com/26339358/32563918-818421c8-c480-11e7-8db4-410489451367.png)

**Comment by digininja** [comment]
Run through all the other debugging suggested as well. Restarting Apache,
sending us phpinfo output etc.

**Comment by mike-bailey** [comment]
Isn't it supposed to be = on? not on? Marking this as inactive since they didn't respond to @digininja

**Comment by digininja** [comment]
Good spot, that was probably it.

**Comment by mike-bailey** [comment]
@root-technical Please note your issue will be closed in 7 days after the label was added should it not be responded to.
