### ISSUE TITLE
PHP function allow_url_include: Disabled

### ISSUE THREAD

**Issue by Beeq1** [ethicalhack3r/DVWA#192]
I have done every thing to make this work. My dvwa is working but this error keeps on comming up.
i have changed the .htaccess file to #php_flag allow_url_fopen on
#php_flag allow_url_include on
and my php.ini to magic_quotes_gpc = Off
allow_url_fopen = on
allow_url_open = On
I have tried every thing to make it work

**Comment by digininja** [comment]
You can't do this in htaccess by default, you have to do it in the php.ini
file.

Unless you are planning to work on the file inclusion labs then just ignore
it

**Comment by mike-bailey** [comment]
Did you restart after you edited your php.ini? Per #199

**Comment by mike-bailey** [comment]
Please note due to past inactivity on your past issues I'm going to start the clock right away and say if the above message doesn't get a response in 7 days we're going to close it.

**Comment by Beeq1** [comment]
I have restarted after I edited the php.ini I have restarted my apache and mysql

**Comment by digininja** [comment]
Do you care about the file inclusion labs?

**Comment by CongVanTrinh** [comment]
i have two erro

PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Installed
PHP module pdo_mysql: Missing

**Comment by Beeq1** [comment]
@digininja 
no not at all

**Comment by digininja** [comment]
In which case, ignore the warning, it won't affect you.

**Comment by Beeq1** [comment]
but it wont let me create a dvwa db with out it

**Comment by digininja** [comment]
That doesn't stop you creating the database, if you can't then something
else is. My bet, you are using Kali and have root as your database account.

**Comment by Beeq1** [comment]
but it wont let me create a dvwa db with out it tho

**Comment by mike-bailey** [comment]
As Robin said, it’s unrelated to creating the db

**Comment by Beeq1** [comment]
@digininja 
Thats sounds like a problem to me becuase I am using kali and I think I did use root.
Is there any way I can fix it ?

**Comment by mike-bailey** [comment]
Are you using a MariaDB? If so, please read the README

**Comment by Beeq1** [comment]
I have mariaDb on my linux but I dont use it for my dvwa or anything els

**Comment by mike-bailey** [comment]
So you are using both MariaDB and MySQL...?

**Comment by mike-bailey** [comment]
It’s possible but highly unlikely you do. How was MySQL server and MariaDB installed?

**Comment by digininja** [comment]
Beeq1, the problem is your database user, the problem and it's fix is well
documented.

**Comment by Beeq1** [comment]
Sorry I didn't respond for a while I had some problems.
I think I have a Edited Kali linux or it just might be the newest version of kali linux, But im pretty sure It was edited because when I first ran kali linux I realized I had both of them I didnt think it was much of a problem.  It looks like this when I run mysql.
------------------------------------------------------------
pen@Master:~$ su
Password: 
root@Master:/home/pen# service
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
root@Master:/home/pen# service mysql start
root@Master:/home/pen# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 32
Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> Ctrl-C -- exit!
Aborted
------------------------------------------------------------------------------------

**Comment by mike-bailey** [comment]
Okay

**Comment by scarofkovu** [comment]
You have to change this one opt/lampp/etc/php.ini, not the one in **dvwa** folder. Change /lampp by your web service stack if u need it.
`cd /opt/lampp/etc`
`chmod 777 php.ini` (if u didn't loged as root)
allow_url_include=On

**Comment by BahaEddineKsib** [comment]
@scarofkovu  thank u
