### ISSUE TITLE
DVWA connection was reset issue

### ISSUE THREAD

**Issue by ishara1000** [ethicalhack3r/DVWA#193]
Hi guyz. I cannot connect to dvwa, localhost error. it says connection was reset. this issue only affect to dvwa

**Comment by digininja** [comment]
Let me get my crystal ball out and then I'll be able to see your full
config and understand exactly what is going on.

**Comment by ishara1000** [comment]
Thank you i solved it. I reinstall apache2 server. then it work

**Comment by digininja** [comment]
That's good, please close the ticket now

**Comment by DunteCityzen** [comment]
how did you solve it?

**Comment by digininja** [comment]
It literally says in his answer.

>  I reinstall apache2 server. then it work

I can't comment as to what was wrong or how this fixed it as the initial problem was never actually explained.

If you are having problems, raise a new ticket and fully explain what is going wrong, what you've tried to do to fix it, and all appropriate logs and config files.
