### ISSUE TITLE
Having Issue connecting MYSQL service

### ISSUE THREAD

**Issue by RoninCD** [ethicalhack3r/DVWA#194]
![kali-2017-11-12-10-46-41](https://user-images.githubusercontent.com/25575051/32700757-69a616f0-c797-11e7-9602-2906e62dc99e.png)
![kali-2017-11-12-10-47-57](https://user-images.githubusercontent.com/25575051/32700758-69b10966-c797-11e7-8233-17de4923ecd8.png)
![kali-2017-11-12-10-48-39](https://user-images.githubusercontent.com/25575051/32700759-69bb78ba-c797-11e7-87f1-8b247d1177bd.png)
![kali-2017-11-12-10-49-18](https://user-images.githubusercontent.com/25575051/32700760-69c4c19a-c797-11e7-89ab-60f16c5a6e5e.png)

Does Anyone know what else to do cause I'm having trouble

Thx

**Comment by digininja** [comment]
You can't use root with mariadb and DVWA, use a different account.

Read closed issues, it is fully documented.

**Comment by RoninCD** [comment]
Yup.

How to Create a New User
within the MySQL shell:

CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON * . * TO 'newuser'@'localhost';
FLUSH PRIVILEGES;

Then configure your user through config.inc.php file the DVWA/config folder....

Thx.. Sorry about the redundant issues.
