### ISSUE TITLE
Error when creating database

### ISSUE THREAD

**Issue by jharris10** [ethicalhack3r/DVWA#196]
I get the following error during setup.
Ubuntu 16.0.4
Apache2
php7.0

Data could not be inserted into 'users' table
SQL: Data too long for column 'avatar' at row 1
All other config shows 'ok' green in setup page.  When I run the SQL commands included in/var/www/html/DVWA-master/dvwa/includes/DBMS MYSql.php file they complete ok and the tables are created.

**Comment by digininja** [comment]
What happens if you rerun the setup now you've created everything by hand?

**Comment by jharris10** [comment]
Same problem unfortunately

Operating system: *nix
Backend database: MySQL
PHP version: 7.0.22-0ubuntu0.16.04.1

Web Server SERVER_NAME: xffalb-1019707212.us-west-2.elb.amazonaws.com

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: ******
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: Missing

[User: root] Writable folder /var/www/html/DVWA-master/hackable/uploads/: Yes
[User: root] Writable file /var/www/html/DVWA-master/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

Status in red, indicate there will be an issue when trying to complete some modules.



Create / Reset Database


Database has been created.
'users' table was created.
Data could not be inserted into 'users' table
SQL: Data too long for column 'avatar' at row 1

DB is dropped ok but the tables are not recreated when the Reset is run

**Comment by jharris10** [comment]
Database changed
mysql> show tables
    -> ;
+----------------+
| Tables_in_dvwa |
+----------------+
| users          |
+----------------+
1 row in set (0.00 sec)

**Comment by digininja** [comment]
That looks like the users table is created but not the guestbook table, you said originally that it failed on the users table so this seems intermittent, am I right or missing something?

**Comment by jharris10** [comment]
It creates the table but seems to error when populating the users table with data. 
This is the error
"Data could not be inserted into 'users' table
SQL: Data too long for column 'avatar' at row 1"
mysql> describe users;
+--------------+-------------+------+-----+-------------------+-----------------------------+
| Field        | Type        | Null | Key | Default           | Extra                       |
+--------------+-------------+------+-----+-------------------+-----------------------------+
| user_id      | int(6)      | NO   | PRI | NULL              |                             |
| first_name   | varchar(15) | YES  |     | NULL              |                             |
| last_name    | varchar(15) | YES  |     | NULL              |                             |
| user         | varchar(15) | YES  |     | NULL              |                             |
| password     | varchar(32) | YES  |     | NULL              |                             |
| avatar       | varchar(70) | YES  |     | NULL              |                             |
| last_login   | timestamp   | NO   |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
| failed_login | int(3)      | YES  |     | NULL              |                             |
+--------------+-------------+------+-----+-------------------+-----------------------------+
8 rows in set (0.00 sec)

mysql> select * from users;
Empty set (0.00 sec)

mysql> show tables
    -> ;
+----------------+
| Tables_in_dvwa |
+----------------+
| users          |
+----------------+
1 row in set (0.00 sec)

************************************

when I run the command from the cli

************************************
mysql> INSERT INTO users VALUES
    ->         ('1','admin','admin','admin',MD5('password'),'{$baseUrl}admin.jpg', NOW(), '0'),
    ->         ('2','Gordon','Brown','gordonb',MD5('abc123'),'{$baseUrl}gordonb.jpg', NOW(), '0'),
    ->         ('3','Hack','Me','1337',MD5('charley'),'{$baseUrl}1337.jpg', NOW(), '0'),
    ->         ('4','Pablo','Picasso','pablo',MD5('letmein'),'{$baseUrl}pablo.jpg', NOW(), '0'),
    ->         ('5','Bob','Smith','smithy',MD5('password'),'{$baseUrl}smithy.jpg', NOW(), '0');
Query OK, 5 rows affected (0.00 sec)
Records: 5  Duplicates: 0  Warnings: 0

mysql> select * from users;
+---------+------------+-----------+---------+----------------------------------+-----------------------+---------------------+--------------+
| user_id | first_name | last_name | user    | password                         | avatar                | last_login          | failed_login |
+---------+------------+-----------+---------+----------------------------------+-----------------------+---------------------+--------------+
|       1 | admin      | admin     | admin   | 5f4dcc3b5aa765d61d8327deb882cf99 | {$baseUrl}admin.jpg   | 2017-11-13 15:34:11 |            0 |
|       2 | Gordon     | Brown     | gordonb | e99a18c428cb38d5f260853678922e03 | {$baseUrl}gordonb.jpg | 2017-11-13 15:34:11 |            0 |
|       3 | Hack       | Me        | 1337    | 8d3533d75ae2c3966d7e0d4fcc69216b | {$baseUrl}1337.jpg    | 2017-11-13 15:34:11 |            0 |
|       4 | Pablo      | Picasso   | pablo   | 0d107d09f5bbe40cade3de5c71e9e9b7 | {$baseUrl}pablo.jpg   | 2017-11-13 15:34:11 |            0 |
|       5 | Bob        | Smith     | smithy  | 5f4dcc3b5aa765d61d8327deb882cf99 | {$baseUrl}smithy.jpg  | 2017-11-13 15:34:11 |            0 |
+---------+------------+-----------+---------+----------------------------------+-----------------------+---------------------+--------------+
5 rows in set (0.00 sec)

mysql>

**Comment by digininja** [comment]
the avatar field has a max of 70 chars and when it gets inserted from the
setup script it is generated in the format

{$baseUrl}admin.jpg

My guess is that your base URL is longer than 61 characters and so it is
creating a field value over the 70 char limit and then failing.

**Comment by jharris10** [comment]
yes thanks....just realised that so the $baseUrl is set from $_Server
just checked that and as its an AWS instance it is over 61 characters. 
xffalb-101970xxxx.us-west-2.elb.amazonaws.com.
Thanks for your help.  Now I need to figure out how to modify the $_Server variable to get it under 61 characters. 
Thanks

**Comment by digininja** [comment]
Just update the database definition to 255 chars and you'll be fine.

**Comment by jharris10** [comment]
Thank you for your help.  

That has fixed it.   I run the setup as an AWS user-data install script modifying the field during install does the job for me. 
sed -i "s/avatar varchar(70)/avatar varchar(100)/g" /var/www/html/DVWA-master/dvwa/includes/DBMS/MySQL.php,

**Comment by digininja** [comment]
It is nice not being asked how to install php-gd for a change!
