### ISSUE TITLE
PHP function allow_url_include: Disabled

### ISSUE THREAD

**Issue by Beeq1** [ethicalhack3r/DVWA#199]
I have tried every thing It tells me when i get to my 127.0.0.1/dvwa it says PHP function allow_url_include: Disabled in red When i click the button where it says create / reset database it says Could not connect to the MySQL service.
Please check the config file.
I have asked people and they say change your php.ini file and i have I changed it to
magic_quotes_gpc = Off
allow_url_fopen = on
allow_url_open = On
And it still says PHP function allow_url_include: Disabled

**Comment by mike-bailey** [comment]
Don't open a new issue just because it isn't solved yet. Comment on your other issue.
