### ISSUE TITLE
where is allow_url_fopen and allow_url_include used

### ISSUE THREAD

**Issue by digininja** [ethicalhack3r/DVWA#200]
Am I right in thinking that these two functions are only required for the file inclusion lab? If so, then I'm tempted to add a message to say not to worry about those two unless you want to do LFI and RFI. Will also add a pointer on how to fix it.

May move some people to self-service help and stop the constant panic about a red status.

**Comment by mike-bailey** [comment]
I can't think off the top of my head where else.

**Comment by mike-bailey** [comment]
The README says SQL injection uses it but I don't get how/why.

**Comment by digininja** [comment]
I can't think of a reason either

**Comment by digininja** [comment]
I've just done PR #202 to add some more info
