### ISSUE TITLE
Testing automatically via script

### ISSUE THREAD

**Issue by koalalorenzo** [ethicalhack3r/DVWA#210]
Hello!
I am trying to build a simple set of tests that once the DVWA is deployed and configured it will validate that all the security flaws are possible or not possible.

The main reason is that I want to understand if a WAF can block some of these vulnerability and instead of running each vulnerability test manually, I would like to know if somebody already scripted out something to use.

Any?
Thanks again for your help! DVWA is awesome 👍

**Comment by digininja** [comment]
I've not heard of anything like this but it should definitely be possible.
Most of the stages have fairly obvious inputs and then fixed outputs you
can check.

**Comment by mike-bailey** [comment]
These are basically unit tests. Sounds like they aren’t out there. Closing.
