### ISSUE TITLE
DVWA problem

### ISSUE THREAD

**Issue by unshul** [ethicalhack3r/DVWA#213]
When i am trying to open "127.0.01/dvwa/setup.php", It is showing me that "The connection was reset" .
I am unable to open my dvwa web application. Please help me to sort out this problem

**Comment by digininja** [comment]
Give us some more info to work with...

What OS, what version, how did you install it, have you configured it, what do the web server logs say, any more information which you think might help.

**Comment by unshul** [comment]
I am using Kali 2017.3 in a live machine. yes i have configured it but i don't know about the web server logs

**Comment by digininja** [comment]
Is the web server running?

**Comment by digininja** [comment]
So check the logs and see what they say

**Comment by unshul** [comment]
How to check them

**Comment by mike-bailey** [comment]
cat /var/log/apache2/error.log

Assuming Apache2

Please upload it to something like pastebin.com or gist.github.com and paste the link here

**Comment by unshul** [comment]
I have uploaded it. Please check out:
[https://pastebin.com/MgphQppX](url)

**Comment by digininja** [comment]
You've broken Apache, did you try an update on the OS and something failed?

I'd uninstall Apache with

apt-get remove apache

then do an update and upgrade

apt-get update && apt-get upgrade

then reinstall Apache

apt-get install apache

Watch out for any errors or messages at every step.

**Comment by unshul** [comment]
I have done a update in last 2 hrs. but there was not any error. but now i am trying your given steps...

**Comment by unshul** [comment]
Sorry for late reply because of my poor internet connection. I have followed all of your steps and now it is working fine. I was struggling for this problem from past two days. Thnks for the help...

**Comment by digininja** [comment]
Glad it worked, please close the ticket.

**Comment by mike-bailey** [comment]
I got it.
