### ISSUE TITLE
LI - high

### ISSUE THREAD

**Issue by AddaxSoft** [ethicalhack3r/DVWA#214]
Was the previous version a bug?

If not, how would you bypass this check I wonder?

![image](https://user-images.githubusercontent.com/6898938/35152416-b05925fe-fd22-11e7-99c2-af8b3bfbcae2.png)

**Comment by digininja** [comment]
> Was the previous version a bug?

What do you mean? What previous version?

Are you asking for the solution?

**Comment by AddaxSoft** [comment]
Let me explain, I downlaoded the ISO file form vulnhub, and the high version of the challenge was the one I posted here. It seems impossible to bypass. I was wondeirng if it was a bug (corrected in newer version here in github) or it is still vulnerable.

If yes, how would you bypass the check?
I'm curious.

**Comment by digininja** [comment]
I've no idea what version the one is that comes with vulnhub but I'd suggest always running the latest github version. The version here is different and I've just checked and can be bypassed at the high level.

The code you pasted doesn't look like it could be bypassed but it would depend on what other code is around it so without context I don't know what you could do with it.

**Comment by mike-bailey** [comment]
Feel free to continue discussion, but closing as this isn't an issue

**Comment by AddaxSoft** [comment]
@digininja well, it's [here](https://www.vulnhub.com/entry/damn-vulnerable-web-application-dvwa-107,43/), feel free to try yourself and let me know if you can bypass it.

I think it was a bug and it's now fixed in the latest version.


@mike-bailey I would still like to know if it was a bug or the code is vulnerable.

**Comment by mike-bailey** [comment]
@AddaxSoft I'm gonna guess it was a bug if it has since been changed like @digininja said

**Comment by mike-bailey** [comment]
looks like vulnhub is basically hosting a 2011 version

**Comment by AddaxSoft** [comment]
Ah now that sucks, because I was hoping it's not a bug... 
We found a bypass but we can't do anything with it, basically if $file = NULL the filter is bypassed

**Comment by mike-bailey** [comment]
Unfortunately a risk associated with obsolete software. Sorry about that. It probably was broken in other ways.

**Comment by digininja** [comment]
If it was before the impossible level was introduced then high was often
not possible or very obscure so that may be it.

**Comment by AddaxSoft** [comment]
@digininja seems like it, so high was like a way to show how you would protect against these attacks I guess?

**Comment by digininja** [comment]
I think it was just supposed to be hard but some were maybe a little too
hard.
