### ISSUE TITLE
error during dvwa DB setup

### ISSUE THREAD

**Issue by Linux-007** [ethicalhack3r/DVWA#215]
![screen shot 2018-01-21 at 4 57 50 pm](https://user-images.githubusercontent.com/35172869/35193679-442199ba-fecc-11e7-8ffd-f5d5c0f8e164.png)
![screen shot 2018-01-21 at 4 56 29 pm](https://user-images.githubusercontent.com/35172869/35193680-44e90158-fecc-11e7-8b4a-e43e7236a6ae.png)
![screen shot 2018-01-21 at 4 56 19 pm](https://user-images.githubusercontent.com/35172869/35193681-4520b6d4-fecc-11e7-86b5-4e652e3fdb15.png)
 
I did the installation , missed something , cannot go the next page ?

**Comment by digininja** [comment]
Try reading the messages on the screen, they tell you exactly what is wrong.

**Comment by Linux-007** [comment]
i am  not able to change users ? can you help 
![screen shot 2018-01-21 at 7 29 47 pm](https://user-images.githubusercontent.com/35172869/35194910-83c17ea4-fee1-11e7-9ede-d6b285735048.png)

**Comment by digininja** [comment]
Again, read the error messages, the grant failed. Go back through the
commands you ran, run each at a time and check the results.

**Comment by mike-bailey** [comment]
Replace xxx with your password
