### ISSUE TITLE
Command injection output is messed up

### ISSUE THREAD

**Issue by MrPhenomOne** [ethicalhack3r/DVWA#216]
When I do command injection, I have in output rhomboids with question marks. I understand it's something with encoding, but where and how to fix this?

**Comment by digininja** [comment]
Apart from looking pretty, does it need fixing?

What level, what browser, what language?

**Comment by mike-bailey** [comment]
I forgot to answer this, sorry. What command are you using is also key so we can try to determine expected output.

**Comment by MrPhenomOne** [comment]
Level doesn't matter; browser is Firefox 58; English language in dvwa.

Command also was any: didn't matter if it's "127.0.0.1 & dir" or "127.0.0.1 | dir"

**Comment by mike-bailey** [comment]
Both of those commands result in plaintext ASCII for me. You're going to http://whateverurl/vulnerabilities/exec/#, doing `127.0.0.1 | dir` and getting invalid characters? Do any commands not result in an encoding error.

**Comment by MrPhenomOne** [comment]
There are mix of valid and invalid charatcters. Fpr example, names of files are valid, as well as "ping word" , but most of that are invalid.

Can I send you screenshot by email?

**Comment by mike-bailey** [comment]
You should be able to attach it here. However I’m going to have to drop off shortly as it’s 3am here.

**Comment by MrPhenomOne** [comment]
![2018-02-12](https://user-images.githubusercontent.com/17023836/36087793-10fc15d6-0fcc-11e8-8798-8dc7eebb1363.png)

**Comment by digininja** [comment]
It doesn't help you but, it works fine for me.

You are running it on a Windows box, is the web server definitely set to serve English encoding? My guess is that the encodings are out of sync somewhere and that is messing everything up. You could test it by creating a simple page containing just this script and see whether it messes up or not:

```php
<?php
$cmd = shell_exec( 'ping -c 4 127.0.0.1' ); 
echo "<pre>{$cmd}</pre>"; 
?>
```

If it does not mess up, then you need to look at the headers sent by DVWA and start adding them in, if it does mess up then it is your machine/web server/browser and you can look there for the problem.

**Comment by mike-bailey** [comment]
Really old but was the above attempted? After 7 days, closing.

**Comment by digininja** [comment]
Needs closing
