### ISSUE TITLE
set up page not working 

### ISSUE THREAD

**Issue by apu745** [ethicalhack3r/DVWA#220]
Database Setup

Click on the 'Create / Reset Database' button below to create or reset your database.
If you get an error make sure you have the correct user credentials in: " . realpath( getcwd() . DIRECTORY_SEPARATOR . "config" . DIRECTORY_SEPARATOR . "config.inc.php" ) . "

If the database already exists, it will be cleared and the data will be reset.
You can also use this to reset the administrator credentials (\"admin // password\") at any stage.

Setup Check
{$DVWAOS}
Backend database: {$DBMS}
PHP version: " . phpversion() . "

{$SERVER_NAME}

{$phpDisplayErrors}
{$phpSafeMode}
{$phpURLInclude}
{$phpURLFopen}
{$phpMagicQuotes}
{$phpGD}
{$phpMySQL}
{$phpPDO}

{$MYSQL_USER}
{$MYSQL_PASS}
{$MYSQL_DB}
{$MYSQL_SERVER}

{$DVWARecaptcha}

{$DVWAUploadsWrite}
{$DVWAPHPWrite}

{$bakWritable}
Status in red, indicate there will be an issue when trying to complete some modules.

If you see disabled on either allow_url_fopen or allow_url_include, set the following in your php.ini file and restart Apache.

allow_url_fopen = On
allow_url_include = On

These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

    \"Create                                     " . tokenField() . "

"; dvwaHtmlEcho( $page ); ?>

**Comment by digininja** [comment]
you haven't got php enabled on the server.

**Comment by mike-bailey** [comment]
Closing as that’s the clear issue. Feel free to open another otherwise.
