### ISSUE TITLE
line 65 of vulnerabilities/sqli_blind/index.php

### ISSUE THREAD

**Issue by kabads** [ethicalhack3r/DVWA#223]
was 
`num    = mysqli_fetch_row( $result ) [0] ;` 
but needs to be:
`num    = mysqli_fetch_row( $result [0])  ;`

If I knew git better, I'd submit a pull request. Perhaps, if I get time.

**Comment by digininja** [comment]
It looks correct as it is to me, the mysqli_fetch_row function returns an array  of results, the [0] then pulls off the first item from that array.

To show explicitly what is going on, this pulls out the rows first then gets the count from the first element:

```
 65         $rows    = mysqli_fetch_row( $result );
 66         var_dump ($rows);
 67         $num    = $rows[0];
 68         var_dump ($num);
```

This is what gets displayed:

```
array(1) {
  [0]=>
  string(1) "5"
}
string(1) "5"
```

**Comment by digininja** [comment]
If you look at $result, it is an object

```
var_dump ($result);
```

```
object(mysqli_result)#4 (5) {
  ["current_field"]=>
  int(0)
  ["field_count"]=>
  int(1)
  ["lengths"]=>
  NULL
  ["num_rows"]=>
  int(1)
  ["type"]=>
  int(0)
}
```

If you tried to pull element 0 from it with [0] you would get this error:

```
<br />
<b>Fatal error</b>:  Uncaught Error: Cannot use object of type mysqli_result as array in /var/sites/dvwa/non-secure/htdocs/vulnerabilities/sqli_blind/index.php:65
Stack trace:
#0 {main}
  thrown in <b>/var/sites/dvwa/non-secure/htdocs/vulnerabilities/sqli_blind/index.php</b> on line <b>65</b><br />
```

**Comment by Danovercast** [comment]
that's very kind of you !
