### ISSUE TITLE
Google recaptcha v1 discontinued at the end of March 2018

### ISSUE THREAD

**Issue by halfluke** [ethicalhack3r/DVWA#224]
I created a recaptcha version 2 in my Google account, added the code to DVWA config file, but when I go to the recaptcha challenge in dvwa, the warning mentioned [here](https://developers.google.com/recaptcha/docs/faq)
is displayed. 
Is this an issue with dvwa?

**Comment by digininja** [comment]
I doubt anyone has touched the recaptcha code for years so it probably does
need updating. Feel free to have a go and send in a pull request.

**Comment by halfluke** [comment]
Ehm, I'm afraid I do not have the skills, I'm just using dvwa for learning

**Comment by digininja** [comment]
Isn't moving from not having skill to having them the definition of
learning? Have a go and see what happens and you will learn things.

**Comment by Exhibitioner** [comment]
Have fixed the captcha, now using the latest Google Recaptcha v2. Also removed deprecated mysql_ usage, all converted to mysqli_ so DVWA should now be fully compatible with latest PHP version (7.2). 

Will commit this tomorrow

**Comment by digininja** [comment]
Don't know which branch you were working on but mysql_ has been gone for a
very long time now.

**Comment by Exhibitioner** [comment]
That's odd. When I downloaded it from here it was full of mysql_ calls. I'll just submit captcha fix then.

**Comment by digininja** [comment]
If you downloaded a release it might have been. Any changes should be done
against the latest master branch from GitHub.

**Comment by Exhibitioner** [comment]
Turns out it's the README "zip" stable download I used. It downloads a version from (2015?), should probably get that download updated too.

**Comment by digininja** [comment]
Looking at the releases, that was the last tagged release. I think we just
assume everyone uses the latest from the repo.

**Comment by Exhibitioner** [comment]
Have moved captcha functionality over to current master. Pull request is pending (#227).

**Comment by mike-bailey** [comment]
PR was merged.
