### ISSUE TITLE
php version-7,PHP module mysql: Missing,PHP module pdo_mysql: Missing

### ISSUE THREAD

**Issue by pulok19524** [ethicalhack3r/DVWA#226]
hey guys.I am totally new and trying to install DVWA in php-7.0.And i am using MariaDB instead of Mysql.I follow the instruction for MariaDB.But when i went to the Dvwa setup page i see this:

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 7.0.28-1

Web Server SERVER_NAME: localhost

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Missing
PHP module pdo_mysql: Missing

MySQL username: root
MySQL password: *blank*
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: 6LcH9EsUAAAAAKTYe6ini6UtK_2465pmDgE3johd

[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: Yes
[User: root] Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

[User: root] Writable folder /var/www/html/dvwa/config: Yes
Status in red, indicate there will be an issue when trying to complete some modules.

If you see disabled on either allow_url_fopen or allow_url_include, set the following in your php.ini file and restart Apache.

allow_url_fopen = On
allow_url_include = On

These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

so when i try to put this command:
apt-get -y install apache2 mysql-server php php-mysqli php-gd libapache2-mod-php

i get this:
Building dependency tree       
Reading state information... Done
Package php-mysqli is a virtual package provided by:
  php7.2-mysql 7.2.3-1
  php7.1-mysql 7.1.15-1
  php7.0-mysql 7.0.28-1
You should explicitly select one to install.

E: Package 'php-mysqli' has no installation candidate
what is wrong what can i do now.

**Comment by digininja** [comment]
If you are using PHP 7.0 then choose the 7.0 MySQL library to match it.

And read the warning about not using the root database user with mariadb.

**Comment by mike-bailey** [comment]
This is a system issue so closing
