### ISSUE TITLE
Issue Setting up DVWA on kali linux.

### ISSUE THREAD

**Issue by houndmf** [ethicalhack3r/DVWA#230]
**When install php7.0-gd I get an error.**
apt-get install php7.0-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libapache2-mod-php7.0 php7.0-cli php7.0-common php7.0-json php7.0-mysql
  php7.0-opcache php7.0-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php7.0-gd
The following packages will be upgraded:
  libapache2-mod-php7.0 php7.0-cli php7.0-common php7.0-json php7.0-mysql
  php7.0-opcache php7.0-readline
7 upgraded, 1 newly installed, 0 to remove and 1226 not upgraded.
Need to get 27.9 kB/3,662 kB of archives.
After this operation, 150 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://http.kali.org/kali kali-rolling/main amd64 php7.0-gd amd64 7.0.22-2
  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/php7.0/php7.0-gd_7.0.22-2_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
**So the first thing i notice thats wrong is my version of php is php7.0.16-3, confirmed here, dont know why its trying to install php7.0.22-2:**
php -v
PHP 7.0.16-3 (cli) (built: Feb 22 2017 10:03:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-3, Copyright (c) 1999-2017, by Zend Technologies
apt-get update and apt-get upgrade also gives errors, not sure where ive gone wrong as im a beginner just trying to practice. followed different tutorials, and done loads of research. to my knoledge ive got things set right just not sure where to go from here.

**Comment by digininja** [comment]
Sounds like you need to do an update but can't. This is a Kali issue not
DVWA, talk to their support then come back to us once you have a working
distro.

**Comment by houndmf** [comment]
Have opted for a complete re-install of Kali as seems much easier and I have nothing of importance on there. going for the latest build or would you recommend an earlier one?

**Comment by digininja** [comment]
Latest should work

**Comment by CryptSkitty** [comment]
@houndmf 
Kali Devs tend to avoid breaking tools via their dependencies. When they fork/merge from debian testing to kali-dev, they may have tinkered with apt's preference values:

https://wiki.debian.org/AptPreferences

Never hurts to check.

**Comment by mike-bailey** [comment]
>This is a Kali issue not DVWA, talk to their support then come back to us once you have a working
distro.

I should note I'm not locking discussion, just closing this as a DVWA issue.

**Comment by houndmf** [comment]
sudo apt-get install 7.0-gd gives me this error:
Couldnt find any packages by glob 'php7.0-gd 
Couldnt find any packages br regex 'php7.0-gd 
and when I update: apt-get install update reading package lists...done
 Thats it. Not sure whats gone wrong, I have reinstalled my version of kali with no issues as well.

**Comment by houndmf** [comment]
This is where im at:
Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 7.0.16-3

Web Server SERVER_NAME: localhost

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Missing
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: ******
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: 6Lf_EVAUAAAAAMlLF2IqUmx4-HSpIFZ40JvS8eZc

[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: Yes
[User: root] Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes


[User: root] Writable folder /var/www/html/dvwa/config: Yes
Status in red, indicate there will be an issue when trying to complete some modules.

If you see disabled on either allow_url_fopen or allow_url_include, set the following in your php.ini file and restart Apache.

allow_url_fopen = On
allow_url_include = On

These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

**Comment by mike-bailey** [comment]
What happens if you do `php-gd`

**Comment by houndmf** [comment]
root@kali:~# php-gd
bash: php-gd: command not found
root@kali:~# apt-get install php-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php-gd

**Comment by houndmf** [comment]
It keeps telling me no matter what variation of the command i put in that it cant find it. Im wondering if theres an issue with my repository?
This gives an error as well:
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install php7.0-gd

**Comment by houndmf** [comment]
add-apt-repository ppa:ondrej/php
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Kali/kali-rolling
