### ISSUE TITLE
Cant install php7.0-gd?? For DVWA setup

### ISSUE THREAD

**Issue by houndmf** [ethicalhack3r/DVWA#231]
Back again. I have gotten as far as needing to install php7.0-gd but when I do get an error saying : 
Couldnt find any package by glob 'php7.0-gd
Couldnt find any package by regex 'php7.0-gd

Im new to this and just trying to set up DVWA so i can practice and learn. Not sure where im going wrong??
any help would be appreciated.
cheers

**Comment by mike-bailey** [comment]
You can keep commenting on the last issue. Please don't open a new one 😄 It's closed because it's not a DVWA issue so we don't want it on our list as such, not because nobody can help you and we don't want you discussing it. #230
