### ISSUE TITLE
Blank Login page After  clicking Create/Reset Data base

### ISSUE THREAD

**Issue by jokkr** [ethicalhack3r/DVWA#232]
hi, I set up dvwa as per instructions and everything was working.....
but when i click the **Create/Reset Data base** it just leave me to a blank page  with address "localhost/dvwa/setup.php#"

THIS IS THE SETUP PAGE

**Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 7.0.27-0+deb9u1

Web Server SERVER_NAME: localhost

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Installed

reCAPTCHA key: 6Ldp0FAUAAAAAFZ3pv7u_QS-73yHQGUJ3Kp-25Xv

Writable folder /var/www/html/dvwa/hackable/uploads/: Yes)
Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

Status in red, indicate there will be an issue when trying to complete some modules**

Please Help Me...

Thanks in advance....

**Comment by mike-bailey** [comment]
What do logs say? Should be in /var/log/apache2/error.log

**Comment by jokkr** [comment]
/var/log/apache2/error.log

[Tue Apr 03 20:40:11.991419 2018] [mpm_event:notice] [pid 3859:tid 3074643712] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Tue Apr 03 20:40:11.992035 2018] [core:notice] [pid 3859:tid 3074643712] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 03 21:23:42.622872 2018] [mpm_event:notice] [pid 3859:tid 3074643712] AH00491: caught SIGTERM, shutting down
[Tue Apr 03 21:24:53.721721 2018] [mpm_event:notice] [pid 460:tid 3075020544] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Tue Apr 03 21:24:53.839105 2018] [core:notice] [pid 460:tid 3075020544] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 03 21:32:04.411120 2018] [mpm_event:notice] [pid 460:tid 3075020544] AH00491: caught SIGTERM, shutting down
[Tue Apr 03 21:48:39.321522 2018] [mpm_event:notice] [pid 495:tid 3074471680] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Tue Apr 03 21:48:39.484873 2018] [core:notice] [pid 495:tid 3074471680] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 03 22:10:34.765141 2018] [mpm_event:notice] [pid 495:tid 3074471680] AH00491: caught SIGTERM, shutting down
[Tue Apr 03 22:11:54.340931 2018] [mpm_event:notice] [pid 423:tid 3074262784] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Tue Apr 03 22:11:54.388000 2018] [core:notice] [pid 423:tid 3074262784] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 03 22:22:48.671687 2018] [mpm_event:notice] [pid 423:tid 3074262784] AH00491: caught SIGTERM, shutting down
[Tue Apr 03 22:24:36.157089 2018] [mpm_event:notice] [pid 420:tid 3074549504] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Tue Apr 03 22:24:36.190949 2018] [core:notice] [pid 420:tid 3074549504] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 07:33:15.225455 2018] [mpm_event:notice] [pid 470:tid 3074942720] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 07:33:15.251650 2018] [core:notice] [pid 470:tid 3074942720] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 07:45:46.000192 2018] [mpm_event:notice] [pid 416:tid 3074733824] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 07:45:46.035388 2018] [core:notice] [pid 416:tid 3074733824] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:05:45.599628 2018] [mpm_event:notice] [pid 416:tid 3074733824] AH00491: caught SIGTERM, shutting down
[Wed Apr 04 09:05:46.039907 2018] [mpm_event:notice] [pid 4677:tid 3074647808] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 09:05:46.048476 2018] [core:notice] [pid 4677:tid 3074647808] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:11:44.223938 2018] [mpm_event:notice] [pid 4677:tid 3074647808] AH00491: caught SIGTERM, shutting down
[Wed Apr 04 09:11:53.033004 2018] [mpm_event:notice] [pid 4792:tid 3074574080] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 09:11:53.034832 2018] [core:notice] [pid 4792:tid 3074574080] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:19:13.046621 2018] [mpm_event:notice] [pid 4792:tid 3074574080] AH00491: caught SIGTERM, shutting down
[Wed Apr 04 09:20:22.264249 2018] [mpm_event:notice] [pid 5581:tid 3074717440] AH00489: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 09:20:22.294801 2018] [core:notice] [pid 5581:tid 3074717440] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:45:31.290436 2018] [mpm_event:notice] [pid 5581:tid 3074717440] AH00491: caught SIGTERM, shutting down
[Wed Apr 04 09:45:31.786018 2018] [mpm_prefork:notice] [pid 12393] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 09:45:31.787907 2018] [core:notice] [pid 12393] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:45:35.692364 2018] [mpm_prefork:notice] [pid 12393] AH00169: caught SIGTERM, shutting down
[Wed Apr 04 09:45:37.400237 2018] [mpm_prefork:notice] [pid 12448] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 09:45:37.414576 2018] [core:notice] [pid 12448] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:46:56.640458 2018] [:error] [pid 12450] [client ::1:42600] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 09:47:06.836456 2018] [:error] [pid 12452] [client ::1:42604] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 09:47:38.915268 2018] [:error] [pid 12453] [client ::1:42606] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 09:47:53.560121 2018] [:error] [pid 12454] [client ::1:42608] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Apr 04 09:49:10.890807 2018] [mpm_prefork:notice] [pid 12448] AH00169: caught SIGTERM, shutting down
[Wed Apr 04 09:49:13.977446 2018] [mpm_prefork:notice] [pid 12526] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 09:49:13.979144 2018] [core:notice] [pid 12526] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:49:22.576055 2018] [:error] [pid 12527] [client ::1:42610] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 09:53:01.790417 2018] [:error] [pid 12533] [client ::1:42626] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 09:55:52.123229 2018] [mpm_prefork:notice] [pid 12526] AH00169: caught SIGTERM, shutting down
[Wed Apr 04 09:55:53.100129 2018] [mpm_prefork:notice] [pid 12706] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 09:55:53.112542 2018] [core:notice] [pid 12706] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:56:08.893321 2018] [:error] [pid 12707] [client ::1:42634] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 09:56:26.112102 2018] [:error] [pid 12850] [client ::1:42646] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Apr 04 09:58:19.603268 2018] [mpm_prefork:notice] [pid 12706] AH00169: caught SIGTERM, shutting down
[Wed Apr 04 09:58:20.767790 2018] [mpm_prefork:notice] [pid 13015] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 09:58:20.772133 2018] [core:notice] [pid 13015] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 09:59:09.932447 2018] [:error] [pid 13017] [client ::1:42656] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 09:59:47.128334 2018] [:error] [pid 13017] [client ::1:42672] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 10:00:03.442897 2018] [:error] [pid 13019] [client ::1:42676] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Apr 04 10:01:35.872084 2018] [:error] [pid 13020] [client ::1:42678] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Apr 04 10:43:09.831425 2018] [mpm_prefork:notice] [pid 464] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 10:43:09.850199 2018] [core:notice] [pid 464] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 10:45:46.717933 2018] [:error] [pid 566] [client ::1:44908] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 10:47:49.324014 2018] [:error] [pid 1138] [client ::1:44918] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 10:57:36.784026 2018] [:error] [pid 566] [client ::1:45912] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 11:09:12.243130 2018] [mpm_prefork:notice] [pid 464] AH00169: caught SIGTERM, shutting down
[Wed Apr 04 11:09:13.013486 2018] [mpm_prefork:notice] [pid 1536] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 11:09:13.014425 2018] [core:notice] [pid 1536] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 11:12:40.474332 2018] [mpm_prefork:notice] [pid 1536] AH00169: caught SIGTERM, shutting down
[Wed Apr 04 11:12:42.151758 2018] [mpm_prefork:notice] [pid 1568] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 11:12:42.157810 2018] [core:notice] [pid 1568] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 11:13:04.231589 2018] [mpm_prefork:notice] [pid 1568] AH00169: caught SIGTERM, shutting down
[Wed Apr 04 11:14:57.576301 2018] [mpm_prefork:notice] [pid 451] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 11:14:57.593634 2018] [core:notice] [pid 451] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 11:16:32.659524 2018] [mpm_prefork:notice] [pid 451] AH00169: caught SIGTERM, shutting down
[Wed Apr 04 11:16:33.373715 2018] [mpm_prefork:notice] [pid 994] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 11:16:33.377617 2018] [core:notice] [pid 994] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 04 11:18:32.108205 2018] [:error] [pid 998] [client 192.168.42.241:41490] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.42.189/dvwa/setup.php
[Wed Apr 04 11:26:49.643961 2018] [:error] [pid 995] [client 192.168.42.80:40388] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.42.189/dvwa/setup.php
[Wed Apr 04 11:31:06.786131 2018] [:error] [pid 996] [client 192.168.42.80:40398] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Apr 04 11:31:10.708649 2018] [:error] [pid 1092] [client 192.168.42.80:40404] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Apr 04 11:31:11.883333 2018] [:error] [pid 1093] [client 192.168.42.80:40406] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Apr 04 11:31:12.709616 2018] [:error] [pid 1094] [client 192.168.42.80:40408] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:461\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 461
[Wed Apr 04 11:33:42.222492 2018] [:error] [pid 998] [client ::1:34630] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 11:35:04.904900 2018] [:error] [pid 995] [client ::1:34638] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Wed Apr 04 12:13:50.849646 2018] [mpm_prefork:notice] [pid 488] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Apr 04 12:13:50.886193 2018] [core:notice] [pid 488] AH00094: Command line: '/usr/sbin/apache2'

**Comment by mike-bailey** [comment]
How did you download DVWA?

**Comment by jokkr** [comment]
I downloaded from this link 'https://github.com/RandomStorm/DVWA/archive/v1.9.zip '

which is from the guide i used to setup dvwa

**Comment by mike-bailey** [comment]
It’s failing on a function that doesn’t exist anymore in our code https://github.com/ethicalhack3r/DVWA/search?utf8=%E2%9C%93&q=mysql_connect&type=

**Comment by mike-bailey** [comment]
Try https://github.com/ethicalhack3r/DVWA/archive/master.zip

**Comment by jokkr** [comment]
so what can I do to Fix It
?
:(

**Comment by jokkr** [comment]
okay

**Comment by digininja** [comment]
What does the Apache error log say?

If you don't know what that is, or where it is, read the closed issues, it
has been discussed many times.

**Comment by mike-bailey** [comment]
@digininja scroll up

**Comment by mike-bailey** [comment]
Basically error logs indicate use of mysql_connect which doesn’t exist here. It’s in an old build. There’s a bad build out there jokkr got, and has since been resolved. Closing as not an issue with the present build.

**Comment by digininja** [comment]
Oops, I only got the initial email so replied to that.

**Comment by jokkr** [comment]
Thanks Mike for Helping me out...

I Got some other issues But I managed to troubleshoot 'em my self..

Thanks for helping me :+1:
