### ISSUE TITLE
reCAPTCHA v2 upgrade

### ISSUE THREAD

**Issue by jeremy923** [ethicalhack3r/DVWA#234]
Hi guys

Now that reCAPTCHA v1 has been suspended (https://developers.google.com/recaptcha/docs/faq#what-happens-to-recaptcha-v1), I just wonder if corresponding upgrade of DVWA is planned?

Cheers

**Comment by digininja** [comment]
It has already been done, see
https://github.com/ethicalhack3r/DVWA/issues/224

**Comment by adibikar** [comment]
I was do new git clone again and it already fix for captcha v2.
It was done here [Captcha fix](https://github.com/ethicalhack3r/DVWA/commit/3cef5cafa71ca7724c9231ce6aed7e853f4ce787)

**Comment by jeremy923** [comment]
Thanks :)
