### ISSUE TITLE
DVWA login screen blank

### ISSUE THREAD

**Issue by Victini517** [ethicalhack3r/DVWA#237]
When i complete the dvwa setup everything is enabled and when i go to the login site there is nothing
I'll link the apache error log
https://pastebin.com/6mzkM751

**Comment by mike-bailey** [comment]
Do you mind posting the config.inc.php how you did the log by any chance?

**Comment by digininja** [comment]
Looks like you've messed up your config file, check that to start with.

**Comment by Victini517** [comment]
https://pastebin.com/H055cNip here

**Comment by mike-bailey** [comment]
DVWA requires you set up a MySQL database, you can’t just null it out I’m afraid.

**Comment by Victini517** [comment]
the null is name of the database and the user

**Comment by mike-bailey** [comment]
In that case maybe remove the extra backticks

**Comment by digininja** [comment]
That looks like the problem to me. I'd guess copy/paste mistake from the
SQL create statement.

**Comment by Victini517** [comment]
I got it working by just doing it again

**Comment by digininja** [comment]
Well done. Don't forget to close the issue.
