### ISSUE TITLE
Blank page when trying to load 127.0.0.1/dvwa/

### ISSUE THREAD

**Issue by ren0784** [ethicalhack3r/DVWA#239]
Hello this is my first time trying to load dvwa using kali linux. I am also a noob when it comes to kali!
I have followed all the instructions and how to's for dvwa, however, when I try to load it the page does not appear. 
I get this error from the Apache error logs:

Thu Apr 26 19:13:06.704556 2018] [:error] [pid 1275] [client 127.0.0.1:37374] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:467\nStack trace:\n#0 /var/www/html/dvwa/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php on line 467 

Here is line 467 from /var/www/html/dvwa/dvwa/includes/dvwaPage.inc.php:

if( $DBMS == 'MySQL' ) {
		if( !@($GLOBALS["___mysqli_ston"] = mysqli_connect( $_DVWA[ 'db_server' ],  $_DVWA[ 'db_user' ],  $_DVWA[ 'db_password' ] ))

Also,
allow_url_fopen on
allow_url_include on

Any help would be greatly appreciated, hopefully this is just a noob mistake!!! Thank you!

**Comment by mike-bailey** [comment]
The MySQL library isn't installed. Something like `apt install php-mysql`.

**Comment by mike-bailey** [comment]
Any updates? This issue will be closed in 7 days otherwise.

**Comment by mike-bailey** [comment]
Honestly this is pretty straightforward so I’m closing.
