### ISSUE TITLE
DVWA Security hole

### ISSUE THREAD

**Issue by w2n1ck** [ethicalhack3r/DVWA#244]
In DVWA through 1.9, after the installation is complete, setup.php is not locked and is not deleted. The attacker can directly access the page and reset the database to directly obtain the login account password, and then enter the console to obtain server privileges.

Direct access to setup.php e.g:/setup.php

For example, add an account directly through the command execution loophole and upload the vulnerability via getshell.

for example
http://123.206.7.138/login.php
Unable to log in using the default admin/password, visit setup.php to reset the database, and log in with the default admin/password

**Comment by mike-bailey** [comment]
Cool! Closing because this app is supposed to have security holes.

**Comment by mike-bailey** [comment]
In addition, please be careful about exposing it to the internet. Spiders have scanned for DVWA before to use as pivots.

**Comment by w2n1ck** [comment]
Oh yet， I use search engines to find many applications on the public network that can directly attack
![image](https://user-images.githubusercontent.com/26704158/40401065-5e49bcae-5e77-11e8-94eb-7fe4a4664ea9.png)

**Comment by digininja** [comment]
Really not a good idea to leave DVWA exposed to the internet, even if you change the password of the admin user. Don't forget there are 4 other users and, as you pointed out, the database can be reset at any time by anyone.

**Comment by ahmetkotan** [comment]
Only you and me are clever in this world, all of these idle. Cheers!

**Comment by DoctorHackerAbertay** [comment]
So a deliberately vulnerable web app is vulnerable. Not a "security hole" in my book!

**Comment by WebBreacher** [comment]
Would it be a security issue or an anti-security issue if DVWA was NOT vulnerable?

**Comment by mike-bailey** [comment]
I’m gonna lock this just because it isn’t the first time this has happened in this tracker lol
