### ISSUE TITLE
Could not connect to the MySQL service. Please check the config file.

### ISSUE THREAD

**Issue by Asif02** [ethicalhack3r/DVWA#249]
Could not connect to the MySQL service.
Please check the config file Problem[
![screenshot from 2018-07-05 12-48-20](https://user-images.githubusercontent.com/35127826/42336476-caed578e-8051-11e8-9ab0-d9864acf0836.png)
](url)

**Comment by mike-bailey** [comment]
Did you edit and move the config file? The config.inc.php?

**Comment by mike-bailey** [comment]
Please note after 7 days this will be marked as inactive and closed
