### ISSUE TITLE
sql or xss is not working

### ISSUE THREAD

**Issue by SamehAtefSaad** [ethicalhack3r/DVWA#250]
I have installed DVWA on Win 7 . When I run SQL command, it doesn't show anything. when I run XSS, it doesn't run the script but shows it in text like below :
![image](https://user-images.githubusercontent.com/28782149/42753003-41d7d776-88f8-11e8-8e75-ca9ff85fb492.png)

**Comment by digininja** [comment]
Learn how the security levels works and try again.

**Comment by mqliutie** [comment]
@SamehAtefSaad Help me. I have the same problem...

**Comment by digininja** [comment]
Will give you the same comment, learn how the security levels work.

**Comment by mqliutie** [comment]
@digininja En, I am not good at PHP , but I found some message. It works. Thanks

**Comment by digininja** [comment]
It is nothing to do with PHP, it is all to do with using a web application.
If you are planning to try to hack one, then we have to assume you know how
to use one first.

**Comment by mqliutie** [comment]
When I first attempted to `alert` some message the `cookie.security` was **impossible**.
After I changed the value It works.
Because I found the message was in `index.php` 
```
switch( $_COOKIE[ 'security' ] ) 
```

**Comment by digininja** [comment]
Browse the application, there is a much easier way to set the levels
