### ISSUE TITLE
BLANK LOGIN PAGE IN KALI LINUX WITH PHP V 7.2 after doing complete setup

### ISSUE THREAD

**Issue by rroy1045** [ethicalhack3r/DVWA#251]
I have tried it two times, 1 in physical machine and 2nd time in virtual machine..In physical Machine i got blank page a complete white page and in virtual machine I got some other page apart from my login page...i ahve attached a screenshot of it..I have also uploaded the complete process that i have followed below in a text file...please HELP..

[How_To_Install_DVWA_In_Kali_Linux_2018.1.txt](https://github.com/ethicalhack3r/DVWA/files/2216466/How_To_Install_DVWA_In_Kali_Linux_2018.1.txt)
![screenshot-virtual machine](https://user-images.githubusercontent.com/34626301/43039789-95a3c82a-8d02-11e8-9b23-d48d5b278486.png)

**Comment by digininja** [comment]
My guess would be that you don't have PHP installed it enabled

**Comment by mike-bailey** [comment]
Do you have your logs? Should be around /var/log/apache2:(error/access).log

**Comment by rroy1045** [comment]
Well i have manually installed php,mysql and all...For further reverification i even installed XAMPP as stated in the docs file...But still now nothing's working..N yes the log files i am placing them below. I couldnt understand the possible error in them

The content of apache2 access log files are:-
::1 - - [23/Jul/2018:07:13:07 -0400] "GET /DVWA HTTP/1.1" 301 564 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:13:08 -0400] "GET /DVWA/ HTTP/1.1" 200 4657 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:13:08 -0400] "GET /favicon.ico HTTP/1.1" 404 500 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [23/Jul/2018:07:28:04 -0400] "GET / HTTP/1.1" 200 3380 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [23/Jul/2018:07:28:04 -0400] "GET /icons/openlogo-75.png HTTP/1.1" 200 6040 "http://trikster/" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
127.0.0.1 - - [23/Jul/2018:07:28:05 -0400] "GET /favicon.ico HTTP/1.1" 404 499 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:28:22 -0400] "GET /DVWA/ HTTP/1.1" 304 182 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:28:27 -0400] "GET / HTTP/1.1" 200 3379 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:28:27 -0400] "GET /icons/openlogo-75.png HTTP/1.1" 200 6040 "http://localhost/" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:30:47 -0400] "GET /DVWA/ HTTP/1.1" 304 182 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:30:50 -0400] "GET / HTTP/1.1" 200 3379 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:30:50 -0400] "GET /icons/openlogo-75.png HTTP/1.1" 304 181 "http://localhost/" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:30:52 -0400] "GET / HTTP/1.1" 200 3379 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:30:52 -0400] "GET /icons/openlogo-75.png HTTP/1.1" 304 181 "http://localhost/" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:30:55 -0400] "GET /DVWA/ HTTP/1.1" 304 181 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:36:16 -0400] "GET /DVWA/ HTTP/1.1" 304 182 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:36:18 -0400] "GET /DVWA/ HTTP/1.1" 304 181 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [23/Jul/2018:07:36:21 -0400] "GET /DVWA/ HTTP/1.1" 304 181 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"


The content of apache2 error log files are:-

[Mon Jul 23 07:12:24.745986 2018] [mpm_event:notice] [pid 2495:tid 140571228365888] AH00489: Apache/2.4.33 (Debian) configured -- resuming normal operations
[Mon Jul 23 07:12:24.746341 2018] [core:notice] [pid 2495:tid 140571228365888] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jul 23 07:37:44.254137 2018] [mpm_event:notice] [pid 2495:tid 140571228365888] AH00491: caught SIGTERM, shutting down
[Mon Jul 23 07:37:44.557887 2018] [mpm_event:notice] [pid 8995:tid 139720676353088] AH00489: Apache/2.4.33 (Debian) configured -- resuming normal operations
[Mon Jul 23 07:37:44.558004 2018] [core:notice] [pid 8995:tid 139720676353088] AH00094: Command line: '/usr/sbin/apache2'

**Comment by digininja** [comment]
No obvious errors. Do some googling and work out how to create a phpinfo
script and see if that works.

**Comment by rroy1045** [comment]
Well the problem is sorted out now..What i did was i purged all previously installed versions of apache2, mysql and php, and after that selectively reinstalled only those modules  that was required....
After that i reinstalled DVWA and after completing the setup just opened localhost/DVWA/setup.php and thats it! It worked..
I am closing the issue now. Well thanks both of you for your support..
