### ISSUE TITLE
why window.location?

### ISSUE THREAD

**Issue by digininja** [ethicalhack3r/DVWA#256]
@ethicalhack3r Any idea why you did the navigation in left hand pane like this?

```
<li onclick="window.location='../../vulnerabilities/xss_d/'" class=""><a href="../../vulnerabilities/xss_d/">XSS (DOM)</a></li>
<li onclick="window.location='../../vulnerabilities/xss_r/'" class=""><a href="../../vulnerabilities/xss_r/">XSS (Reflected)</a></li>
<li onclick="window.location='../../vulnerabilities/xss_s/'" class=""><a href="../../vulnerabilities/xss_s/">XSS (Stored)</a></li>
```
I can't see why you went for window.location instead of just relying on the anchor tag. It is broken by my CSP high and impossible levels so would like to remove it as I don't think it is adding anything but wanted to check first.

**Comment by dewhurstsecurity** [comment]
no reason that I can remember

**Comment by digininja** [comment]
I've removed them and everything seems to still be working so I've updated the PR that is already in there.
