### ISSUE TITLE
issue while setting up MySql database

### ISSUE THREAD

**Issue by mritunjay7497** [ethicalhack3r/DVWA#258]
hi,
i'm all set for DVWA but the only thing stopping it from initialisationis the dabase issue.
Ive tried various methods like reconfiguring mysql,changing credentials but of no help.
All the modules are installed and everything works just fine except setting up the database.
I even went through your old issues but in vain Please help me
![screenshot from 2018-08-30 00 52 06](https://user-images.githubusercontent.com/24255924/44810295-fd988f00-abee-11e8-8dbb-ee98841065a9.png)
![screenshot from 2018-08-30 00 51 58](https://user-images.githubusercontent.com/24255924/44810296-fd988f00-abee-11e8-9c08-bd990207744e.png)

**Comment by digininja** [comment]
Based on the top screenshot you don't know your own database password so we can't help you that much. Set up MySQL so you can log in and then setup the config file with the correct credentials, not those of root.

If you get stuck getting into MySQL, ask on their forums.

**Comment by mritunjay7497** [comment]
i know the database password, i've set  it to "toor"

**Comment by digininja** [comment]
so why does the screenshot show you failing to log in with it?

**Comment by mritunjay7497** [comment]
![screenshot from 2018-08-30 01 00 00](https://user-images.githubusercontent.com/24255924/44810693-15bcde00-abf0-11e8-964f-d4fafa57bba2.png)

**Comment by mritunjay7497** [comment]
Don't know :(
that's where i'm stuck

**Comment by digininja** [comment]
That is the password you put in the DVWA config file which is what DVWA
will try to use to log into MySQL but from your first screenshot, toor is
not the root password.

Talk to the MySQL team about getting your database configured correctly
then come back.

**Comment by mritunjay7497** [comment]
okay, let me try that
anyways, thanks :)
