### ISSUE TITLE
Impossible model is not impossible!

### ISSUE THREAD

**Issue by hnytgl** [ethicalhack3r/DVWA#259]
Impossible model in XSS is not impossible,I found a bug in it, and could be 
the reason is that  this function "function dvwaSecurityLevelGet()" in "includes/dvwaPage.inc.php"，Get values directly from  "$_COOKIE[ 'security' ]" ，do not handle it.

**Comment by digininja** [comment]
That isn't a vulnerability in the exercise it is a generic vulnerability in
the app as a whole.

**Comment by mike-bailey** [comment]
This is by design.
