### ISSUE TITLE
Could not connect to the MySQL service

### ISSUE THREAD

**Issue by Jihadist** [ethicalhack3r/DVWA#260]
Apache error log from Ubuntu 18.04 on vmware

> [Sun Sep 16 18:33:50.719037 2018] [mpm_prefork:notice] [pid 27051] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
> [Sun Sep 16 18:33:50.719102 2018] [core:notice] [pid 27051] AH00094: Command line: '/usr/sbin/apache2'
> [Sun Sep 16 18:34:42.612533 2018] [php7:notice] [pid 27056] [client 192.168.1.55:56731] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.229.10/dvwa/setup.php

Pass for mysql is blank
But smth like 

> mysql -uroot -p

 works only with sudo
I  tried to create db manually as in instructions but it doesnt work all the same.
What's going wrong?

**Comment by digininja** [comment]
Please read all the other threads where this has been asked and try all the
offered solutions. If things still don't work, provide all the information
we have requested off the other people.
