### ISSUE TITLE
Could not connect or create or reset Database

### ISSUE THREAD

**Issue by manoelitonunes** [ethicalhack3r/DVWA#262]
Hi team, I have completed the whole tutorial and I am using Ubuntu 16.04 and connect on Kali through ssh. After the whole setup which seems to be fine, I could not create the database. Could anyone please help me to fix this issue.

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 5.6.37-1+ubuntu16.04.1+deb.sury.org+1

Web Server SERVER_NAME: 192.168.91.135

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: ******
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: 6LdQGHEUAAAAAGrPYQofJZF0Kss5Fiq5y8IP3JVC

[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: Yes
[User: root] Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

[User: root] Writable folder /var/www/html/dvwa/config: Yes
Status in red, indicate there will be an issue when trying to complete some modules.

If you see disabled on either allow_url_fopen or allow_url_include, set the following in your php.ini file and restart Apache.

allow_url_fopen = On
allow_url_include = On

These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

Could not connect to the MySQL service.
Please check the config file.
Your database user is root, if you are using MariaDB, this will not work, please read the README.md file.

**Comment by digininja** [comment]
Please read the many other instances of this question, go through all the
suggested fixes and, if it still doesn't work, come back with all the
information we request in those other tickets.

**Comment by manoelitonunes** [comment]
Hi buddy, thanks for your prompt response, I have been trying everything. please find attached the screenshot. Hope you can help me to get this working.
![capture](https://user-images.githubusercontent.com/6164908/45772248-06eda800-bc3f-11e8-8a3d-8edbe7e4a564.JPG)

**Comment by ethicalhack3r** [comment]
The SQL error in your screenshot says `Can't create database 'dvwa'; database exists`

Are you sure the correct database username and password are configured in the DVWA config file?

**Comment by manoelitonunes** [comment]
Thanks for replying, please find attached the screenshot of the config file. 
![image](https://user-images.githubusercontent.com/6164908/45774004-c8a6b780-bc43-11e8-9523-19b9b17805aa.png)

**Comment by ethicalhack3r** [comment]
> Are you sure the correct database username and password are configured in the DVWA config file?

**Comment by manoelitonunes** [comment]
Please find attached the screenshot of the config file above, I believe this is correct, thanks

**Comment by manoelitonunes** [comment]
mysql> grant all on dvwa.* to dvwa@localhost identified by 'xxx';
Query OK, 0 rows affected, 1 warning (0.01 sec)


 this command is not working

**Comment by ethicalhack3r** [comment]
> Query OK, 0 rows affected, **1 warning** (0.01 sec)

It gave you a warning what was the warning?

1. Are you sure you have the correct database password configured in the config file? 100% sure?

2. You are able to authenticate with the mysql client with the `dvwa` user and the password of `p@ssw0rd`?

3. Was mysql running when you clicked the `Create / Reset Database` button in the first screenshot?

**Comment by manoelitonunes** [comment]
![image](https://user-images.githubusercontent.com/6164908/45775480-ce060100-bc47-11e8-827f-586386185c9b.png)

Please see the screenshot I clicked to create the database again and the error at the bottom has changed.

The error warning is:
mysql> grant all on dvwa.*@localhost identified by '19ubuntu31@';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@localhost identified by '19ubuntu31@'' at line 1
mysql> 

1 - yes
2- I'm authenticating the sql with the password : 19ubuntu31@
3- not so sure

Many thanks for your help.

**Comment by digininja** [comment]
grant all on dvwa.* to dvwa@localhost identified by "XX"; flush privileges;

Then put the dvwa user into the config file

**Comment by manoelitonunes** [comment]
Sorry my stupidity but can I confirm "XX" needs to be replaced with my password set on config file ?

**Comment by digininja** [comment]
Either that or the password in the config file needs replacing with XX

**Comment by manoelitonunes** [comment]
I still trying to get it right and now I am facing this error on the screenshot below.
![capture1](https://user-images.githubusercontent.com/6164908/45838565-e8a0ae80-bd09-11e8-9494-958af15cd901.JPG)

**Comment by manoelitonunes** [comment]
Just an update, I changed the password and the command is working as seen on the screenshot below, but when I click on create/reset database could not connect to the mysql service.
Any idea what seems to be the error?
![capture2](https://user-images.githubusercontent.com/6164908/45839705-04598400-bd0d-11e8-9652-a6337255e230.JPG)

**Comment by manoelitonunes** [comment]
I read many others posts in here but the problem is because I don't know what seems to be the problem with the database. I wanted this to work so much. Anyway thanks for your help.

**Comment by mike-bailey** [comment]
@manoelitonunes Did you update the config with the new password by any chance? The `19Ubuntu31@`.

**Comment by manoelitonunes** [comment]
Hi Mike, please see below,

Last login: Thu Sep 20 11:10:07 2018 from 192.168.91.139
root@ubuntu:~# tail /var/log/apache2/error.log
[Thu Sep 20 11:36:19.824934 2018] [:error] [pid 44422] [client 192.168.91.139:37710] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.91.135/dvwa/setup.php
[Thu Sep 20 11:36:23.905940 2018] [:error] [pid 44422] [client 192.168.91.139:37710] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.91.135/dvwa/setup.php
[Thu Sep 20 11:37:38.436262 2018] [:error] [pid 44425] [client 192.168.91.139:37780] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.91.135/dvwa/setup.php
[Thu Sep 20 11:41:01.932064 2018] [mpm_prefork:notice] [pid 44419] AH00169: caught SIGTERM, shutting down
[Thu Sep 20 11:41:02.978865 2018] [mpm_prefork:notice] [pid 44550] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Sep 20 11:41:02.978954 2018] [core:notice] [pid 44550] AH00094: Command line: '/usr/sbin/apache2'
[Thu Sep 20 11:41:09.018568 2018] [:error] [pid 44555] [client 192.168.91.139:37954] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.91.135/dvwa/setup.php
[Thu Sep 20 11:41:11.715605 2018] [:error] [pid 44555] [client 192.168.91.139:37954] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.91.135/dvwa/setup.php
[Thu Sep 20 16:28:06.607598 2018] [:error] [pid 44553] [client 192.168.91.139:50450] PHP Notice:  Undefined index: session_token in /var/www/html/dvwa/setup.php on line 14, referer: http://192.168.91.135/dvwa/setup.php
[Thu Sep 20 16:28:11.351209 2018] [:error] [pid 44553] [client 192.168.91.139:50450] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://192.168.91.135/dvwa/setup.php

thanks for your help

**Comment by mike-bailey** [comment]
I only see notices, no errors, are you sure this is directly after pressing the button?

**Comment by manoelitonunes** [comment]
yes I'm sure, that's why I don't know what seems to be the problem

**Comment by manoelitonunes** [comment]
![capture3](https://user-images.githubusercontent.com/6164908/45852252-b6f20c80-bd36-11e8-9c79-6dfb413ac2fa.JPG)

**Comment by manoelitonunes** [comment]
![capture3](https://user-images.githubusercontent.com/6164908/45852292-e9036e80-bd36-11e8-9da3-98f9374ef8df.JPG)

**Comment by mike-bailey** [comment]
`Your database user is root`

In the screenshot it's dvwa, so hence my follow up question:
Do you mind please posting your config?

**Comment by manoelitonunes** [comment]
Hey Mike please see the config screenshot. Thanks
![config](https://user-images.githubusercontent.com/6164908/45872093-04966580-bd87-11e8-9e12-27997520bae9.JPG)

**Comment by digininja** [comment]
Look at the line that says db_user, it says root, you created the dvwa user with that password, set that as the user.

**Comment by digininja** [comment]
different browser, incognito window, try again

**Comment by manoelitonunes** [comment]
Hi guys I just want to say thank you very much for all ur help, See on the last screenshot I posted I changed the dvwa to root and now is working. I really appreciate all the help and patience with me.

**Comment by digininja** [comment]
All that is documented in other tickets. How to check the user, the
connections, create the user and the rest of it.

**Comment by AdarshKvT** [comment]
For me below configuration worked. Its for LAMPP:
-Create a new database "dvwa" from localhost/dashboard inside phpmyAdmin.
-And then leave the DWVA config.inc.php db_password field empty. (ex. '').
-restart the apache as well as mysql from xampp
