### ISSUE TITLE
Create Initial Database via CLI

### ISSUE THREAD

**Issue by jamesholland-uk** [ethicalhack3r/DVWA#266]
I'd like to be able to programmatically deploy a DVWA instance that's ready to use. I can cover all the pre-requisite steps and get the server and DB ready, it would just be great to be able to call a script or set of commands to do whatever happens when you click the Create/Reset Database button when you first arrive at a fresh install. Is there any chance of this?

**Comment by digininja** [comment]
Set it up once, dump the database with mysqldump then you can import that
into anywhere else you want.

**Comment by jamesholland-uk** [comment]
Thanks for the quick reply digininja. Will the presence of the imported database on the server mean that you will be able to get directly to login.php then? As without clicking that button, you always get redirected to setup.php

**Comment by digininja** [comment]
From the top of my head, the page just checks if the database is created
and if not bounces you so as long as it's there you will be able to log in

**Comment by jamesholland-uk** [comment]
Perfect, this worked, thanks so much!!
