### ISSUE TITLE
Create/Reset Database Button Refreshes Back to Setup Page

### ISSUE THREAD

**Issue by jamesholland-uk** [ethicalhack3r/DVWA#267]
On a fresh install from cloning the git repo (git clone https://github.com/ethicalhack3r/DVWA), onto an Ubuntu 14.04 VM in GCP (hostname 4.4.0-133-generic #159~14.04.1-Ubuntu SMP Fri Aug 10 08:17:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux), clicking the Create/Reset Database doesn't do anything, just refreshes back to the same page. I've spent a while reading a few similar previous issues, but I've not found a solution yet. I've pasted info below (and redacted a few bits and changed IP addresses) which was asked in previous issues. Any ideas what this might be?

**Apache Access Log:**
10.x.x.x - - [05/Oct/2018:10:04:07 +0000] "POST /setup.php HTTP/1.1" 302 443 "http://1.1.1.1/setup.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
10.x.x.x - - [05/Oct/2018:10:04:07 +0000] "GET /setup.php HTTP/1.1" 200 2153 "http://1.1.1.1/setup.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

**Apache Error Log:**
[Fri Oct 05 10:04:07.061185 2018] [:error] [pid 11582] [client 10.x.x.x:37462] PHP Notice:  Undefined index: session_token in /var/www/html/setup.php on line 14, referer: http://1.1.1.1/setup.php
[Fri Oct 05 10:04:37.190907 2018] [:error] [pid 11581] [client 10.x.x.x:29877] PHP Notice:  Undefined index: session_token in /var/www/html/setup.php on line 14, referer: http://1.1.1.1/setup.php
[Fri Oct 05 10:11:12.654258 2018] [:error] [pid 11646] [client 10.x.x.x:21345] PHP Notice:  Undefined index: session_token in /var/www/html/setup.php on line 14, referer: http://1.1.1.1/setup.php

**PHP**
$php -v
PHP 5.5.9-1ubuntu4.26 (cli) (built: Sep 17 2018 13:46:30)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**Git**
DVWA$ git rev-parse HEAD
7244d08fe06b981ea5f58ec38f569cc04aef498b

**Setup page info:**
Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 5.5.9-1ubuntu4.26

Web Server SERVER_NAME: 35.242.177.40

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: *blank*
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: <present, but redacted here>

[User: root] Writable folder /var/www/html/hackable/uploads/: Yes
[User: root] Writable file /var/www/html/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

[User: root] Writable folder /var/www/html/config: Yes 
Status in red, indicate there will be an issue when trying to complete some modules.

If you see disabled on either allow_url_fopen or allow_url_include, set the following in your php.ini file and restart Apache.
allow_url_fopen = On
allow_url_include = On

**Comment by digininja** [comment]
You can't use root as the user, create a different user

**Comment by jamesholland-uk** [comment]
Ok thanks digininja. It has been working fine with root previously, but I will look to change the automation that spins it all up to use a different user. FWIW it was working fine for days, then this behaviour started happening 2 days ago, then stopped a few hours later. Then it started happening again this evening. Very strange considering the server, OS and the config are built from an automation toolset.

**Comment by digininja** [comment]
Assuming you are using MariaDb, only the root Linux user can connect to the
database as root so unless you were running the web server as root it
shouldn't have been able to connect.

Despite how it sometimes looks, computers are deterministic and if it
worked then stopped working then something changed somewhere.

**Comment by jamesholland-uk** [comment]
It's MySQL FWIW on the root user thing. Totally agree about deterministic output though, that's why it's so frustrating :-)

**Comment by digininja** [comment]
What OS? Are you deliberately running myself?

**Comment by jamesholland-uk** [comment]
Ubuntu. Did you mean am I deliberately running MySQL, in which case, it just happened to be that I was already on a LAMP stack kinda setup.

**Comment by digininja** [comment]
I meant did you deliberately install mysql as opposed to MariaDb which
comes as the default Ubuntu package

**Comment by jamesholland-uk** [comment]
Ah ok. No, like I say, I had MySQL in the automation build already.

You'll hate me, but I've found this one to be a browser thing. The create-reset button wasn't working in Chrome, but I just tried Safari and it worked fine. That meant I was able to mysqldump like you suggested in Issue 266, so I've totally bypassed this button now anyway. My apologies!

**Comment by digininja** [comment]
Just for context, I've spent a lot of time debugging Fedora and MySQL
as installed from the MySQL official packages and so wanted to be sure
exactly what was installed before going digging around in the wrong
area.

It is odd the button didn't work in Chrome, if you want to try to
debug it or create a ticket with more info in then we can look at it.

**Comment by jamesholland-uk** [comment]
Thanks mate. The  login to DVWA with the default creds was also not working in Chrome, but was in other browsers. I highly suspect it may be an extension or some odd cached content in my Chrome, as it worked in Chrome on a colleague's machine. If I do get a concrete reproducible issue I will raise another ticket as you advised. Thanks for the great web-app and great support!

**Comment by spedicino** [comment]
I'm not sure if it will let me post this, but anyway.

I had a similar issue like James. However, my experience was exactly the opposite. I have a fresh install of Amazon Linux 2, and followed the readme, and tutorials. I even ran the script described in: https://github.com/ethicalhack3r/DVWA/issues/134#issuecomment-302418028

(it worked) but it didn't matter what I did, every time I hit the "Create DB" nothing would happen, just a refresh of the page. That's how I got to this page and I tried Chrome. Worked perfectly the 1st time around.

I am not sure if with my current setup I can help debug what the issue might be with IE.

Thanks for your continuous support digininja. I read many of the issues, and I can understand how irritating must be to reply over and over regarding the same issues.

Cheers,
Sergio

**Comment by digininja** [comment]
@spedicino if it is consistent then we can probably debug it. If my script works, then the database connection is working fine so that isn't the issue.

Can you tail the apache access and error logs and post all the entries that come after you click the create button. That might give us something to work on.

**Comment by spedicino** [comment]
Hi,

So I was trying to replicate the issue, and it seems that it is working
from IE as well.. I'll paste the access and error logs in the email but
there's nothing wrong with them. I'll see if I can replicate the issue in
the next few days and get back to you.

[root@ip-10-2-67-174 httpd]# date

Thu Nov 14 04:17:39 UTC 2019

[root@ip-10-2-67-174 httpd]# tail access_log

10.2.17.237 - - [14/Nov/2019:04:16:58 +0000] "GET
/dvwa/dvwa/images/logo.png HTTP/1.1" 200 5044 "
http://10.2.67.174/dvwa/setup.php" "Mozilla/5.0 (Windows NT 10.0; WOW64;
Trident/7.0; rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:16:58 +0000] "GET
/dvwa/js/add_event_listeners.js HTTP/1.1" 404 196 "
http://10.2.67.174/dvwa/setup.php" "Mozilla/5.0 (Windows NT 10.0; WOW64;
Trident/7.0; rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:16:58 +0000] "GET
/dvwa/dvwa/images/spanner.png HTTP/1.1" 200 464 "
http://10.2.67.174/dvwa/setup.php" "Mozilla/5.0 (Windows NT 10.0; WOW64;
Trident/7.0; rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:16:58 +0000] "GET /dvwa/favicon.ico
HTTP/1.1" 200 1406 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0;
rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:17:03 +0000] "GET /dvwa/login.php HTTP/1.1"
200 1523 "http://10.2.67.174/dvwa/setup.php" "Mozilla/5.0 (Windows NT 10.0;
WOW64; Trident/7.0; rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:17:03 +0000] "GET /dvwa/dvwa/css/login.css
HTTP/1.1" 200 842 "http://10.2.67.174/dvwa/login.php" "Mozilla/5.0 (Windows
NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:17:03 +0000] "GET
/dvwa/dvwa/images/login_logo.png HTTP/1.1" 200 9088 "
http://10.2.67.174/dvwa/login.php" "Mozilla/5.0 (Windows NT 10.0; WOW64;
Trident/7.0; rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:17:19 +0000] "POST /dvwa/login.php
HTTP/1.1" 302 - "http://10.2.67.174/dvwa/login.php" "Mozilla/5.0 (Windows
NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:17:19 +0000] "GET /dvwa/index.php HTTP/1.1"
200 6815 "http://10.2.67.174/dvwa/login.php" "Mozilla/5.0 (Windows NT 10.0;
WOW64; Trident/7.0; rv:11.0) like Gecko"

10.2.17.237 - - [14/Nov/2019:04:17:19 +0000] "GET
/dvwa/js/add_event_listeners.js HTTP/1.1" 404 196 "
http://10.2.67.174/dvwa/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64;
Trident/7.0; rv:11.0) like Gecko"

[root@ip-10-2-67-174 httpd]#

[root@ip-10-2-67-174 httpd]#

[root@ip-10-2-67-174 httpd]#

[root@ip-10-2-67-174 httpd]#

[root@ip-10-2-67-174 httpd]# tail error_log

[Thu Nov 14 03:54:53.841388 2019] [http2:warn] [pid 3065] AH02951: mod_ssl
does not seem to be enabled

[Thu Nov 14 03:54:53.846545 2019] [mpm_prefork:notice] [pid 3065] AH00163:
Apache/2.4.41 () configured -- resuming normal operations

[Thu Nov 14 03:54:53.846567 2019] [core:notice] [pid 3065] AH00094: Command
line: '/usr/sbin/httpd -D FOREGROUND'

[Thu Nov 14 03:58:28.026519 2019] [mpm_prefork:notice] [pid 3065] AH00170:
caught SIGWINCH, shutting down gracefully

[Thu Nov 14 03:59:00.075160 2019] [suexec:notice] [pid 3024] AH01232:
suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)

[Thu Nov 14 03:59:00.109103 2019] [lbmethod_heartbeat:notice] [pid 3024]
AH02282: No slotmem from mod_heartmonitor

[Thu Nov 14 03:59:00.109150 2019] [http2:warn] [pid 3024] AH10034: The mpm
module (prefork.c) is not supported by mod_http2. The mpm determines how
things are processed in your server. HTTP/2 has more demands in this regard
and the currently selected mpm will just not do. This is an advisory
warning. Your server will continue to work, but the HTTP/2 protocol will be
inactive.

[Thu Nov 14 03:59:00.109155 2019] [http2:warn] [pid 3024] AH02951: mod_ssl
does not seem to be enabled

[Thu Nov 14 03:59:00.124660 2019] [mpm_prefork:notice] [pid 3024] AH00163:
Apache/2.4.41 () configured -- resuming normal operations

[Thu Nov 14 03:59:00.124686 2019] [core:notice] [pid 3024] AH00094: Command
line: '/usr/sbin/httpd -D FOREGROUND'



Thank you
