### ISSUE TITLE
PostgreSQL is not yet fully supported.

### ISSUE THREAD

**Issue by rseasgsa** [ethicalhack3r/DVWA#269]
Hello
PostgreSQL is not yet fully supported.
This is the message I always receive when I click the Reset/create database button in my http://127.0.0.1/dvwa/setup.php
I downloaded the postgresql and yet nothing changed. Maybe something I missed in the configuration file or maybe not.
Please who has the solution to this problem will had my thanks.
Thank you

**Comment by digininja** [comment]
Postgresql isn't supported at all and isn't likely to be any time soon. It
was a plan at the start but never really took off.

**Comment by rseasgsa** [comment]
So what should I do
How do I get this database created

**Comment by mike-bailey** [comment]
Use MySQL or a supported database engine.

**Comment by digininja** [comment]
Rewrite DVWA to support postgresql.

There is virtually no code in the app to work with postgresql and that that
is there hasn't been touched since version one many years so is unlikely to
work now

**Comment by rseasgsa** [comment]
To Mike thanks
if I understand you I run mysql and apache2 before I check to create the dvwa databse yet nothing new
To digi thanks
The work you asking me to do a big one and will be different from anyone who has created this danm batabase. I really don't see it worthed

**Comment by mike-bailey** [comment]
You'd have to use mysql and create a database within MySQL to run the application.

**Comment by digininja** [comment]
All I was pointing out was that it isn't supported and that if you want it
then either implement it or find someone interested in doing it for you.

**Comment by mike-bailey** [comment]
Closing as resolved, feel free to further comment.
