### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by genkaiten** [ethicalhack3r/DVWA#271]
I have my DVWA folder in /var/www/html/ 
but I get the following error. What to do?

DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment.

**Comment by digininja** [comment]
How about reading the error message?

**Comment by genkaiten** [comment]
Read the message, but there's no way to know how to configure to my environment. What does that mean?

**Comment by mike-bailey** [comment]
Please read the file and associated documentation https://github.com/ethicalhack3r/DVWA#database-setup

**Comment by genkaiten** [comment]
Hey Mike, that really helped me out. Thanks so much for the pivot point that turned things around.

**Comment by genkaiten** [comment]
I had problems connecting to the mariaDB database still, so I changed the
password. As per the
directions in the config file, I am trying to connect as a normal user,
outside of root. But still I can't
connect. In the browser address bar I've tried "localhost/dvwa"  as well as
"127.0.0.1/dvwa".
Nothing works.

**Comment by digininja** [comment]
Define "nothing works".

Send copies of your Apache error log /var/log/apache/error.log

Prove you can connect to the database on the command line using the creds
from the config file

Send a copy of the config file

Instructions for doing all of these are in previously closed tickets

**Comment by digininja** [comment]
There is no point obfuscating the password, to be able to use it we would
have to find your box, some how get access to it, and then connect to mysql
to get access to the DVWA database which doesn't really contain much.

You also didn't mention the proof that you could connect to the database on
the command line with those credentials. That is one of the things that
regularly turns out to be wrong.

**Comment by genkaiten** [comment]
I can connect on root using the following command:
mysql -u root -h localhost -p

But I can't connect from the dedicated user. I know
there's a fix to this but I'm not a seasoned Kali Linux
user.

**Comment by mike-bailey** [comment]
> from the dedicated user
Can you clarify this? How'd you make the dedicated user.

**Comment by genkaiten** [comment]
I just added a user to Kali Linux called "genkaiten". I now have
a choice to log into Kali under "root" or "genkaiten"

**Comment by digininja** [comment]
It doesn't sound like you've created a mysql user (not Kali). Read the
readme, it gives full details of how to do it.

**Comment by genkaiten** [comment]
I've followed the directions in the READ ME file to the letter. Then in the
dedicated
user account I opened the mysql service as you can see in the screen shot.
Then
I entered localhost/dvwa and also 127.0.0.1 in the address window of the
browser.
In the config file I have 127.0.0.1 instead of 'localhost' in the settings.

Now, not only can't I see the DVWA page, I get an error.

**Comment by mike-bailey** [comment]
Did you follow the “grant all on” SQL statement to create the user ?

**Comment by genkaiten** [comment]
I followed the READ ME directions and that's all I can do. There are no
directions
about the "grant all on" SQL statement.

**Comment by mike-bailey** [comment]
I should clarify. I'm referring to this:
![image](https://user-images.githubusercontent.com/7607089/47122590-6d1d1900-d245-11e8-8941-6090f4ef82dd.png)

**Comment by genkaiten** [comment]
Yes I did that

**Comment by genkaiten** [comment]
I took a screen shot of that

**Comment by mike-bailey** [comment]
If you followed it literally, the username would be `dvwa` and password would be `xxx`

**Comment by mike-bailey** [comment]
None of your screenshots attached as previously noted, probably due to email.

**Comment by mike-bailey** [comment]
The "xxx" bit is supposed to be replaced but we could probably do a better job clarifying that. It's been an issue with others in the past.

**Comment by genkaiten** [comment]
Michael, the following is what I entered into Kali under my
root account. Can you tell me what I'm doing wrong here?


genkaiten@kali:~$ ```mysql
> create database dvwa;
> grant all on dvwa.* to genkaiten@localhost identified by 'Ciel&1976';
> flush privileges;
> ```
ERROR 1698 (28000): Access denied for user 'genkaiten'@'localhost'
bash: create: command not found
bash: grant: command not found
bash: flush: command not found
genkaiten@kali:~$

**Comment by mike-bailey** [comment]
All good! the 
```
mysql>
```

indicates you are already logged into MySQL, so you'd need to run in your case the `mysql -u root -h localhost -p` bit, then you should see your console change. Similar to how some documents would tell you `# command-here` and to run it in a root shell.

**Comment by genkaiten** [comment]
I after entering that command I started getting somewhere. Below is what I
entered in the root account. Later, I went to my user account "genkaiten"
and I am still not even able to see the html DVWA mockup anymore.
The browser says "Unable to connect, Firefox is unable to connect to
the server at 127.0.0.1

====

root@kali:~# mysql -u root -h localhost -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 35
Server version: 10.1.29-MariaDB-6 Debian buildd-unstable

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input
statement.

MariaDB [(none)]> create database dvwa;
Query OK, 1 row affected (0.03 sec)

MariaDB [(none)]> grant all on dvwa.* to genkaiten@localhost identified by
'Ciel&1976';
Query OK, 0 rows affected (0.14 sec)

MariaDB [(none)]> flush privileges;
Query OK, 0 rows affected (0.04 sec)

MariaDB [(none)]> ```
    `> Ctrl-C -- exit!
Aborted
root@kali:~# ```
> ^C
root@kali:~#

**Comment by mike-bailey** [comment]
Did you install a webserver? Per https://github.com/ethicalhack3r/DVWA#linux-packages

**Comment by genkaiten** [comment]
Apache is running when I just enter "localhost" in the address line. I
installed it
when following the tutorial of a Youtube video.

**Comment by mike-bailey** [comment]
I believe the youtube tutorial is out of date and we don't maintain it so not sure. Are you running Kali in a virtual machine?

**Comment by genkaiten** [comment]
I entered exactly that line in Kali root and I got a convoluted message.
Below
is what I entered.


root@kali:~# apt-get -y install apache2 mysql-server php php-mysqli php-gd
libapache2-mod-php
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package mysql-server is not available, but is referred to by another
package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php-mysqli is a virtual package provided by:
  php7.0-mysql 7.0.27-1
  php7.2-mysql 7.2.4-1+b2
You should explicitly select one to install.

E: Package 'mysql-server' has no installation candidate
E: Package 'php-mysqli' has no installation candidate
root@kali:~#

**Comment by genkaiten** [comment]
Yes, Kali is being run in a virtual machine

**Comment by genkaiten** [comment]
Michael, I have to leave this WiFi hotspot now. It is worth noting that one
Ethical Hacker who did
a video on using DVWA didn't finish the last part because he himself
couldn't connect. Hoping
to be able to use this software because I'm told it's the GoTo place to
learn SQL Injection.

**Comment by genkaiten** [comment]
It sure would have been nice to install DVWA but I see that's not a
possibility. I actually installed
it on Kali about 3 years ago and it worked. Oh well.

**Comment by mike-bailey** [comment]
We’re sorry to hear you had a poor experience. I believe the only install step that’s changed in 3 years is the config file being named something different. Regardless, good luck in your studies.
