### ISSUE TITLE
Call to undefined function mysqli_connect

### ISSUE THREAD

**Issue by shinios** [ethicalhack3r/DVWA#272]
The server is up and running and through localhost/ I can access the DVWA directories but instead of getting the login page I get a blank page. (no error or anything) I've gone through some older issues and found that it might be due to a lack of php-mysql but I've checked for that and newer versions.
OS: Kali Linux 

``[Fri Oct 19 19:11:18.376479 2018] [mpm_prefork:notice] [pid 1940] AH00163: Apache/2.4.34 (Debian) configured -- resuming normal operations
[Fri Oct 19 19:11:18.504325 2018] [core:notice] [pid 1940] AH00094: Command line: '/usr/sbin/apache2'
[Fri Oct 19 19:12:17.472332 2018] [:error] [pid 1990] [client ::1:56142] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA-master/dvwa/includes/dvwaPage.inc.php:470\nStack trace:\n#0 /var/www/html/DVWA-master/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA-master/dvwa/includes/dvwaPage.inc.php on line 470, referer: http://localhost/
[Fri Oct 19 19:12:21.069978 2018] [:error] [pid 1991] [client ::1:56148] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php:470\nStack trace:\n#0 /var/www/html/DVWA/login.php(8): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/DVWA/dvwa/includes/dvwaPage.inc.php on line 470, referer: http://localhost/``

**Comment by digininja** [comment]
You are missing the PHP mysqli package, install that.

**Comment by digininja** [comment]
It is usually enabled by default when it is installed.

Check the phpinfo page and search for mysql. And I'll leave it up to you to
find it as your first bit of app hacking

**Comment by shinios** [comment]
gone through the phpinfo in the dvwa main directory is only a couple lines and the only reference I get is the dvwaPage.inc.php and in that file I find some mysql stuff but I'm not entirely sure what I'm supposed to do there.

**Comment by digininja** [comment]
Work out what phpinfo is and get the info out of it.

Welcome to the start of app hacking.

**Comment by shinios** [comment]
So I've set up the phpinfo but the search for mysql didn't get me really far, as it only showed the authors for the mysqli module. So, I went into the php.ini config file and looked up mysql in there. I changed some settings around but I am still ending up with a blank page for dvwa.

**Comment by digininja** [comment]
If the mysqli module is mentioned then it is installed and working, it
should tell you config settings as well.

Tail the error log at the same time as accessing the setup page, screenshot
the log page and the section of the phpinfo page where it shows mysql

**Comment by shinios** [comment]
I've attached a screenshot of the error log
The php.ini of the apache2 and a screenshot of line 470 which is mentioned in the error log.
the phpinfo itself contains mysqli only once and just to mention the authors, so I haven't attached that one.

![screenshot from 2018-10-20 08-24-41](https://user-images.githubusercontent.com/44302032/47252841-10874d00-d443-11e8-9f44-994e56228162.png)
![screenshot from 2018-10-20 08-30-02](https://user-images.githubusercontent.com/44302032/47252852-28f76780-d443-11e8-8e57-b66c41232ac8.png)
![screenshot from 2018-10-20 08-32-35](https://user-images.githubusercontent.com/44302032/47252853-28f76780-d443-11e8-8444-7012d5bda882.png)

**Comment by digininja** [comment]
Need a screenshot of the phpinfo page as rendered in a browser please.

**Comment by shinios** [comment]
![fireshot capture 001 - phpinfo - http___127 0 0 1_phpinfo php](https://user-images.githubusercontent.com/44302032/47252992-49282600-d445-11e8-9e62-55dd22416823.png)

**Comment by digininja** [comment]
I can't see any mention of mysql in that so the module isn't enabled.

Find out how to use dpkg to get a list of installed packages, filter that
for mysql and then send a screenshot of that.

Find out how to list what modules are enabled in PHP and send a screenshot
of checking that. I'd expect no results.

**Comment by shinios** [comment]
to me it seems like mysql is up and running

![dpkg](https://user-images.githubusercontent.com/44302032/47253654-dec7b380-d44d-11e8-9515-d18b414cd9c7.png)
![php -m](https://user-images.githubusercontent.com/44302032/47253655-df604a00-d44d-11e8-91a4-a6aacb01db8a.png)

**Comment by digininja** [comment]
It looks like it but try get-selection on dpkg to list installed packages.

Have you restarted Apache since you installed it?

Have you done anything deliberately different when setting anything up?
Such as go for PHP fpm. Something is screwed up that may be a really simple
change but killed it.

**Comment by shinios** [comment]
I didnt do any special adjustments, but a while back I did run some remove/autoremove commands.
Maybe I did delete something that I shouldn't have. Is there a way to scan for missing packages that should normally be installed?
![get selections](https://user-images.githubusercontent.com/44302032/47254240-6534c300-d457-11e8-8553-a32fcc61b299.png)

**Comment by digininja** [comment]
I don't know if having 7.2 and 7.3 installed at the same time could cause a
problem, I'm not at a machine to test it.

It shouldn't make a difference as you don't need the mysql server on the
same machine, but is the server up and running and can you connect to it on
the command line?

**Comment by mike-bailey** [comment]
No reply. Normally I warn but it's been half a year.
