### ISSUE TITLE
DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment.

### ISSUE THREAD

**Issue by vjadi** [ethicalhack3r/DVWA#275]
DVWA System error - config file not found. Copy config/config.inc.php.dist to config/config.inc.php and configure to your environment. how can i fix this problem

**Comment by digininja** [comment]
The answer is in the error message, copy the distributed config file to the
real one and then configure it. It's all documented.

**Comment by mike-bailey** [comment]
Please provide more details

**Comment by vipul-nair** [comment]
do exactly what the error says.go to config directory copy the config.inc.php.dist as config.inc.php in the same directory...it will work
