### ISSUE TITLE
Hight level csrf

### ISSUE THREAD

**Issue by vipul-nair** [ethicalhack3r/DVWA#277]
There is an additional parameter, a csrf token, which is submitted in the get request. All the answers i saw on the web uses xss to trigger the password change.
I thought of a different way and was wondering if my answer was right ?

Basically what i do is create a php script on attacker website which requests the dvwa csrf page, collects the user_token issued to the attacker page then use that token to further submit the password, new_password and the user_token. I tried doing this (request two pages and using the user token of one page on another
) will it work?

**Comment by digininja** [comment]
You are asking "will it work?", the best way to find out is to try.

And there are no right it wrong answers, if you get the desired results
then you win.

**Comment by vipul-nair** [comment]
but in your opinion.will it work?i dont wanna waste time implementing a flawed logic
