### ISSUE TITLE
Install???

### ISSUE THREAD

**Issue by bayvista** [ethicalhack3r/DVWA#278]
Where are the instructions for Kali?

**Comment by mike-bailey** [comment]
They are located in the README file on the homepage of the project.

**Comment by bayvista** [comment]
Ok . So I have installed DVWA Then it says 'Simply unzip dvwa.zip, place the unzipped files in your public html folder, then point your browser to: http://127.0.0.1/dvwa/setup.php'. 
Where is my public html folder?

**Comment by mike-bailey** [comment]
I encourage you to check out videos on the matter. If something hiccups from there, we can gladly assist with that, but this is a well documented matter.

**Comment by bayvista** [comment]
Herewith:

root@kali:/var/www/html# tail /var/log/apache2/error.log
[Mon Nov 26 13:26:59.388527 2018] [php7:error] [pid 5306] [client
127.0.0.1:55684] PHP Fatal error:  require_once(): Failed opening required
'dvwa/includes/dvwaPage.inc.php' (include_path='.:/usr/share/php') in
/var/www/html/dvwa/index.php on line 4
[Mon Nov 26 13:40:32.304719 2018] [core:error] [pid 4355] (13)Permission
denied: [client 127.0.0.1:55698] AH00035: access to /dvwa/index.html denied
(filesystem path '/var/www/html/dvwa/index.html') because search
permissions are missing on a component of the path
[Mon Nov 26 13:40:32.304815 2018] [core:error] [pid 4355] (13)Permission
denied: [client 127.0.0.1:55698] AH00035: access to /dvwa/index.cgi denied
(filesystem path '/var/www/html/dvwa/index.cgi') because search permissions
are missing on a component of the path
[Mon Nov 26 13:40:32.304855 2018] [core:error] [pid 4355] (13)Permission
denied: [client 127.0.0.1:55698] AH00035: access to /dvwa/index.pl denied
(filesystem path '/var/www/html/dvwa/index.pl') because search permissions
are missing on a component of the path
[Mon Nov 26 13:40:32.304896 2018] [core:error] [pid 4355] (13)Permission
denied: [client 127.0.0.1:55698] AH00035: access to /dvwa/index.php denied
(filesystem path '/var/www/html/dvwa/index.php') because search permissions
are missing on a component of the path
[Mon Nov 26 13:40:32.304936 2018] [core:error] [pid 4355] (13)Permission
denied: [client 127.0.0.1:55698] AH00035: access to /dvwa/index.xhtml
denied (filesystem path '/var/www/html/dvwa/index.xhtml') because search
permissions are missing on a component of the path
[Mon Nov 26 13:40:32.304976 2018] [core:error] [pid 4355] (13)Permission
denied: [client 127.0.0.1:55698] AH00035: access to /dvwa/index.htm denied
(filesystem path '/var/www/html/dvwa/index.htm') because search permissions
are missing on a component of the path
[Mon Nov 26 13:41:40.919602 2018] [core:error] [pid 4353] (13)Permission
denied: [client 127.0.0.1:55700] AH00035: access to /dvwa/setup.php denied
(filesystem path '/var/www/html/dvwa/setup.php') because search permissions
are missing on a component of the path
[Mon Nov 26 13:42:25.320457 2018] [core:error] [pid 4356] (13)Permission
denied: [client 127.0.0.1:55726] AH00035: access to /dvwa/setup.php denied
(filesystem path '/var/www/html/dvwa/setup.php') because search permissions
are missing on a component of the path
[Mon Nov 26 13:46:32.797862 2018] [core:error] [pid 4354] (13)Permission
denied: [client 127.0.0.1:55804] AH00035: access to /dvwa/setup.php denied
(filesystem path '/var/www/html/dvwa/setup.php') because search permissions
are missing on a component of the path
root@kali:/var/www/html#

**Comment by mike-bailey** [comment]
`chmod -R 755 /var/www/html` and try again please

**Comment by bayvista** [comment]
DVWA System error - config file not found. Copy config/config.inc.php.dist
to config/config.inc.php and configure to your environment.

OK I'll try this next. Where are you?

**Comment by mike-bailey** [comment]
>Where are you?

Physically? USA

>OK I'll try this next

This step is likely newer than the video, sounds good :)

**Comment by mike-bailey** [comment]
Nothing as in a blank display? What do the logs say?

**Comment by bayvista** [comment]
Log:

[Tue Nov 27 16:18:04.527135 2018] [php7:notice] [pid 4354] [client 127.0.0.1:56160] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
[Tue Nov 27 16:29:05.581984 2018] [php7:notice] [pid 4353] [client 127.0.0.1:56178] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
[Tue Nov 27 16:34:03.585300 2018] [php7:notice] [pid 5306] [client 127.0.0.1:56190] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
[Tue Nov 27 16:34:34.289961 2018] [php7:notice] [pid 23386] [client 127.0.0.1:56196] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
[Tue Nov 27 16:39:35.489630 2018] [php7:notice] [pid 4356] [client 127.0.0.1:56238] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
[Tue Nov 27 16:50:39.424416 2018] [mpm_prefork:notice] [pid 4350] AH00169: caught SIGTERM, shutting down
[Tue Nov 27 16:50:48.701236 2018] [mpm_prefork:notice] [pid 25551] AH00163: Apache/2.4.37 (Debian) configured -- resuming normal operations
[Tue Nov 27 16:50:48.701367 2018] [core:notice] [pid 25551] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 27 16:51:57.390657 2018] [php7:notice] [pid 25555] [client 127.0.0.1:56278] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
[Tue Nov 27 16:52:38.223227 2018] [php7:notice] [pid 25607] [client 127.0.0.1:56290] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
[Tue Nov 27 16:58:40.696510 2018] [mpm_prefork:notice] [pid 25551] AH00169: caught SIGTERM, shutting down
[Tue Nov 27 16:58:40.911950 2018] [mpm_prefork:notice] [pid 25885] AH00163: Apache/2.4.37 (Debian) configured -- resuming normal operations
[Tue Nov 27 16:58:40.912077 2018] [core:notice] [pid 25885] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 27 17:04:12.925356 2018] [php7:notice] [pid 25888] [client 127.0.0.1:56316] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
[Tue Nov 27 17:27:06.741988 2018] [php7:notice] [pid 25887] [client 127.0.0.1:56434] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9

**Comment by mike-bailey** [comment]
Are you able to manually connect to the MySQL server via `mysql -udvwa -h127.0.0.1 -pSuperSecretPassword99 dvwa`?

**Comment by bayvista** [comment]
root@kali:/var/log/apache2# mysql -udvwa -h127.0.0.1 -pSuperSecretPassword99 dvwa
ERROR 1698 (28000): Access denied for user 'dvwa'@'localhost'

**Comment by mike-bailey** [comment]
Did you create the dvwa user?

**Comment by bayvista** [comment]
How do I do that?

**Comment by mike-bailey** [comment]
Please see "Database Setup" under the readme

**Comment by bayvista** [comment]
Thanks Mike for all your patience. I'm now logged into dvwa.

**Comment by RilanHou** [comment]
> 感谢Mike的耐心等待。我现在登录了dvwa。

Hello bayvista！How did you solve this problem? 
Notice: Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9
