### ISSUE TITLE
Could not connect to the MySQL service. Please check the config file.

### ISSUE THREAD

**Issue by hoodie12** [ethicalhack3r/DVWA#279]
i looked in all of the issues but i couldn't find an answer please help i watched the video followed it step by step but to nothing i get this every time
 
Could not connect to the MySQL service.
Please check the config file.
Your database user is root, if you are using MariaDB, this will not work, please read the README.md file.

**Comment by mike-bailey** [comment]
Are you using MariaDB per chance?
