### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Blackscript3** [ethicalhack3r/DVWA#282]
Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in D:\server\wamp\www\DVWA-master\dvwa\dvwa\includes\dvwaPage.inc.php:478 Stack trace: #0 D:\server\wamp\www\DVWA-master\dvwa\dvwa\includes\dvwaPage.inc.php(478): PDO->__construct('mysql:host=127....', 'root', '') #1 D:\server\wamp\www\DVWA-master\dvwa\login.php(8): dvwaDatabaseConnect() #2 {main} thrown in D:\server\wamp\www\DVWA-master\dvwa\dvwa\includes\dvwaPage.inc.php on line 478

what can i do?

**Comment by digininja** [comment]
If you google the error:

```
Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in 
```

there are a lot of pages that discuss it and give possible solutions. Have you tried any of those?

**Comment by Blackscript3** [comment]
no!

**Comment by Blackscript3** [comment]
All is well but not being!

**Comment by digininja** [comment]
If you say so.

**Comment by Blackscript3** [comment]
:(
