### ISSUE TITLE
Remote File Inclusion on low security

### ISSUE THREAD

**Issue by Hhhhelix** [ethicalhack3r/DVWA#283]
I can confirm LFI by using payload "http://127.0.0.1/dvwa/vulnerabilities/fi/?page=/php.info.php",
but i've got some troubles in confirm RFI by using 
"http://127.0.0.1/dvwa/vulnerabilities/fi/?page=https://www.google.com"
It gives the following errors:
```
Warning: include(https://www.google.com) [function.include]: failed to open stream: Invalid argument in C:\phpStudy\PHPTutorial\WWW\dvwa\vulnerabilities\fi\index.php on line 36

Warning: include() [function.include]: Failed opening 'https://www.google.com' for inclusion (include_path='.;C:\php5\pear;../../external/phpids/0.6/lib/') in C:\phpStudy\PHPTutorial\WWW\dvwa\vulnerabilities\fi\index.php on line 36
```

I'm running DVWA on phpMyAdmin on VM windows 7,the php version is 5.2.17.
How can I fix it,please?

**Comment by digininja** [comment]
What level are you on? Works fine for me.

![image](https://user-images.githubusercontent.com/117081/50529702-c085d000-0aee-11e9-8cdd-d197c5a23a06.png)

**Comment by Hhhhelix** [comment]
I get what happened!When i click on the File Inclusion bar,the security level change to impossible,while clicking on the other bar it doesn't change.I use burp to modifier the security it just works...why?

**Comment by digininja** [comment]
Probably a bug in the code that sets the security level cookie. I went in
on medium, changed to low then included Google and it worked fine so the
vulnerability is working, just some bug in the general code around it.

**Comment by ratm9808** [comment]
same problem exist in metasploitable2. i highly recommend to use the dvwa from the github. 
https://github.com/ethicalhack3r/DVWA

**Comment by axano** [comment]
Guys. It is most probably a php.ini issue. be sure that url include is 'On' in all of the following files
/var/www/dvwa/php.ini
/etc/php5/cli/php.ini
/etc/php5/cgi/php.ini
/etc/php5/apache2/php.ini

; Whether to allow include/require to open URLs (like http:// or ftp://) as files.
allow_url_include = On
