### ISSUE TITLE
Could not connect to MySQL service

### ISSUE THREAD

**Issue by donnacha69** [ethicalhack3r/DVWA#284]
CentOS 7.6 (x86_64)
PHP 5.4.16
MySQL 8.0.13
Apache 2.0

Latest version of DVWA installed from GitHub.

Error after clicking on the "Create / Reset Database" button: Could not connect to MySQL service Please check the config file.

-------------------------------------------------------------------------------------------------------------------

# Database variables
#   WARNING: The database specified under db_database WILL BE ENTIRELY DELETED during setup.
#   Please use a database dedicated to DVWA.
#
# If you are using MariaDB then you cannot use root, you must use create a dedicated DVWA user.
#   See README.md for more information on this.
$_DVWA = array();
$_DVWA[ 'db_server' ]   = 'localhost';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'dvwausr2';
$_DVWA[ 'db_password' ] = 'XXXXXXXX';

# Only used with PostgreSQL/PGSQL database selection.
$_DVWA[ 'db_port '] = '5432';

----------------------------------------------------------------------------------------------------------------

Can connect to MySQL on the command line....

[root@localhost ~]# mysql -u dvwausr2 -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 15
Server version: 8.0.13 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| dvwa               |
| information_schema |
| mysql              |
+--------------------+
3 rows in set (0.01 sec)

mysql> use dvwa
Database changed
mysql>

---------------------------------------------------------------------------------------------------------------

Thanks!

**Comment by mike-bailey** [comment]
I don’t think 5432 is the right port for MySQL.

**Comment by donnacha69** [comment]
Thanks for the quick response. This configuration item is only relevant to PostgreSQL, according to the configuration file. Regardless, I changed it to 3306, still no luck.

By the way, I do see connection attempts in the MySQL logs but no error.  The following is from the MySQL general_log:

2019-01-14T06:27:02.494653Z        19 Connect   dvwausr2@localhost on  using Socket

However, if I connect via the command-line, I get the following logged...

2019-01-14T06:35:53.983669Z        20 Connect   dvwausr2@localhost on  using Socket
2019-01-14T06:35:53.984237Z        20 Query     select @@version_comment limit 1

I do not get the last line as output in the log file if I click on the "Create / Reset Database" button.

**Comment by digininja** [comment]
And is that definitely the same as in the config file? No additional spaces
or punctuation?

Don't worry about obscuring things, unless you've reused your Github
password then us knowing the password for your DVWA setup isn't going to
give us anything we can use against you.

**Comment by donnacha69** [comment]
No additional spaces or punctuation. Here it is again....

![image](https://user-images.githubusercontent.com/46583383/51106230-1c0dc880-1826-11e9-901e-90cad46560a0.png)

![image](https://user-images.githubusercontent.com/46583383/51106246-29c34e00-1826-11e9-8794-b0d89cddff47.png)

**Comment by digininja** [comment]
What OS?

You are using MySQL so I'm guessing a CentOS type system, is it locked down with SELinux to stop connections between Apache and MySQL?

On the command line, try adding a -h localhost in case MySQL is only listening on sockets.

**Comment by donnacha69** [comment]
Thanks for your help, SELinux has been disabled.

CentOS 7.6 (x86_64)
PHP 5.4.16
MySQL 8.0.13
Apache 2.0

![image](https://user-images.githubusercontent.com/46583383/51151388-a6494180-18a5-11e9-974d-ca96fd204a53.png)

**Comment by donnacha69** [comment]
I used a short PHP script to verify PHP <-> MySQL connectivity:

<?php

$link = mysqli_connect("localhost", "dvwausr2", "DVWApass19", "dvwa");
# $link = mysqli_connect("localhost", "dvwausr2", "DVWApass19", "dvwa");

if (!$link) {
    echo "Error: Unable to connect to MySQL." . PHP_EOL;
    echo "Debugging errno: " . mysqli_connect_errno() . PHP_EOL;
    echo "Debugging error: " . mysqli_connect_error() . PHP_EOL;
    exit;
}

echo "Success: A proper connection to MySQL was made! The my_db database is great." . PHP_EOL;
echo "Host information: " . mysqli_get_host_info($link) . PHP_EOL;

mysqli_close($link);

?>

The result was an error connecting to MySQL due to a plugin: 'Authentication plugin 'caching_sha2_password' cannot be loaded', or something similar. 
The MySQL documentation instructed me to change the password to a format prior to MySQL 8, or the 'native' format. The encryption algorithm used to protect MySQL passwords has changed in MySQL 8.x?

I used the following command to update the password of the DVWA account in MySQL:

ALTER USER 'dvwausr2'@'localhost' IDENTIFIED WITH mysql_native_password BY 'DVWApass19';

This seems to have solved the problem. I now reach the login page.

**Comment by donnacha69** [comment]
the script...

![image](https://user-images.githubusercontent.com/46583383/51154259-296e9580-18ae-11e9-842c-2c9708ec817e.png)

**Comment by digininja** [comment]
I've seen this one before and remember spending ages debugging it, it was a
real pain to work out.

Glad it's fixed.

And for anyone else reading this, this is a good way to report an issue, we
got details of the problem, the guy did some thinking for himself and
reported back. The fact he fixed it on his own is a bonus, it's more about
putting effort in, thinking and not expecting to be spoon fed answers.
