### ISSUE TITLE
Unable to establish a connection to DVWA site

### ISSUE THREAD

**Issue by GirlKoks** [ethicalhack3r/DVWA#290]
I am unable to establish  a connection to the DVWA server. I tried with different machines but I still get the same error. It was working perfectly last night but this morning I can't access the server anymore.
Is the site down or is there something that I am doing wrong?

**Comment by mike-bailey** [comment]
As far as I know we don’t host DVWA so I’m not sure what server you’re referring to. There’s no central node us-side to go down.
