### ISSUE TITLE
Automatic DB creation

### ISSUE THREAD

**Issue by aracloud** [ethicalhack3r/DVWA#294]
Hi

I don't know if I'm correct here to post my request.

I would like to get DVWA creating the data base automatically upon initial start fo the app. Why? I use DVWA in a docker environment where I do security and availability tests and therefore it would be great while spinning up several containers (published via load balancer) to have DVWA including the data base ready to go without manual interaction.

So, this would mean for me to change the parts in the setup.php code to run the mysql create script instead of the form. But I don't know how to do this correctly.

Any help kindly appreciated!

**Comment by digininja** [comment]
Why not have the docker instance start with a pre-populated database?

**Comment by aracloud** [comment]
tested already and it does not work

**Comment by digininja** [comment]
What I mean is create your Docker instance so when you create a new one it
has the database already set up. In the same way the Apache config is
already in place and the necessary PHP modules.

**Comment by aracloud** [comment]
but then would I need to run some kind of mysql script that creates the data base while building the container.

**Comment by digininja** [comment]
Yes, create a database that looks like you want, dump it with mysqldump and
then use that to create a new database when you create the database.

Or can't you just have an already populated database in your template? I
don't know much about Docker but I know people ship fully working apps in
containers so they must have their databases already created in those.

**Comment by aracloud** [comment]
I will try the mysqldump way...

> Yes, create a database that looks like you want, dump it with mysqldump and then use that to create a new database when you create the database. Or can't you just have an already populated database in your template? I don't know much about Docker but I know people ship fully working apps in containers so they must have their databases already created in those.

**Comment by aracloud** [comment]
What is the default mysqld user and password? I see the mysqld is running as "mysql" user but what is the password?

**Comment by digininja** [comment]
Why? It shouldn't have one set and you shouldn't need it anyway, you
connect to the database as a mysql user not as a Linux user.

**Comment by aracloud** [comment]
I made it. It runs. Just dumping the "dvwa" DB on a running container and configured the dumped DB into the Container creation code. And it works fine (https://github.com/aracloud/docker-dvwa).

**Comment by digininja** [comment]
That is what I suggested, glad it works.

**Comment by mike-bailey** [comment]
Sounds resolved. Thank you for sharing your solution!
