### ISSUE TITLE
Could not connect to mysql

### ISSUE THREAD

**Issue by BlindMonkeyPL** [ethicalhack3r/DVWA#300]
Hi there. I have problem with DVWA. DVWA server shows message : "Could not connect to MySQL server. Please chcek the conifg file." I have tried to fix it several times but it still does not work. How can i solve this?

**Comment by digininja** [comment]
Like I said in the emails. Give as much info as you can, you don't even say what the operating system is.

This question has been asked plenty of times, have you gone through all of those to see if any of them can answer your question?

Read the questions that have been answered and see how much info they have given.

**Comment by BlindMonkeyPL** [comment]
I saw lots of videos on that but it did not work well for me. I am working on  ubuntu 64 but on windows DVWA works well. About what details you are talking?

**Comment by BlindMonkeyPL** [comment]
Now i have problem even with mysql itself
![VirtualBox_Kali Linux_13_04_2019_20_51_36](https://user-images.githubusercontent.com/49516134/56084071-f5aff700-5e2d-11e9-8ffe-0db03c72a716.png)

**Comment by digininja** [comment]
In which case, I'll redirect you to the Kali and mysql forums to get that
fixed first.

**Comment by BlindMonkeyPL** [comment]
Alright. I have solved the lsb problem with mysql. But i am still stuck with dvwa.
![VirtualBox_KAli Na Debianie_14_04_2019_16_58_38](https://user-images.githubusercontent.com/49516134/56094782-94902e00-5ed6-11e9-8254-61493f946545.png)
![VirtualBox_KAli Na Debianie_14_04_2019_16_59_19](https://user-images.githubusercontent.com/49516134/56094797-b2f62980-5ed6-11e9-9881-2205390ef4d9.png)
Am I doing something wrong?
When I type: service mysql status this appears
![VirtualBox_KAli Na Debianie_14_04_2019_17_03_00](https://user-images.githubusercontent.com/49516134/56094846-2e57db00-5ed7-11e9-8ef3-243c54bebb99.png)

**Comment by digininja** [comment]
Read all the messages on the middle screenshot, all the way down to the bottom of the page.

**Comment by BlindMonkeyPL** [comment]
The only one status in red is Recaptcha. Except this the only other problem that i see is that i use root and it is not gonna working. Did i omit anything? It does not work even if i change the root for something else and it is the same case with Recaptcha.

**Comment by digininja** [comment]
The last message tells you about using root and tells you to read the
readme, did you do that? If so, prove it.

Remember at the start I said to tell us all you'd done, if you don't tell
us you'll end up getting recommendations for stuff you've already done.

**Comment by BlindMonkeyPL** [comment]
Kk here i prove that i changed my username
![VirtualBox_KAli Na Debianie_14_04_2019_17_26_17](https://user-images.githubusercontent.com/49516134/56095182-74fb0480-5eda-11e9-88b6-631a47f9944d.png)
![VirtualBox_KAli Na Debianie_14_04_2019_17_27_18](https://user-images.githubusercontent.com/49516134/56095198-9825b400-5eda-11e9-816f-28e7db08ac04.png)
Yes i have read Readme but i will to it once again.

**Comment by digininja** [comment]
And is there a toor user setup on the database?

Prove you can log into the account from the command line.

**Comment by BlindMonkeyPL** [comment]
So schould i type mysql -u toor -p ?

**Comment by BlindMonkeyPL** [comment]
Alright i did that. Here are results
![VirtualBox_KAli Na Debianie_14_04_2019_17_47_18](https://user-images.githubusercontent.com/49516134/56095447-5ea27800-5edd-11e9-993f-329b7479c0d7.png)

**Comment by digininja** [comment]
And the error message says?

**Comment by BlindMonkeyPL** [comment]
I dont have access

**Comment by digininja** [comment]
So if that user doesn't exist, how do you expect dvwa to connect using it?

**Comment by BlindMonkeyPL** [comment]
I am totaly new to this and i did not know that user like this shall be created. So witch username and password instead of that schould i use?

**Comment by digininja** [comment]
I'm assuming you've not bothered to read the readme yet? The document that
tells you all you need to know and that the error on the page refers you to.

**Comment by BlindMonkeyPL** [comment]
I have tried with admin and password but it does not work to. I will try again with root and toor as it is on my Kali account but later, i have to do something other first. I will be back in 1h.

**Comment by digininja** [comment]
Just read the file, it tells you exactly what you need to do to set up the
database.

**Comment by BlindMonkeyPL** [comment]
Yea you are right i totally missed that point of Readme. So i install "apt-get -y install apache2 mysql-server php php-mysqli php-gd libapache2-mod-php" and i also made next steps: create database, grant all on dvwa.* to dvwa@localhost identified by 'SuperSecretPassword99' ( i used "password")and flush privileges. And what schould i do from this point? It is still unable to connect to database. 
![VirtualBox_KAli Na Debianie_14_04_2019_19_49_32](https://user-images.githubusercontent.com/49516134/56096932-7fbf9480-5eee-11e9-8f5c-1deb4790ed1a.png) 
I can not find anything more in Readme file. I am really stuck here i have no idea what to do.

**Comment by digininja** [comment]
Read the errors that are on the screen, what do they tell you?

**Comment by BlindMonkeyPL** [comment]
That i can't access mysql from this user.

**Comment by digininja** [comment]
So you need to fix that. The example we give in the readme works and there
is plenty of other help out there on adding new users to MySQL or MariaDB.

Add the user, confirm you can connect using it on the command line and
you'll get one step further.

**Comment by BlindMonkeyPL** [comment]
i will find out more about this tomorrow. See you then

**Comment by BlindMonkeyPL** [comment]
OH YEA. I finally did that :D thx for your help digininja ;P

**Comment by digininja** [comment]
A tip for next time then, make sure you read the README files, they are
there to help you and to explain what you need to do to get things working.

Don't forget to close this ticket.

**Comment by BlindMonkeyPL** [comment]
I will keep it in mind. See you
