### ISSUE TITLE
setup problems xampp windows

### ISSUE THREAD

**Issue by nicinu111** [ethicalhack3r/DVWA#301]
is asking to enable allow_url_fopen=on and allow_url_include=on but they are on i use the latest version of xampp

i tryed everything what i can find to fix but is not working, i even reinstall xampp and still the same.

**Comment by digininja** [comment]
Prove they are on by showing the phpinfo output.

**Comment by nicinu111** [comment]
@digininja sry for this late answer https://imgur.com/HAWLlBQ

**Comment by digininja** [comment]
Show the output from phpinfo() not the config file.

**Comment by nicinu111** [comment]
@digininja can you tell my were i find the config file??? you need it from XAMMP or DVWA.

**Comment by mike-bailey** [comment]
digininja is asking you to please upload a php file that simply runs 
```
<?php
phpinfo();
```
and send the output

**Comment by digininja** [comment]
I assume you are installing DVWA to learn about web security so here is
your first challenge. Learn about phpinfo() and then get us the information
I've asked for.

**Comment by nicinu111** [comment]
@mike-bailey were is this php file located???

**Comment by digininja** [comment]
Do some research, you've come here to learn, this is your first lesson

**Comment by mike-bailey** [comment]
Make the PHP file. I gave you the source code. Paste 
```
<?php
phpinfo();
```
Into a PHP file in your web directory and browse to it

**Comment by nicinu111** [comment]
@mike-bailey i done that here it is and tks you communicate better since english in not my main.
![Screenshot_2019-04-29 phpinfo()](https://user-images.githubusercontent.com/49993989/56916689-319bbb00-6ac2-11e9-8f01-e9b1262a1b21.png)

**Comment by nicinu111** [comment]
any update?

**Comment by nicinu111** [comment]
@mike-bailey is any update? has pass 5 days

**Comment by mike-bailey** [comment]
To be clear, on this same server it is saying in the setup that this is not on?

Also these are only required for a subset of vulnerabilities

**Comment by nicinu111** [comment]
@mike-bailey i send a picture were is saying is on in configurations php. i will try and complete remove the app and re-install it to see if is working.

**Comment by nicinu111** [comment]
@mike-bailey i still get the same thing even with the option turn ON by editing to OFF first and next ON
![DVWA2](https://user-images.githubusercontent.com/49993989/57389476-f46eb180-71c2-11e9-9d6b-cd0d85948c06.jpg)

**Comment by nicinu111** [comment]
why is not turning on i have no idea when the server starts

**Comment by nicinu111** [comment]
@mike-bailey i manage to make it work i had to do this shit to work nothing to do with PHP

$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = 'p@ssw0rd';
change to:
$_DVWA[ 'db_server' ]   = 'localhost';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = '';
