### ISSUE TITLE
Fatal error on linux

### ISSUE THREAD

**Issue by aditia13** [ethicalhack3r/DVWA#302]
how to fix this

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/pentest/DVWA-1.9/dvwa/includes/dvwaPage.inc.php:461 Stack trace: #0 /var/www/html/pentest/DVWA-1.9/login.php(8): dvwaDatabaseConnect() #1 {main} thrown in /var/www/html/pentest/DVWA-1.9/dvwa/includes/dvwaPage.inc.php on line 461

**Comment by digininja** [comment]
Use the latest version from GitHub, that will fix it.
