### ISSUE TITLE
DVWA setup.php is not displaying properly

### ISSUE THREAD

**Issue by but19pl** [ethicalhack3r/DVWA#303]
Hi, I have problem with DVWA. Dunno why, but it appears that my computer doesn't read the code correctly.
https://imgur.com/a/4vNnBxx

I have tried using PHP7.3 and PHP7.2 but both weren't solving the problem, so I suppose I don't understand the problem at all.
 
I will be grateful for any help :)

With regards

**Comment by digininja** [comment]
You've not got PHP enabled on the server. You may have installed it, but
you haven't turned it on.

**Comment by but19pl** [comment]
This is weird, my localhost page is (and was) working just fine, but localhost/dvwa/setup.php and login.php etc keep showing background PHP codes like before. Have a look into my terminal history:
$ sudo service apache2 start
$ sudo service mysql start
$ sudo a2enmod php7.3
$ sudo service apache2 restart
//still localhost/dvwa/setup.php isn't working the right way, then I'm trying with PHP7.2
$ sudo a2dismod php7.3
$ sudo a2enmod php7.2
$ sudo service apache2 restart
// still nothing ;_;

**Comment by digininja** [comment]
You show the commands your ran but not the output from them, did you read
the output? Were there errors?

You haven't told us what OS you are running but I'm fairly sure most won't
let you have two versions of PHP installed side by side like you are
describing.

**Comment by but19pl** [comment]
Good point lol I suppose there notifications aren't errors :)
https://imgur.com/a/gj0YxDL
Should I uninstall PHP7.2 then?

**Comment by digininja** [comment]
The quality of the screenshot isn't good enough to read, can you post the
text instead.

I'd pick a version of PHP and stick with that. If you start trying to mix
versions you'll more than likely get problems. DVWA works with all versions
7 and upwards as far as I know.

**Comment by but19pl** [comment]
Terminals output: 
root@cesarz:~# uname -a
Linux cesarz 4.19.0-kali3-686-pae #1 SMP Debian 4.19.20-1kali1 (2019-02-14) i686 GNU/Linux
root@cesarz:~# sudo service apache2 start
root@cesarz:~# sudo service mysql start
root@cesarz:~# sudo a2enmod php7.3
Considering dependency mpm_prefork for php7.3:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php7.3:
Enabling module php7.3.
To activate the new configuration, you need to run:
  systemctl restart apache2
root@cesarz:~# sudo service apache2 restart

PHP7.2 and 7.3 were on this system from the very beggining as far as I know, but maybe I'm mistaken

**Comment by digininja** [comment]
Uninstall all PHP and start again, I reckon you've got some type of
conflict as that looks ok.

**Comment by but19pl** [comment]
I have removed php7.2 and 7.3:
sudo apt-get purge php7.*
then installed:
sudo apt-get install php7.3
no errors, I have restarted my computer, then started my server with same commands I mentioned before, yet, this problem still remains... 

Login.php shows: Need to run 'setup.php'." ); dvwaRedirect( DVWA_WEB_PAGE_TO_ROOT . 'setup.php' ); } $query = "SELECT * FROM `users` WHERE user='$user' AND password='$pass';"; $result = @mysqli_query($GLOBALS["___mysqli_ston"], $query ) or die( '

' . ((is_object($GLOBALS["___mysqli_ston"])) ? mysqli_error($GLOBALS["___mysqli_ston"]) : (($___mysqli_res = mysqli_connect_error()) ? $___mysqli_res : false)) . '.
Try installing again. // <--this is button, not message

I don't know if this will help finding solution, but I will place this piece of the code here

**Comment by digininja** [comment]
No idea what you've done wrong, but I've just done a fresh install, ran
only these commands and got a working DVWA:

```
    1  apt-get install php7.3 php7.3-mysql apache2 vim
    2  apt-get install git
    3  cd /var/www/html/
    4  ls
    5  git clone https://github.com/ethicalhack3r/DVWA.git
    6  apachectl start
    7  cd DVWA/
    8  ls
    9  cp config/config.inc.php.dist config/config.inc.php
   10  history
```

Some configuration still needs doing but PHP is working fine and the setup
page is shown as expected.

**Comment by but19pl** [comment]
Yeah thanks :) it looks good now, but still I have problems with database. I will do my best to fix it, will inform you soon if I encounter some problems.

**Comment by digininja** [comment]
Can guarantee you that the solution to your database problem will have
already been answered many times in these issues.

You will probably be trying to tell PHP to use the root user to connect to
the database which isn't allowed.

**Comment by but19pl** [comment]
I have finally solved my issue. 

I'm Kali linux user, so I have MariaDB, there is my solution for others with similar problems:
// lol just read README.md carefully xD

$ sudo mysql -u root
> create database dvwa;
> grant all on dvwa.* to dvwa@localhost identified by 'SuperSecretPassword99';
> flush privileges;

Now you have to update DVWA/config/config.inc.php, so the following lines have to look like:

$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'dvwa';
$_DVWA[ 'db_password' ] = 'SuperSecretPassword99';

I'm very grateful for digininja for his time and help :)

Closing

**Comment by ADK03** [comment]
thank you so much it worked perfectly

**Comment by ybigsur5** [comment]
Thank you @EmperorTransisthor ! I am Kali user too and this helps tremendously.
