### ISSUE TITLE
dvwa doesn't work correctly

### ISSUE THREAD

**Issue by mohammed1997010** [ethicalhack3r/DVWA#304]
hello friends 
I have downloaded dvwa on my parrot os and I have done all the steps correctly 
but it's still not working...
I can't get the login page
please I need help....
![Screenshot at 2019-05-12 00-33-07](https://user-images.githubusercontent.com/47889454/57575128-08105700-7413-11e9-9fb9-747528376a5c.png)

note:
I'm using Parrot security OS 
my php version is 7.3
and I have installed apache2 and mysql server (MariaDB)

**Comment by digininja** [comment]
Looks to me like you've not got PHP enabled, check that.

**Comment by mohammed1997010** [comment]
Sorry but how to enable PHP ?
Is there a config file I have to edit it?

**Comment by digininja** [comment]
Do some googling, there are loads of tutorials on getting a LAMP setup
working. Once you have that, then come back to DVWA.

**Comment by mohammed1997010** [comment]
well...
I tried to do the following commands after a lot of search about 'enable PHP' : 

`sudo apt-get update`
`sudo apt-get install apache2`
`sudo apt-get install mysql-server`
`sudo mysql_install_db`
`sudo mysql_secure_installation`
`sudo apt-get install php5 libapache2-mod-php5 php5-mcrypt`

and I edited the dir.conf and I moved the PHP index file after the DirectoryIndex and to be the dir.conf like this:

`<IfModule mod_dir.c>
    DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
</IfModule>
`
then I created a new user in mysql using the following commands:

`create user dvwa;`
`grant all on dvwa.* to dvwa@localhost identified by 'toor' ; `
`flush privileges;`
`GRANT ALL ON dvwa.*  To 'dvwa'@'%';`
`FLUSH PRIVILEGES;`

and then I restarted apache and mysql server  and tried to come back to dvwa but the problem still...

**Comment by digininja** [comment]
First, if you are running PHP 5 then you'll have problems, it hasn't been
supported for quite a while.

You showed what you installed but didn't show whether PHP was actually
running. Look on the puppy forums, talk to them about getting it working,
confirm it, then move back to DVWA.
