### ISSUE TITLE
issues in and after installation 

### ISSUE THREAD

**Issue by Penmedad** [ethicalhack3r/DVWA#306]
hello,

I tried both ways of installing  DVWA on my kali (iso and zip file) and in both ways have some difficulty:
1- zip (DVWA Development Source): i successfully installed and were able to login to the environment.
issue: 
     - i can not scan DVWA with Openvas, i guess maybe because both are an local-host!!!
     - after trying the iso way of installing DVWA, i was not able to reach this DVWA anymore 

2-  iso 
    issue:
       - after providing user and pass I'm getting this error :"Table 'dvwa.users' doesn't exist"  

could you please help and guide me to solve this issues?!
I look forward to your reply.
thanks in advance :)

**Comment by digininja** [comment]
The iso is ancient, don't use it.

As for why openvas isn't working, no idea without a lot more technical
details but if you have configured your web server to only listen on
localhost and you are sacanning it from a different box then it won't see
it. Even if it does see it, it won't see any of the DVWA challenges as they
are behind a login page and it won't have the session key.

**Comment by Penmedad** [comment]
Thanks for reply.
Ok then forget about iso, but I still have issue with the first installation, now I see the page like the screenshot, which i attached below!!! have no idea why?! 

Also, how should i configure the web server then?! (to not only listen to local-host!)
also do you mean that scanning the DVWA with Openvas isn't good idea and I should somehow scan the after the login page?!! 
my apology if I'm wrong, I'm new and just trying to learn .
thanks again 
![Capture](https://user-images.githubusercontent.com/50788737/58085180-9b117400-7bff-11e9-8f79-1ebe3a1de5d2.PNG)

**Comment by digininja** [comment]
you've not got PHP enabled on the web server.

**Comment by Penmedad** [comment]
Ooops! okay, it's wired was working before

**Comment by Penmedad** [comment]
hello again,

i enabled PhP but still having the same problem, could you please assist?!
![php](https://user-images.githubusercontent.com/50788737/58378739-2f068580-7fdc-11e9-87cf-9e7bfa8c88a6.PNG)

**Comment by digininja** [comment]
Same problem means you still haven't got PHP enabled.

**Comment by Penmedad** [comment]
so what do you suggest, have you seen the screenshot ?!
 
![php5-6](https://user-images.githubusercontent.com/50788737/58378765-bc49da00-7fdc-11e9-989b-1c003367fccb.PNG)

**Comment by digininja** [comment]
You need to install PHP. How you do that depends on your system. Do some
searching and you should be and to find out how.

**Comment by Penmedad** [comment]
solved thanks.

**Comment by digininja** [comment]
Remember to close the ticket then.

**Comment by kuzuri-03** [comment]
> solved thanks.

How did uhh do it ???
can uh please help me !
