### ISSUE TITLE
DVWA installation disapeare after each restart

### ISSUE THREAD

**Issue by Penmedad** [ethicalhack3r/DVWA#307]
can someone please help me!!! 
I have latest version of Kali on latest version on virtual box, recently tried to install DVWA, but the issue is after each restart all modifies on installation, php and everything disappeared!!!
I also like to add that I installed other application like Openvas , or added repository and guest addition, which all still there and doesn't disappeared!!
so I'm confuse, how do i solve this issue?! 

thanks in advance

**Comment by digininja** [comment]
Sound like you are having a problem with using VirtualBox. This isn't a
DVWA issue.
