### ISSUE TITLE
Could not connect to the MySQL service. Please check the config file.

### ISSUE THREAD

**Issue by GusNa** [ethicalhack3r/DVWA#318]
I've created a new user on the mysql server and their password is blank. I can log in as them with no password but dvwa can't ever seem to see the mysql service. My config file appears to be correct.

**Comment by digininja** [comment]
Get screenshots of you connecting from the command line with the user and
blank password and the section of the config file with the creds in it.

**Comment by zhuhanqun-git** [comment]
Check the README.md

**Comment by zhuhanqun-git** [comment]
Note, if you are using MariaDB rather than MySQL (MariaDB is default in Kali), then you can't use the database root user, you must create a new database user. To do this, connect to the database as the root user then use the following commands:

```mysql
mysql> create database dvwa;
Query OK, 1 row affected (0.00 sec)

mysql> grant all on dvwa.* to dvwa@localhost identified by 'SuperSecretPassword99';
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)
```

You will then need to update the config file, the new entries will look like this:

```php
$_DVWA[ 'db_user' ] = 'dvwa';
$_DVWA[ 'db_password' ] = 'SuperSecretPassword99';
$_DVWA[ 'db_database' ] = 'dvwa';
```

**Comment by koaks** [comment]
Hello, I've tried this too, so many times and I still cannot create my database. Please help!

**Comment by digininja** [comment]
Get a screenshot of the config file and you connecting to the database
using the creeds you have specified.

Loads of instructions on how to do this in closed tickets.

**Comment by darlene88** [comment]
Hi,

Here's a screenshot like you requested:

[image: image.png]
I have tried every fix suggested, change mysql password, allow and flush
privileges, etc.  I am new to all of this but have followed the tutorials
precisely.  Spent hours installing reinstalling, creating new vm's etc.
All great practice, but I need this to work asap.

Many thanks,

Kate

**Comment by digininja** [comment]
Try again on the screenshot. Need the creds and you contacting to the
database on the command line using them.

**Comment by darlene88** [comment]
Screenshot may or may not be showing up, so I also attached them here.  Do
you need the ssh creds too?

**Comment by digininja** [comment]
Still no screenshots, either inline or linked to.

I want to see you using -p to provide the password on the command line with it working (i.e. not an Access denied error), and one of the config file.

**Comment by darlene88** [comment]
<img width="1072" alt="Screen Shot 2020-04-05 at 3 28 54 PM" src="https://user-images.githubusercontent.com/55209009/78508079-334e1400-7752-11ea-829a-5b988043fbaf.png">
can you see this?  when i go to preview, i see a 404 error.  please advise if you are unable to see my screen shots or attachments

**Comment by digininja** [comment]
Yes, what database server are you using, MariaDB or MySQL?

**Comment by darlene88** [comment]
I'm pretty sure I selected MySQL.

**Comment by digininja** [comment]
Please check, it is very important. See the comment straight about where
you put the creds in

**Comment by darlene88** [comment]
<img width="1171" alt="Screen Shot 2020-04-05 at 3 42 17 PM" src="https://user-images.githubusercontent.com/55209009/78508334-131f5480-7754-11ea-8b9a-7e70d9098325.png">

**Comment by digininja** [comment]
you see all those "Access denied" errors, that means your login failed.

Read the spec for logging in on the command line, and then use it to
successfully log in. To the point you can select users from the users table.

**Comment by darlene88** [comment]
I'm sorry, but could you tell me the exact next step.  I've gotten so lost going down the rabbit holes.  log in to what on the command line?  mysql?

**Comment by digininja** [comment]
Google

mysql command line connect

and look for the MySQL docs.

If you want to learn app testing, you need to be able to do this kind of
thing on the command line to understand how the stuff under what you are
testing works.

**Comment by darlene88** [comment]
That's not what I asked.  I can Google mysql command lines.  I just don't know exactly where I am supposed be logging into next.  Am I supposed to change the privileges again.  I have already done that.
I did: sudo mysql -uroot.
then mysql> show databases;
and got the following.


<img width="537" alt="Screen Shot 2020-04-05 at 4 16 12 PM" src="https://user-images.githubusercontent.com/55209009/78508998-de61cc00-7758-11ea-9faf-566f35ef4af5.png">

I have been trouble shooting this for far too long and need to know what the problem is especially since I have gotten this far. I have Googled, found, and done every fix suggested but nothing is working.

**Comment by digininja** [comment]
What you have just shown is that the root user doesn't need a password to
log in, but in the config file you have specified a password. That isn't
going to work.

The next thing to look at, when you log in, what database type does it say,
Mariadb or mysql? If it is mariadb then as the content in the config file
says, you can't use the root user.

**Comment by darlene88** [comment]
Sorry for the confusion, I posted a screenshot earlier showing that it's mysql.  mysql version 14.14

**Comment by digininja** [comment]
That is the command line tool not the server. Connect to the server and
check that version that is.

https://www.liquidweb.com/kb/how-to-check-the-mysql-version/

**Comment by darlene88** [comment]
I'm still seeing mysql, not mariadb.  Please tell me how to proceed.  I
need help getting this last part of dvwa setup.  If you cannot help me,
please ask someone who is willing to help.

**Comment by digininja** [comment]
Send a screenshot.

If it really is MySQL, then set the password in the config file to match the one you use to connect on the command line.

**Comment by darlene88** [comment]
<img width="1076" alt="Screen Shot 2020-04-05 at 5 10 07 PM" src="https://user-images.githubusercontent.com/55209009/78510065-98106b00-7760-11ea-880f-d7e4be0d6bd4.png">

**Comment by digininja** [comment]
If you want the easy and quick fix, remove MySQL, install MariaDB and just use that. It works and it is what we can easily support.

There are issues with MySQL and the password config. There is a closed issue in here somewhere which explains fixing it, but you'll have to dig through to find it.

**Comment by darlene88** [comment]
So, I have mariadb now installed, but I'm still getting the error.  Another note, I am ssh'ing to my ubuntu box.  What else can i try to get into the dvwa database?

**Comment by digininja** [comment]
back to the beginning for debugging then;

- Make sure you have read the note about not being able to run as the root database user.
- Show me a screenshot of the config file
- Show you connecting to the database on the command line using -p to pass the password in on the command line. Make sure this actually connects to the database and does not give an access denied error
- Once connected, show the result of running

`select @@version`

**Comment by darlene88** [comment]
<img width="1164" alt="Screen Shot 2020-04-07 at 3 40 26 PM" src="https://user-images.githubusercontent.com/55209009/78712277-60cbc680-78e6-11ea-8b6c-d5935420e07c.png">
<img width="929" alt="Screen Shot 2020-04-07 at 3 38 50 PM" src="https://user-images.githubusercontent.com/55209009/78712307-6f19e280-78e6-11ea-9c88-976dd644341a.png">
<img width="790" alt="Screen Shot 2020-04-07 at 4 17 37 PM" src="https://user-images.githubusercontent.com/55209009/78715393-5c55dc80-78eb-11ea-8b2d-e9ab19589b31.png">

**Comment by darlene88** [comment]
<img width="1175" alt="Screen Shot 2020-04-07 at 4 25 06 PM" src="https://user-images.githubusercontent.com/55209009/78716119-64624c00-78ec-11ea-8672-c8d7eee51d6a.png">
This is the correct ip, not the the first post.

**Comment by digininja** [comment]
Please send a screenshot of your connecting to the database using the
credentials in the config file using the -p parameter to pass the password
on the command line.

**Comment by darlene88** [comment]
<img width="858" alt="Screen Shot 2020-04-07 at 4 32 09 PM" src="https://user-images.githubusercontent.com/55209009/78716741-77295080-78ed-11ea-94fa-5aa19c341120.png">

**Comment by digininja** [comment]
No, that is connecting as root, entering a command line argument and
getting an error message.

Read your screen before posting stuff, will save us both time.

**Comment by darlene88** [comment]
Not sure why the rudeness is necessary.  But thanks, I'm in for now.

**Comment by mike-bailey** [comment]
There's now three people on this ticket and it's getting heated so I'm both going to close and lock. If anyone else is having this issue, please consider checking what worked for people and what was asked and answered in here.
