### ISSUE TITLE
dvwa works well on regular kali but for some reason not on kali lite

### ISSUE THREAD

**Issue by alonzo1415** [ethicalhack3r/DVWA#320]
so i have 'git clone' the file many times on my parrot os, kali regular and Ubuntu os and it worked flawlessly. however i was running low on ram and decided to run a copy of Kali lite on virtual-box, now for some reason i cannot get dvwa to display as it should. 

1) after placing dvwa folder in /var/www/html/ i edited the config file to '.php' and not '.dist'

2)then check that i had php version 5.6, apache2 and (MySQL which i got by installing 'maria-db')

3)used mysql to create new user to satisfy the readme.txt about the need to change because i was using maria-db instead of mysql.

Now after all of that bear in mind that i have done this multiple time over the last couple of months i am only able to get the setup.php to display and clicking on create/database does nothing but take me to a blank screen with address 127.0.0.1/dvwa/setup.php#

I am really at my wits end here, i have read many topics about this issue but so far none have give any help towards my situation any help would be much appreciated

**Comment by digininja** [comment]
What does the Apache error log say?

**Comment by alonzo1415** [comment]
there you go... thank you

[Fri Sep 27 01:02:17.133689 2019] [:error] [pid 2829] [client ::1:36294] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Fri Sep 27 01:24:41.397900 2019] [:error] [pid 2833] [client ::1:36316] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Fri Sep 27 01:25:27.744570 2019] [mpm_prefork:notice] [pid 2828] AH00169: caught SIGTERM, shutting down
[Fri Sep 27 01:55:15.007853 2019] [mpm_prefork:notice] [pid 3488] AH00163: Apache/2.4.41 (Debian) configured -- resuming normal operations
[Fri Sep 27 01:55:15.008094 2019] [core:notice] [pid 3488] AH00094: Command line: '/usr/sbin/apache2'
[Fri Sep 27 01:57:05.920991 2019] [:error] [pid 3491] [client ::1:36508] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://localhost/dvwa/setup.php
[Fri Sep 27 10:16:55.159564 2019] [:error] [pid 3490] [client 127.0.0.1:43984] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://127.0.0.1/dvwa/setup.php
[Fri Sep 27 11:11:24.730255 2019] [mpm_prefork:notice] [pid 3488] AH00169: caught SIGTERM, shutting down

**Comment by digininja** [comment]
Nothing obvious there. Tail the log and then click the button and paste
whatever is shown at that time. Just the new stuff

**Comment by alonzo1415** [comment]
Now kali lite does not come with php apache2 nor mysql installed so i had to install manually if that helps

**Comment by digininja** [comment]
Why did you go with PHP 5.x? It isn't supported any more.

Shouldn't make a difference though. Send that bit of the log

**Comment by alonzo1415** [comment]
looks like the same but here you go

[Fri Sep 27 10:16:55.159564 2019] [:error] [pid 3490] [client 127.0.0.1:43984] PHP Notice:  Constant DVWA_WEB_PAGE_TO_ROOT already defined in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://127.0.0.1/dvwa/setup.php
[Fri Sep 27 11:11:24.730255 2019] [mpm_prefork:notice] [pid 3488] AH00169: caught SIGTERM, shutting down

**Comment by digininja** [comment]
Can't see anything obvious, will see if I get that warning later on.

You sure you cloned the latest from the repo?

**Comment by alonzo1415** [comment]
Its the one I always use 
https://github.com/ethicalhack3r/DVWA.git

Only difference is I never had to install the others(php, mysql etc) as they came standard on the other distros

I am attempting it on a regular kali on vb to see what happens

**Comment by digininja** [comment]
I've just checked with the latest version and I'm not seeing those notices so looks like we are running different versions.

Rather than using PHP 5.x, setup with 7.x and give that a try instead.

**Comment by alonzo1415** [comment]
Ok I will give it a try and get back to you

**Comment by alonzo1415** [comment]
So i have updated the php to 7x

root@kaliOS19:~# php -v
PHP 7.3.9-1+0~20190902.44+debian9~1.gbpf8534c (cli) (built: Sep  2 2019 13:31:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+0~20190902.44+debian9~1.gbpf8534c, Copyright (c) 1999-2018, by Zend Technologies

I also restart mysql and apache 

A little more info

root@kaliOS19:~# uname -a
Linux kaliOS19 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux

**Comment by alonzo1415** [comment]
So i did change the version but its the same results

**Comment by digininja** [comment]
Show that your database user can log into the database on the command line. Something like:

```
mysql -u myuser -pMyPassword
```

Notice there is no space after the -p

**Comment by alonzo1415** [comment]
root@kaliOS19:~# mysql -u myuser -pMyPassword
ERROR 1045 (28000): Access denied for user 'myuser'@'localhost' (using password: YES)

**Comment by digininja** [comment]
There is your problem then, fix that.

**Comment by alonzo1415** [comment]
Before i go ahead with this, I did create another user before called root2 under mysql and gave it all the privileges of root.
Maybe that's what caused the situation?

**Comment by digininja** [comment]
No, if the database user can't connect to the database then that is your
problem.

**Comment by alonzo1415** [comment]
Will let you know. Thank you

**Comment by alonzo1415** [comment]
root@kaliOS19:~# mysql -u myuser -pMyPassword
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 38
Server version: 10.3.18-MariaDB-1 Debian buildd-unstable

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit;
 
Now it did allow access but still no results from web browser,  I am still getting a blank screen.
 Before you said we had different version, were you referring to kali or php?

**Comment by digininja** [comment]
Show a screenshot of that command working and you config file.

And for versions, I don't get those notices in the log file you do so I'm
guessing I'm running a different version of the code.

**Comment by alonzo1415** [comment]
you are referring to the 'mysql -u myuser -pMyPassword' command?

**Comment by alonzo1415** [comment]
I am actually heading off to work but I will be checking back later to continue for sure.

(1)Here is the config file

<?php

# If you are having problems connecting to the MySQL database and all of the variables below are correct
# try changing the 'db_server' variable from localhost to 127.0.0.1. Fixes a problem due to sockets.
#   Thanks to @digininja for the fix.

# Database management system to use
$DBMS = 'MySQL';
#$DBMS = 'PGSQL'; // Currently disabled

# Database variables
#   WARNING: The database specified under db_database WILL BE ENTIRELY DELETED during setup.
#   Please use a database dedicated to DVWA.
#
# If you are using MariaDB then you cannot use root, you must use create a dedicated DVWA user.
#   See README.md for more information on this.
$_DVWA = array();
$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = 'p@ssw0rd';

# Only used with PostgreSQL/PGSQL database selection.
$_DVWA[ 'db_port '] = '5432';

# ReCAPTCHA settings
#   Used for the 'Insecure CAPTCHA' module
#   You'll need to generate your own keys at: https://www.google.com/recaptcha/admin
$_DVWA[ 'recaptcha_public_key' ]  = '';
$_DVWA[ 'recaptcha_private_key' ] = '';

# Default security level
#   Default value for the secuirty level with each session.
#   The default is 'impossible'. You may wish to set this to either 'low', 'medium', 'high' or impossible'.
$_DVWA[ 'default_security_level' ] = 'impossible';

# Default PHPIDS status
#   PHPIDS status with each session.
#   The default is 'disabled'. You can set this to be either 'enabled' or 'disabled'.
$_DVWA[ 'default_phpids_level' ] = 'disabled';

# Verbose PHPIDS messages
#   Enabling this will show why the WAF blocked the request on the blocked request.
#   The default is 'disabled'. You can set this to be either 'true' or 'false'.
$_DVWA[ 'default_phpids_verbose' ] = 'false';

?>

(2) Not sure but i think this is the command you want to see

root@kaliOS19:~# mysql -u myuser -pMyPassword
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 39
Server version: 10.3.18-MariaDB-1 Debian buildd-unstable

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>

**Comment by digininja** [comment]
yes, a screenshot of it working and of the config file

**Comment by digininja** [comment]
you've not done anything for 1 and can I get screenshots not copy/paste

**Comment by alonzo1415** [comment]
<?php

# If you are having problems connecting to the MySQL database and all of the variables below are correct
# try changing the 'db_server' variable from localhost to 127.0.0.1. Fixes a problem due to sockets.
#   Thanks to @digininja for the fix.

# Database management system to use
$DBMS = 'MySQL';
#$DBMS = 'PGSQL'; // Currently disabled

# Database variables
#   WARNING: The database specified under db_database WILL BE ENTIRELY DELETED during setup.
#   Please use a database dedicated to DVWA.
#
# If you are using MariaDB then you cannot use root, you must use create a dedicated DVWA user.
#   See README.md for more information on this.
$_DVWA = array();
$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = 'p@ssw0rd';

# Only used with PostgreSQL/PGSQL database selection.
$_DVWA[ 'db_port '] = '5432';

**Comment by alonzo1415** [comment]
Sorry kali lite did not have a screenshot apt installed.
I am actually heading off to work but will send the info you need and I will check back later

**Comment by digininja** [comment]
I just installed a VM with Kali Light then did this:

```
apt-get install php  apache2 mariadb-server mariadb-client git php-mysql
service apache2 start
service mysql start
```

Git cloned the repo, followed the database instructions in the README and it worked fine. You've done something wrong somewhere.

And to take screenshots, see this [Taking Screenshots](https://ubuntuforums.org/showthread.php?t=1716649)

**Comment by alonzo1415** [comment]
Okay... I think I'm on my way now. Thank you very much. I do believe it was that version of php that I had not sure but i am getting it to work now. Here are a couple of screenshots not cut/paste.

![screenshot1](https://user-images.githubusercontent.com/55891232/65835242-d9a3f300-e2b1-11e9-8870-f0959ad32101.png)
![screenshot2](https://user-images.githubusercontent.com/55891232/65835257-107a0900-e2b2-11e9-8ed8-b060664ca2be.png)
![screenshot3](https://user-images.githubusercontent.com/55891232/65835261-153ebd00-e2b2-11e9-94b8-53f3a210ccb3.png)

**Comment by alonzo1415** [comment]
thank u.

**Comment by digininja** [comment]
Looks like you fixed something, glad it's working now.

Remember to close the issue.
