### ISSUE TITLE
Could not connect to the MySQL service. 

### ISSUE THREAD

**Issue by sunozil** [ethicalhack3r/DVWA#323]
![image](https://user-images.githubusercontent.com/37857351/66318651-4d976880-e94e-11e9-9525-b4696c573996.png)
![image](https://user-images.githubusercontent.com/37857351/66318722-6acc3700-e94e-11e9-99a0-2bbe93315fb9.png)
![image](https://user-images.githubusercontent.com/37857351/66318938-d6160900-e94e-11e9-94b2-d92633946e09.png)
![image](https://user-images.githubusercontent.com/37857351/66319738-36597a80-e950-11e9-8fc7-c876625c30e7.png)
modifyed the parameters in the PHP.ini file, allow_url_include is in effect, PHP module gd is still missing?

**Comment by sunozil** [comment]
My system is docker using ubuntu, dvwa is installed in apache2

**Comment by digininja** [comment]
what is your problem, mysql or gd?

**Comment by sunozil** [comment]
is gd missing causing create database to fail？

**Comment by sunozil** [comment]
modifyed the parameters in the PHP.ini file, allow_url_include is in effect, PHP module gd is still missing?

**Comment by digininja** [comment]
Do some searching on what gd and displaying errors means.

Read the closed issues, the thing that you are probably asking has been answered many many times.
