### ISSUE TITLE
how can i fix that pls

### ISSUE THREAD

**Issue by Paramedo** [ethicalhack3r/DVWA#327]
Your database user is root, if you are using MariaDB, this will not work, please read the README.md file.

**Comment by mike-bailey** [comment]
Did you read README.md? Did it work?

**Comment by Paramedo** [comment]
if you're having this problem just follow this steps from the readme file:
Note, if you are using MariaDB rather than MySQL (MariaDB is default in Kali), then you can't use the database root user, you must create a new database user. To do this, connect to the database as the root user then use the following commands:

```mysql
mysql> create database dvwa;
Query OK, 1 row affected (0.00 sec)

mysql> grant all on dvwa.* to dvwa@localhost identified by 'SuperSecretPassword99';
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)
```

You will then need to update the config file, the new entries will look like this:

```php
$_DVWA[ 'db_user' ] = 'dvwa';
$_DVWA[ 'db_password' ] = 'SuperSecretPassword99';
$_DVWA[ 'db_database' ] = 'dvwa';
```

**Comment by Paramedo** [comment]
yeah thanks alot bruh :).

**Comment by mike-bailey** [comment]
No problem - so fixed? Lol

**Comment by Paramedo** [comment]
can you recommend me some couses about learning the basics and performing basic attacks on DVWA ?

**Comment by mike-bailey** [comment]
I cannot personally. Maybe someone else does but I just read OWASP mostly.

**Comment by Paramedo** [comment]
well thanks alot for your help :)
