### ISSUE TITLE
File Inclusion

### ISSUE THREAD

**Issue by sunozil** [ethicalhack3r/DVWA#329]
![image](https://user-images.githubusercontent.com/37857351/69112723-f8598580-0abb-11ea-99a7-64bd02411e0c.png)

![image](https://user-images.githubusercontent.com/37857351/69112773-1921db00-0abc-11ea-8306-90af53331ec1.png)

Security Level: low

I uploaded an image (including a Trojan), why does it not work in file inclusion?

**Comment by digininja** [comment]
You are going to need to give us a lot more to work on beyond "it doesn't
work".

**Comment by sunozil** [comment]
Using page=/etc/shadow, the page does not have any prompt statements.

**Comment by digininja** [comment]
Keep going, more information...

**Comment by sunozil** [comment]
PHP Version 7.2.19  Apach2   ubuntu0.18.04.2
allow_url_fopen = On
allow_url_include = On

**Comment by sunozil** [comment]
Security Level: low

**Comment by digininja** [comment]
And what is the content of the file you are uploading?

What are you seeing?

What are your expecting to see?

What process are you following?
