### ISSUE TITLE
Can admin's password be changed on DVWA?

### ISSUE THREAD

**Issue by Hazemwaddah** [ethicalhack3r/DVWA#331]
Hello All, I have installed dvwa on a VM machine and I was wondering can be able to change the login 's password?
I'm using Ubuntu 18.04 - php 7.2.

I have looked through the file setup.php and changed the password but nothing happened: 
![image](https://user-images.githubusercontent.com/47379135/69491558-80b29e80-0e9f-11ea-851a-34ae90f42452.png)

I've also checked the line above which said that I should be aware of the credentials in the config file "config.inc.php" , but I cannot find any credentials inside except for MariaDB. However, I'm using MySQL not MariaDB.

Therefore, my question is there any way I can change the password of "admin user" in dvwa database?

Thanks.

**Comment by digininja** [comment]
You can use the CSRF page to change your password:

/vulnerabilities/csrf/

**Comment by digininja** [comment]
The thing you have circled is static copy in some HTML. I strongly suggest you do some reading around basic web technologies before trying to get into DVWA, it will make progress through it much easier.

**Comment by Hazemwaddah** [comment]
I've changed the password. Thank you digininja.
