### ISSUE TITLE
j'ai des biscoto                                                                                                                                                                                                               .

### ISSUE THREAD

**Issue by leolfbar** [ethicalhack3r/DVWA#337]

**Comment by digininja** [comment]
Not very informative...

Try English and tell us what you want, or stop wasting our time.

**Comment by mike-bailey** [comment]
@digininja I get the sentiment, but at the same time let's try to not lash out at people filing...?

**Comment by digininja** [comment]
For those who don't speak French...

it works in.

dsl

please don't come

I am armed

I have cookies
