### ISSUE TITLE
ERROR 403

### ISSUE THREAD

**Issue by ergohestia** [ethicalhack3r/DVWA#338]
Hello. I have a problem running the application. After uploading files to the htdocs folder in XAMPP it shows an error:
Forbidden access!

You do not have access to the requested object. It is protected against reading or cannot be read by the server.

If you think this is a server error, contact your administrator.
Error 403
localhost
Apache / 2.4.41 (Unix) OpenSSL / 1.1.1d PHP / 7.3.11 mod_perl / 2.0.8-dev Perl / v5.16.3

What may be the problem?

**Comment by digininja** [comment]
What directory is your XAMPP document root is pointing at?

What is the content of that directory?

What are the permissions on that directory?

What do the web logs says?

**Comment by ergohestia** [comment]
Working! Helped change permissions in XAMPP. Thanks for the help.

**Comment by digininja** [comment]
Good.

Remember to close the issue.

**Comment by ergohestia** [comment]
comleted
