### ISSUE TITLE
Could not drop existing database SQL: Access denied for user 'bella'@'127.0.0.1' to database 'dvwa'

### ISSUE THREAD

**Issue by Chitra-94** [ethicalhack3r/DVWA#339]

**Comment by digininja** [comment]
Make sure you've got the username and password in the config file correct. To check this, make sure you can connect to the database from the command line using them.

**Comment by Chitra-94** [comment]
![Screenshot 2020-01-27 05:19:54](https://user-images.githubusercontent.com/57666467/73166986-fe27a480-40c4-11ea-9cf6-c4a094aff10f.png)
![Screenshot_2020-01-27_05-20-24](https://user-images.githubusercontent.com/57666467/73166999-054eb280-40c5-11ea-9187-2563ad050405.png)

**Comment by Chitra-94** [comment]
I can connect to database as root user, also, if i try to login as 'bella'(non-root) without giving password(just by double-clicking enter), am able to login to DB. the issue is coming if i give the password which I'd set

**Comment by digininja** [comment]
If you can't log in using that password on the command line, then that isn't the password for that user.

If you can get in without providing a password, then there is no password set on the account.

Go back in as the root user and set the password. Make sure you flush privileges, then come out and make sure you can get in as the user using the password. If you can't do it on the command line, then you won't be able to do it through DVWA.

**Comment by Chitra-94** [comment]
still could not login with different password.. But I created a new user and flush privileges and now DVWA is opening in my localhost.. Thanks!!

**Comment by digininja** [comment]
Glad it's working. Please close the issue.
