### ISSUE TITLE
File Upload Won't work

### ISSUE THREAD

**Issue by devporter007** [ethicalhack3r/DVWA#347]
I am running dvwa on metasploitable 2 vm and not able to expoit file upload vulnerability as when i try to upload anything like images or anything else i face the same error i.e "Your image was not uploaded.
". What should i do now

**Comment by digininja** [comment]
Send us more information.

What do the error logs say.

Is the app setup correctly?

Does the setup page say that there is write access to the uploads directory?

**Comment by devporter007** [comment]
Looks like there was some problems with permissions of directories which now i have fixed, btw thx for  quick response...

**Comment by Gohanckz** [comment]
@devporter007  
I have the same problem, can you tell me how do I give permissions to load directories?
