### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /var/www/dvwa2/vulnerabilities/sqli_blind/index.php on line 65

### ISSUE THREAD

**Issue by berenkg** [ethicalhack3r/DVWA#351]
Hello, I have detected some mistakes on the following pages. As an example, when I get to the '**vulnerabilities / sqli_blind /**' page, I get an error like the one below. '
**Parse error: syntax error, unexpected '[' in /var/www/dvwa2/vulnerabilities/sqli_blind/index.php on line 65**
'Errors like this are organized by compile-time error and the following code changes.
Pages with errors:
- / vulnerabilities / sqli_blind / ==> at all levels.
- vulnerabilities / sqli / ==> only at medium level.

Php code to be made to index.php page for / vulnerabilities / sqli_blind / page:
You will need to change the 65th line as follows.
```php
$result = mysqli_query($GLOBALS["___mysqli_ston"],  $query ) or die( '<pre>' . ((is_object($GLOBALS["___mysqli_ston"])) ? mysqli_error($GLOBALS["___mysqli_ston"]) : (($___mysqli_res = mysqli_connect_error()) ? $___mysqli_res : false)) . '</pre>' );
$num2    = mysqli_fetch_row( $result ); //change this
$num = $num2[0]; //change this
$i      = 0;
```

First, let's make the following change on the 28th line in the medium.php file.
```php
$query  = "SELECT COUNT(*) FROM users;";
$result = mysqli_query($GLOBALS["___mysqli_ston"],  $query ) or die( '<pre>' . ((is_object($GLOBALS["___mysqli_ston"])) ? mysqli_error($GLOBALS["___mysqli_ston"]) : (($___mysqli_res = mysqli_connect_error()) ? $___mysqli_res : false)) . '</pre>' );
$number_of_rows2 = mysqli_fetch_row( $result ); //change this
$number_of_rows = number_of_rows2[0]; //change this.
```
Then let's go to the vulnerabilities / sqli / index.php file and make the following change in line 64.
```php
if( $vulnerabilityFile == 'medium.php' ) {
		$page[ 'body' ] .= "\n				<select name=\"id\">";

		for( $i = 1; $i < $number_of_rows[0] + 1 ; $i++ ) { $page[ 'body' ] .= "<option value=\"{$i}\">{$i}</option>"; } //change this
		$page[ 'body' ] .= "</select>";
	}
```

that is all. happy hacking...

**Comment by jcZhou-615** [comment]
love you from ass
