### ISSUE TITLE
Links to javascript/source/medium.js and javascript/source/high.js are broken

### ISSUE THREAD

**Issue by Mi-Al** [ethicalhack3r/DVWA#355]
Paths to the following files are set as absolute:

- /vulnerabilities/javascript/source/medium.js
- /vulnerabilities/javascript/source/high.js

It's alright if DVWA is located in the root server folder like http://localhost. But if to place DVWA in any subfolder like http://localhost/dvwa, those files will be not found (404).

**Comment by digininja** [comment]
This was fixed in git a long time ago I think, try using the latest version
- not release

**Comment by Mi-Al** [comment]
To install DVWA I use the command:

`https://github.com/ethicalhack3r/DVWA`

But in the **About** section it is said:

`Version 1.10 *Development* (Release date: 2015-10-08)`

**Comment by Mi-Al** [comment]
And in the **medium.php** file ( https://github.com/ethicalhack3r/DVWA/blob/master/vulnerabilities/javascript/source/medium.php ) :

```
<?php
$page[ 'body' ] .= <<<EOF
<script src="/vulnerabilities/javascript/source/medium.js"></script>
EOF;
?>
```

So the bug is still not fixed...

**Comment by digininja** [comment]
It has been fixed, just waiting for @ethicalhack3r to do the pull request. I'll give him another prod.

https://github.com/ethicalhack3r/DVWA/pull/341/files

**Comment by digininja** [comment]
PR merged so if you update now it should be fixed in master.

**Comment by Mi-Al** [comment]
Thank you very much!
