### ISSUE TITLE
couldnt connect to mysql server , please check the config file

### ISSUE THREAD

**Issue by sankethj** [ethicalhack3r/DVWA#359]
i tried solve problem from past few days , but i can't 
i am kali linux 2020.2 user
access dined in mysql status
![image](https://user-images.githubusercontent.com/60228223/83866043-ce5c6d80-a744-11ea-9dfc-7326329ce9bf.png)

**Comment by digininja** [comment]
Did you create a dvwa user and if so, are you using the correct password for it?

**Comment by sankethj** [comment]
yaa, i created dvwa user and using correct password too....

**Comment by digininja** [comment]
did you do a flush privileges after creating it?

Get a screenshot of creating a user called dvwa2 with a password and then
log into it on the command line by passing the password in the -p parameter.

**Comment by sankethj** [comment]
got that bro, thanks for reply 
it was my mistake made in config file altered user name ;
thank you , its working now
