### ISSUE TITLE
502 Server Error

### ISSUE THREAD

**Issue by dhodyrahmad** [ethicalhack3r/DVWA#360]
Hi, Im trying to connect the url but always got returned to 502 server error, while there no problem with my error log on nginx and I disabled the SElinux. Did I missed something?

**Comment by digininja** [comment]
Are you sure it is 502? 501 is a server error, 502 is a bad gateway which
is usually some kind of networking error.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

If it is 502 then I'd look at your proxy and web server config as you've
probably got something pointing at the wrong place.

**Comment by dhodyrahmad** [comment]
Oh i think i found my problem, its just health check on my firewall.
