### ISSUE TITLE
Setting up DVWA using packer/ansible

### ISSUE THREAD

**Issue by Maspital** [ethicalhack3r/DVWA#363]
Hey there,

First off, I should probably apologise since this most likely doesn’t belong here - I tried stackoverflow and the like, but without any success.

I am trying to set up a network consisting of several VMs (acting as Clients, Servers and Routers) using packer and ansible. One of these servers needs to have DVWA installed and a corresponding database all set up, however the latter is not a trivial task when you’re trying to do it automatically. Right now this is solved by also installing Chromium+Selenium, having a selenium script open the setup.php page and letting it click on the “create/reset database”-button.

This is a really “clunky” solution, since a whole browser is installed for one single task, is there any way to create a database via the command line or by using functions provided by the ansible-MySQL module etc? 

Sorry for any inconvenience caused, I’ve been trying to solve this problem for the past several days to no avail and it’s getting seriously frustrating :/ any help or push in the right direction would be greatly appreciated. If you need any more details, please let me know :)

**Comment by digininja** [comment]
Just use curl to hit it from the command line.

Or create a database, dump it, and then install that using the mysql
command line tool.

**Comment by Maspital** [comment]
Thanks a lot! :) I didn’t know you could use curl that way. I’ll comment my solution as soon as I find out which parameters etc. are needed.

**Comment by digininja** [comment]
Don't need any parameters, just post to the setup page

**Comment by Maspital** [comment]
What do you mean by "post to the setup page"? I looked at the source code and found
```
<!-- Create db button -->
	<form action="#" method="post">
		<input name="create_db" type="submit" value="Create / Reset Database">
		<input type='hidden' name='user_token' value='b9806b7f2753e1f5ae23d1668e3a721a' />
	</form>
```
A new usertoken is generated each time the page reloads. When I  manually hit the button, a request with the payload
`create_db=Create+%2F+Reset+Database&user_token=b9806b7f2753e1f5ae23d1668e3a721a` is created, along with the desired dvwa database, if I just trigger this request via curl, no db is created. I tried
```
curl -d "create_db=Create+%2F+Reset+Database&user_token=b9806b7f2753e1f5ae23d1668e3a721a" http://127.0.0.1/dvwa/setup.php
curl -d "" http://127.0.0.1/dvwa/setup.php
curl -X POST http://127.0.0.1/dvwa/setup.php
curl --request POST http://127.0.0.1/dvwa/setup.php
```
none of which result in success (success = dvwa-folder exists in /var/lib/mysql/).

Sorry if this question is trivial, I'm quite new to this topic.

**Comment by digininja** [comment]
Do it the easy way, get a working setup, then dump the database:

```
mysqldump --opt -p dvwa > dvwa.sql
```

Edit that file and add the commands to create the database and user at the top:
 
```
create database dvwa if not exists;
create user dvwa@localhost identified by 'p@ssw0rd';
grant all on dvwa.* to dvwa@localhost;
flush privileges;
use dvwa;
```

Then as part of your install, load the database:

```
mysql -p < dvwa.sql
```

If you are automating it all, you need to pass the password to the mysqldump and mysql commands, you do this by including the password with the -p, no space, e.g. -pSecretPassword. The user would have to be root as only root can create the database and grant privileges by default.

There may be some small typos here, but you should be able to get something working based on it.

**Comment by digininja** [comment]
Or if you want to do it with a `curl` script:

```
#!/usr/bin/env bash

TOKEN=`curl -s http://dvwa.test/setup.php --cookie-jar dvwa.jar | grep token | cut -f 6 -d "'"`

curl -s -k -X POST \
--cookie dvwa.jar \
-H 'Content-Type: application/x-www-form-urlencoded' \
--data-binary "create_db=Create+%2F+Reset+Database&user_token=$TOKEN" \
http://dvwa.test/setup.php
```

**Comment by Maspital** [comment]
It works perfectly, thank you so much! All this new stuff is somewhat overwhelming sometimes, but people like you are insanely helpful :) thanks again
