### ISSUE TITLE
mysql & mariadb Database Error #2002:

### ISSUE THREAD

**Issue by Cr-cm** [ethicalhack3r/DVWA#371]
after install and visit http://localhost/dvwa then turn to http://localhost/dvwa/setup.php#,and then tap "Create/Reset Database' button ,and the result 
Could not connect to the database service.
Please check the config file.
Database Error #2002: ����Ŀ�����������ܾ����޷����ӡ�

i can visit http://localhost/phpMyAdmin4.8.5/index.php?db=mysql&table=user&target=sql.php this page successfully. how to fix this error

**Comment by digininja** [comment]
Please read the README file and if you are still having problems come back with all the information it tells you to submit with problems like this.

**Comment by Cr-cm** [comment]
i have read readme but can't solve it. in windows 2012R2,it always tells that error

**Comment by digininja** [comment]
So send all the evidence that the readme asks for and I'll try to help.

**Comment by Cr-cm** [comment]
![image](https://user-images.githubusercontent.com/6006788/88913398-641eff80-d293-11ea-9874-f50f28f0d67c.png)

**Comment by Cr-cm** [comment]
<?php

# If you are having problems connecting to the MySQL database and all of the variables below are correct
# try changing the 'db_server' variable from localhost to 127.0.0.1. Fixes a problem due to sockets.
#   Thanks to @digininja for the fix.

# Database management system to use
$DBMS = 'MySQL';
#$DBMS = 'PGSQL'; // Currently disabled

# Database variables
#   WARNING: The database specified under db_database WILL BE ENTIRELY DELETED during setup.
#   Please use a database dedicated to DVWA.
#
# If you are using MariaDB then you cannot use root, you must use create a dedicated DVWA user.
#   See README.md for more information on this.
$_DVWA = array();
$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = 'root';

# Only used with PostgreSQL/PGSQL database selection.
$_DVWA[ 'db_port '] = '3308';

# ReCAPTCHA settings
#   Used for the 'Insecure CAPTCHA' module
#   You'll need to generate your own keys at: https://www.google.com/recaptcha/admin
$_DVWA[ 'recaptcha_public_key' ]  = '6LdK7xITAAzzAAJQTfL7fu6I-0aPl8KHHieAT_yJg';
$_DVWA[ 'recaptcha_private_key' ] = '6LdK7xITAzzAAL_uw9YXVUOPoIHPZLfw2K1n5NVQ';

# Default security level
#   Default value for the security level with each session.
#   The default is 'impossible'. You may wish to set this to either 'low', 'medium', 'high' or impossible'.
$_DVWA[ 'default_security_level' ] = 'impossible';

# Default PHPIDS status
#   PHPIDS status with each session.
#   The default is 'disabled'. You can set this to be either 'enabled' or 'disabled'.
$_DVWA[ 'default_phpids_level' ] = 'disabled';

# Verbose PHPIDS messages
#   Enabling this will show why the WAF blocked the request on the blocked request.
#   The default is 'disabled'. You can set this to be either 'true' or 'false'.
$_DVWA[ 'default_phpids_verbose' ] = 'false';

?>

**Comment by Cr-cm** [comment]
$_DVWA = array();
$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = 'root';

# Only used with PostgreSQL/PGSQL database selection.
$_DVWA[ 'db_port '] = '3308';

# ReCAPTCHA settings
#   Used for the 'Insecure CAPTCHA' module
#   You'll need to generate your own keys at: https://www.google.com/recaptcha/admin
$_DVWA[ 'recaptcha_public_key' ]  = '6LdK7xITAAzzAAJQTfL7fu6I-0aPl8KHHieAT_yJg';
$_DVWA[ 'recaptcha_private_key' ] = '6LdK7xITAzzAAL_uw9YXVUOPoIHPZLfw2K1n5NVQ';

**Comment by Cr-cm** [comment]
above is my config.inc.php 
and then i set mysql port in PhpStudy and in browser http://localhost/phpMyAdmin4.8.5/ i can use root/root visit mysql

**Comment by Cr-cm** [comment]
then visit http://127.0.0.1/DVWA/ it will turn to http://127.0.0.1/DVWA/setup.php# and click Create/Reset Database button and then tell me 
Could not connect to the database service.
Please check the config file.
Database Error #2002: ����Ŀ�����������ܾ����޷����ӡ�

Your database user is root, if you are using MariaDB, this will not work, please read the README.md file.

**Comment by digininja** [comment]
Are you using MySQL or MariaDB? Newer PHP doesn't play well with newer MySQL.

Are you sure you should be on port 3308?

Can you translate that error message? All I see is garbled characters. Check in the log files, I don't know where they will be stored on a Windows box.

**Comment by Cr-cm** [comment]
mysql version is 5.7.26 
i always test MariaDB

**Comment by Cr-cm** [comment]
i am very sure the two ports and i set them all correctly

**Comment by digininja** [comment]
> mysql version is 5.7.26
> i always test MariaDB

What do you mean you test MariaDB?

**Comment by Cr-cm** [comment]
you can link my computer use teamviewer?
1 689 272 880
 s9mv74

**Comment by Cr-cm** [comment]
> > mysql version is 5.7.26
> > i always test MariaDB
> 
> What do you mean you test MariaDB?

i have installed MariaDB and create user (dwva/dwva) and datebase dwva for this and chang port to 3310 and then setting  config.inc.php too and then it tells me this error too.

**Comment by Cr-cm** [comment]
you can link my computer use teamviewer?
1 689 272 880
cv4v94
this new

**Comment by digininja** [comment]
That is a very bad idea, don't let strangers onto your computer.

You need to translate the error into something readable, search the database logs and php logs and you'll find something.

I'd still like to see a command line connection to the database using the credentials you give.

When you use MariaDB, you can't use the root database user, there are protections in place to prevent that.

Try changing the host to localhost or the IP address of the machine rather than 127.0.0.1, I've seen that mess things up before.

**Comment by Cr-cm** [comment]
> That is a very bad idea, don't let strangers onto your computer.
> 
> You need to translate the error into something readable, search the database logs and php logs and you'll find something.
> 
> I'd still like to see a command line connection to the database using the credentials you give.
> 
> When you use MariaDB, you can't use the root database user, there are protections in place to prevent that.
> 
> Try changing the host to localhost or the IP address of the machine rather than 127.0.0.1, I've seen that mess things up before.

thanks!!!

**Comment by digininja** [comment]
Was that a celebration of it working?

**Comment by Cr-cm** [comment]
config.inc.php i have added :3308 
$_DVWA[ 'db_server' ]   = '127.0.0.1:3308'; 
then fixed all 
installation should update !!!
solved!!!!
thanks

**Comment by digininja** [comment]
Glad it's working. Please close the ticket.

**Comment by digininja** [comment]
I should have seen the huge comment when you posted the config

```
Only used with PostgreSQL/PGSQL database selection.
$_DVWA[ 'db_port '] = '3308';
```

We don't use the port setting for MySQL/MariaDB so you changing it made absolutely no difference and that is why it worked when you gave it with the IP.

I'll fix that.
