### ISSUE TITLE
Regarding the following  dvwapage line_461  error     

### ISSUE THREAD

**Issue by lcccer** [ethicalhack3r/DVWA#375]
error at:
if( $DBMS == 'MySQL' ) {
		if( !@mysql_connect( $_DVWA[ 'db_server' ], $_DVWA[ 'db_user' ], $_DVWA[ 'db_password' ] )
		|| !@mysql_select_db( $_DVWA[ 'db_database' ] ) ) {
			//die( $DBMS_connError );
			dvwaLogout();
			dvwaMessagePush( 'Unable to connect to the database.<br />' . $DBMS_errorFunc );
			dvwaRedirect( DVWA_WEB_PAGE_TO_ROOT . 'setup.php' );
		}
---------------------------------------------------------------------------------------------------------------------
function (@mysql_connect)   not  global define       
---------------------------------------------------------------------------------------------------------------------
changes ：

if( $DBMS == 'MySQL' ) {
		if( !@($GLOBALS["___mysqli_ston"] = mysqli_connect( $_DVWA[ 'db_server' ],  $_DVWA[ 'db_user' ],  $_DVWA[ 'db_password' ] ))
		|| !@((bool)mysqli_query($GLOBALS["___mysqli_ston"], "USE " . $_DVWA[ 'db_database' ])) ) {
			//die( $DBMS_connError );
			dvwaLogout();
			dvwaMessagePush( 'Unable to connect to the database.<br />' . $DBMS_errorFunc );
			dvwaRedirect( DVWA_WEB_PAGE_TO_ROOT . 'setup.php' );
		}

-----------------------------------------------------------------------------------------------------------------------
ok，install   successful     go on！！！

**Comment by digininja** [comment]
That looks like you aren't using the latest version from GitHub, we got rid
of all references to mysql_ functions years ago.

**Comment by lcccer** [comment]
Hello，Release 1.9  zip   include   error！！！

**Comment by digininja** [comment]
Check out the latest using git, the releases are not recent.

**Comment by lcccer** [comment]
Ok  Thanks!
