### ISSUE TITLE
give hints when setup showing problems

### ISSUE THREAD

**Issue by digininja** [ethicalhack3r/DVWA#56]
If the setup page gives a warning about something then give a link or help baloon which gives information on fixing the problem. The one I've just had is this

PHP function allow_url_include: Disabled

So the help would either say "go to php.ini and set X" or just point them at this page:

http://php.net/manual/en/filesystem.configuration.php

**Comment by mike-bailey** [comment]
++ will do when I finish the backup config branch

**Comment by digininja** [comment]
You are really digging back through issues, well done!

**Comment by mike-bailey** [comment]
Are you going to do this for allow_url_include stuff or do you want me to do it all? I was gonna fix the docker which is coming soon then get to this.

**Comment by digininja** [comment]
Just saw the issues tonight and thought it would be a five minute fix to do.

Just impressed myself with my amazing git skills and got my repo up to date
so happy to do it when I'm back on the machine tomorrow.

**Comment by mike-bailey** [comment]
Sounds good, I'm merging non-major PRs to keep this maintained so hopefully @ethicalhack3r doesn't mind when I just merge it outright.

**Comment by digininja** [comment]
Didn't realise I already had a two year old issue open to do this! Guess
I'm slacking a bit on what I said I'd do.

**Comment by digininja** [comment]
Fixed in PR #202
