### ISSUE TITLE
create a backup config file

### ISSUE THREAD

**Issue by digininja** [ethicalhack3r/DVWA#59]
I've just scanned DVWA with Wfuzz and it found the /config directory and as directory indexing is enabled I can see the config.inf.php file but obviously can't read the contents as it is parsed by php.

It would be nice to have a "backup" of the file with .bak or .old in there that could be discovered as another vulnerability.

**Comment by mike-bailey** [comment]
How would this be consistently updated? Maybe on site load copy it to config.inc.php.bak?

**Comment by digininja** [comment]
Just do it at the end of the setup process. At that point we know the config file is good and working so just copy it to config.inc.php.bak or similar.

**Comment by mike-bailey** [comment]
Made a PR for this.

**Comment by mike-bailey** [comment]
Definitely done.
