### ISSUE TITLE
reCAPTCHA key problem with DVWA

### ISSUE THREAD

**Issue by webkodex** [ethicalhack3r/DVWA#60]
Hi, I have a issue with CAPTCHA key, even after copying the right & inserting it to public & server it still says could not Could not connect to the MySQL service. Please check the config file. & how to fix 
Writable file /var/www/html/DVWA/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: No
kindly suggest me a fix.

![capture](https://cloud.githubusercontent.com/assets/15958581/12852330/d57f233c-cc47-11e5-9ea6-63b3848dc09e.PNG)

![capture1](https://cloud.githubusercontent.com/assets/15958581/12852333/dd873b28-cc47-11e5-8f9c-c074f3b1fbd2.PNG)

**Comment by digininja** [comment]
is your public key split over two lines by accident or just for the screenshot?

**Comment by webkodex** [comment]
no, i took this screenshot exactly as it is in server. not just for screenshot.

**Comment by digininja** [comment]
so you've got a broken line in the file, the word public should be all one
word not broken in the middle.

**Comment by webkodex** [comment]
Thanks That worked, but still got an error that Could not connect to the MySQL service, i have ignored phpids log txt - no . however  the username i used for mysql is root & password is toor, (updated), i put same values under db user - root , db password - toor, under config.inc.php. is that php ids should be fixed ? or something else is missing ?

**Comment by digininja** [comment]
My guess is that you've got the database credentials wrong.

Try connecting with

mysql -u root -p

And put the password in that is in the config file. See if that works.

**Comment by webkodex** [comment]
checked it nothing wrong with password, its root/toor
![mysql](https://cloud.githubusercontent.com/assets/15958581/12854014/b8342062-cc50-11e5-8349-91d290637061.PNG)

![mysql2](https://cloud.githubusercontent.com/assets/15958581/12854020/c2db021a-cc50-11e5-93be-c6af971eca1b.PNG)

**Comment by digininja** [comment]
Add a -H 127.0.0.1 to that command line and try again. I don't know what interfaces MariaDB listens on by default so it may only be accepting socket connections.

And whatever you are using to take screenshots is missing off the edges which makes some things hard to check.

**Comment by webkodex** [comment]
_its fixed working now on CentOs 7_

what interfaces MariaDB listens on ? i changed it to** 0.0.0.0** under etc/my.cnf

**socket =/var/lib/mysql/mysql.sock**

then i changed db server 127.0.0.1 to **localhost** inside dvwa config

I have also mutillidae on same vm, i found that mutillidae had no issues with mariadb, i went to mutiilidae>classes >MySQLhandler.php & setting was localhost. 


![mysql](https://cloud.githubusercontent.com/assets/15958581/12865745/8d8d187c-ccce-11e5-9842-83fddaef548b.PNG)

![var](https://cloud.githubusercontent.com/assets/15958581/12865747/93122cf6-ccce-11e5-828e-83f9ea4be37f.PNG)


 Thank you for your valuable time & suggestions.

**Comment by digininja** [comment]
It will be that MariaDB probably only listens on local sockets by default so now you've asked it to listen on the network as well.

Glad its fixed.

**Comment by mansurabbas** [comment]
When I type mysql -u root and then press enter, I got this error...

ERROR 2002 (HY000) : can't connect to local MYSQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by leonteale** [comment]
Is your database running

**Comment by eulerworks** [comment]
@mansurabbas if youre on OSX with XAMPP try this:
Set db_password to null in config.inc.php like this: $_DVWA[ 'db_password' ] = '';
from your terminal try:
```<prompt>$ /Applications/XAMPP/bin/mysql -u root -p```
hit ```<enter>``` (for no password)
if this brings up the mariadb monitor, it works, but your PATH needs adjusting so run:
```<prompt>$ ln -sf /Applications/XAMPP/xamppfiles/var/mysql/mysql.sock /tmp/mysql.sock```

It should work now. Underlying issue: I would imagine /tmp/mysql.sock doesnt exist...

Otherwise for MAMP, follow this here:
{http://stackoverflow.com/questions/11105796/error-2002-cant-connect-to-local-mysql-server-through-socket-applications-ma/26766466#26766466}

**Comment by sshourya948** [comment]
> When I type mysql -u root and then press enter, I got this error...
> 
> ERROR 2002 (HY000) : can't connect to local MYSQL server through socket '/var/run/mysqld/mysqld.sock' (2)

bro just install xampp on your linux and and install dvwa in that and just start apache by going into /opt/lampp/ folder and typing this command ./xampp startapache this command will start apache server and then ./xampp startmysql this will start your mysql database and then your dvwa will work
