### ISSUE TITLE
Is there a mod I need to make to my browser to get to the lab in the local host?

### ISSUE THREAD

**Issue by ajmayes012** [ethicalhack3r/DVWA#61]
I have all the files in /var/www/ but it wont pull up the local host? Looks like this has been a common problem on the tutorial I'm watching on Udemy. Thanks

**Comment by ajmayes012** [comment]
service apache2 restart

**Comment by g0tmi1k** [comment]
Your web root depends on web services settings. 
By the looks of it - your using apache2?
Whats the host OS? Debian? Ubuntu?

By default: 
+ Debian 8 >  = `/var/www/html`
+ Debian < 7 = `/var/www`

**Comment by digininja** [comment]
Have you tried talking to the Udemy author about it?

**Comment by mike-bailey** [comment]
@ajmayes012 Is this resolved? What's the current status of this.

After two weeks of non-response I'll be closing it.

**Comment by mike-bailey** [comment]
See above
