### ISSUE TITLE
Login.php is blank

### ISSUE THREAD

**Issue by bhutchison** [ethicalhack3r/DVWA#68]
I have setup everything as instructed.  I can see the /setup.php  /instructions.php and /about.php pages but when I click on the create database button, I just get a blank screen.
The url it goes to after clicking create database is - http://localhost/dvwa/setup.php#

Nothing else happens, it doesnt take me to the login or anything.  Any help would be great.

Getting error
 Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\dvwa\dvwa\includes\dvwaPage.inc.php:461 Stack trace: #0 C:\xampp\htdocs\dvwa\login.php(8): dvwaDatabaseConnect() #1 {main} thrown in C:\xampp\htdocs\dvwa\dvwa\includes\dvwaPage.inc.php on line 461

**Comment by lxtsina** [comment]
i have the same problom with the up floor 
i have setup everything as instructed. I can see the /setup.php /instructions.php and /about.php pages but when I click on the create database button, I just get a blank screen.
The url it goes to after clicking create database is - http://localhost/dvwa/setup.php#

Nothing else happens, it doesnt take me to the login or anything. Any help would be great.
(i did not get he error message even the php.ini  display_errors = On)

**Comment by nfeynman** [comment]
I'm having the exact same problem. Did you find a solution? I didn't quite get lxtsina's solution, even though, I tried it and nothing changed.

**Comment by el2t** [comment]
try
chmod -R 755 /var/www/dvwa

**Comment by ivipuls** [comment]
Are you using php v7.0? 
Read http://localhost/dvwa/instructions.php
"_Note, You are unable to use PHP v7.0 or later with DVWA_."

**Comment by michaelyousrie** [comment]
for those with the same issue still;

I had to make sure that my database server was running using the below command:

`$ sudo service mysql start`

**Comment by CyberSpace7777** [comment]
> Are you using php v7.0? Read http://localhost/dvwa/instructions.php "_Note, You are unable to use PHP v7.0 or later with DVWA_."

hey mate, I am having the same issue in 2024. However, your article is 8 years ago.
Can you please confirm if it is still applicable today?
If so, can you please advise what PHP version to use?
![Uploading PHP v5.6.JPG…]()

**Comment by digininja** [comment]
We moved away from php 5.x many years ago. DVWA currently runs fine on all versions of php from 7.0 onwards.

**Comment by rahysmonroe** [comment]
im having same problem in 2024 
<img width="959" alt="dvwa" src="https://github.com/digininja/DVWA/assets/109827550/6d622729-0ce6-4ba6-b756-9907e1915613">

**Comment by digininja** [comment]
Please create a new ticket and provide ALL the information requested. If
you don't, the ticket will be closed.

**Comment by Madosca** [comment]
Hi can anyone  assist me. Am trying to install DVWA on my Kali Linux. But any time i click on create Database the screen turns blank. How do i fix it please ? Have already tried the suggested solutions but all to no avail. The version of PHP i use is 8.2

**Comment by digininja** [comment]
As said in the reply above yours, please create a new ticket giving ALL the
information requested in the template.

**Comment by lakunzy7** [comment]
same here im having the same issue

**Comment by digininja** [comment]
Can you read?
