### ISSUE TITLE
Fatal error: Uncaught Error:

### ISSUE THREAD

**Issue by sspy4tech** [ethicalhack3r/DVWA#72]
*_Getting Error after clicking on Create and reset database button 
*_
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\DVWA\dvwa\includes\DBMS\MySQL.php:9 Stack trace: #0 C:\xampp\htdocs\DVWA\setup.php(17): include_once() #1 {main} thrown in C:\xampp\htdocs\DVWA\dvwa\includes\DBMS\MySQL.php on line 9

Could any 1 can help to reslove this issues

Detail 
Setup Check
Operating system: Windows
Backend database: MySQL
PHP version: 7.0.4

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Enabled (Easy Mode!)
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Installed

reCAPTCHA key: --------

Writable folder C:\xampp\htdocs\DVWA/hackable/uploads/: Yes)
Writable file C:\xampp\htdocs\DVWA/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes
# Status in red, indicate there will be an issue when trying to complete some modules.

**Comment by g0tmi1k** [comment]
You can't use PHP 7 with it.

**Comment by ethicalhack3r** [comment]
Since the last comment you are now able to use PHP 7
