### ISSUE TITLE
dvwaExternalLinkUrlGet() does not register

### ISSUE THREAD

**Issue by ghost** [ethicalhack3r/DVWA#75]
Fatal error: Call to undefined function dvwaExternalLinkUrlGet() in C:\xampp\htdocs\dvwa\vulnerabilities\[Insert Vuln Here]\help\help.php on line 33

It does this for all php files that use this function >:(

**Comment by mike-bailey** [comment]
Closing as stale, someone is more than welcome to open a new one if they experience this but afaik this was patched.
