### ISSUE TITLE
Only loading http://localhost/dvwa/setup.php - but no login.php.

### ISSUE THREAD

**Issue by Rogermumu** [ethicalhack3r/DVWA#76]
I am using XAMPP web server, and it is working well. Only, I do not know why "localhost" is loading the setup.php and not the login.php. When I remove "setup.php" from the URL and replace it with "login.php", the URL is flipping back to "setup.php". 
So, I tried already to reinstall DVWA - XAMPP - MySql -PHP5, etc, but always the same problem occurs. 
What can I do to change in a good direction? 
Anyone can help? 
Thanks !

**Comment by prmdsngh** [comment]
[http://www.snazar.com/articles/setting-up-dvwa-in-a-kali-vm/](url) check out this link u will be fine
