### ISSUE TITLE
PHP module mysql: Missing

### ISSUE THREAD

**Issue by karlito62** [ethicalhack3r/DVWA#80]
hi ,

I have a problem I can not change PHP module mysql: Missing 
how to resolve this error thank you in advance

```
PHP function display_errors: Enabled (Easy Mode!)
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Missing
PHP module pdo_mysql: Installed
```

**Comment by digininja** [comment]
You need to install the MySQL libraries, what OS are you running it on?

**Comment by karlito62** [comment]
hi , 
I use xampp on windows 10

**Comment by digininja** [comment]
no idea then, could help with LAMP stack but not Windows

**Comment by karlito62** [comment]
I used USB Webserver everything works except that I have an error
Fatal error: in G:\serveur\root\DV\dvwa\includes\dvwaPage.inc.php on line 469

**Comment by Themercee** [comment]
For your USB Webserver, ensure that php-pdo is enable. The dvwaPage.inc.php use PDO to connect to the database.

**Comment by zief** [comment]
i'm on ubuntu 16

**Comment by Themercee** [comment]
If you have the php version 7, you will need to get the module php7-mysql installed. You can search in the repositories
`sudo apt-cache search php | grep mysql`
Look for something like php7-mysql.

Important: I am not sure if the DVWA is compatible with PHP v7, maybe just validate that, to be sure.

**Comment by mesakh** [comment]
hi,

i'm on kali linux and still same trouble in PHP module gd is missing, how i can fix this problems? 
for 2nd questions how i set up the disable configuration like PHP function display_errors: and the other else?

Operating system: *nix
Backend database: MySQL
PHP version: 5.6.17-3

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Missing
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: *blank*
MySQL database: dvwa
MySQL host: 127.0.0.1

reCAPTCHA key: 6LdK7xITAAzzAAJQTfL7fu6I-0aPl8KHHieAT_yJg

[User: root] Writable folder /var/www/html/dvwa/DVWA-master/hackable/uploads/: No
[User: root] Writable file /var/www/html/dvwa/DVWA-master/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: No

**Comment by MuhammadHFarhad** [comment]
Can anyone please help me with this problem? I'm using Parrot Sec Os, tired of tryin to solve these errors for 17hrs. What should i do to prevent this error?


Operating system: *nix

PHP version: 7.4.33
PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Missing - Only an issue if you want to play with captchas
PHP module mysql: Missing
PHP module pdo_mysql: Missing

Backend database: MySQL/MariaDB
Database username: user
Database password: ******
Database database: dvwa
Database host: 127.0.0.1
Database port: 3306

**Comment by digininja** [comment]
Read the README and then if you are still having problems open a new ticket and provide all the information requested.
