### ISSUE TITLE
Fatal error: dvwaPage.inc.php on line 469

### ISSUE THREAD

**Issue by karlito62** [ethicalhack3r/DVWA#81]
hi, 
I install all when I click on create a database, the bass is given then create its redirects me to the login page I have the following error message

Fatal error: in G:\serveur\root\DVWA\dvwa\includes\dvwaPage.inc.php on line 469

**Comment by mike-bailey** [comment]
I'd be surprised if this was still an issue since line 469 on that file is commented out. Feel free to re-open anissue if it is.
