### ISSUE TITLE
Command Execution not working?

### ISSUE THREAD

**Issue by samolivercz** [ethicalhack3r/DVWA#84]
Hi, 

I am having problems with command execution on dvwa.

It seems that the regular function of the "Ping" command is not even executing, I enter an IP and press submit, however nothing happens. I am not even greeted with the ping command in red text as expected, it looks more like the page is simply refreshing itself.

If anyone can help me with this, i'd greatly appreciate it

**Comment by mike-bailey** [comment]
Do you have any more details on this such as logs? Sorry for the long wait, I realize this issue may have been long abandoned, I just wanted to follow up on it since the exec code base hasn't changed at all in two years.

**Comment by mike-bailey** [comment]
Do you have any more details on this such as logs? Sorry for the long wait, I realize this issue may have been long abandoned, I just wanted to follow up on it since the exec code base hasn't changed at all in two years.

**Comment by MenyBgu** [comment]
hi, i having the same problem.
any solutions ?

**Comment by digininja** [comment]
Create a new ticket with full details. What level, what you are trying,
logs,what's happening etc.

**Comment by shouryashukla0602** [comment]
Same here, please help, I'm running DVWA on Kali Nethunter using Apache2 ans MariaDB, rest all the sections are working fine. But when I enter the ip address in the ping section it gives nothing, just refreshes. I've tried localhost also, the output is nothing. On the other hand when I enter the command in the terminal it's giving output. Please help

**Comment by digininja** [comment]
As I said to MenyBgu, can you create a new ticket with all the info,
including the exact command you are submitting and examples of all others
you have tried.

Also snippets of the Apache access and error logs from made during the
requests you think should work.
