### ISSUE TITLE
Installing on kali3 and logging in

### ISSUE THREAD

**Issue by cloversedu** [ethicalhack3r/DVWA#85]

**Comment by cloversedu** [comment]
HI, 
I am not able to properly install DVWA in kali3 or login.
Any suggestions?

**Comment by Rogermumu** [comment]
Hi,

Click on this link and follow the instructions.

http://gatewaysolu.blogspot.be/2013/08/how-to-install-dvwa-in-kali-linux.html

If you have the Apache2 server in your kali linux menu, then start it first.
If Apache2 - or XAMPP is missing in your kali, then install it first.
But you have to be aware that XAMPP server is folowing an other path then
Apache2.
If you have more questions, please feel free to ask.
Good luck.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-05-27 14:06 GMT+02:00 cloversedu <notifications@github.com>:
