### ISSUE TITLE
ReCAPTCHA upgrade causes issues

### ISSUE THREAD

**Issue by OrangePorpoise** [ethicalhack3r/DVWA#88]
The link to gaining an public/private key set for the ReCAPTCHA challenge has now been updated, no longer do you get a public/private key you get site/server and whilst the premise is the same, these seem to cause errors within the dvwa site.

If more information is required am happy to provide it but currently just looks like an issue due to changes Googles end.

**Comment by mike-bailey** [comment]
(This was definitely updated)
