### ISSUE TITLE
Deprecated: Function mysql_numrows() while sql injection low level test dvwa V1.9

### ISSUE THREAD

**Issue by douchka** [ethicalhack3r/DVWA#92]
Deprecated: Function mysql_numrows() while sql injection low level test 
the function is deprecated as you see and i switched to mysql_num_rows() function in the 
C:\wamp\www\DVWA\vulnerabilities\sqli\source
line 21
`
<?php

if( isset( $_REQUEST[ 'Submit' ] ) ) {
    // Get input
    $id = $_REQUEST[ 'id' ];

```
// Check database
$query  = "SELECT first_name, last_name FROM users WHERE user_id = '$id';";
$result = mysql_query( $query ) or die( '<pre>' . mysql_error() . '</pre>' );

// Get results
$num = mysql_num_rows( $result );
$i   = 0;
while( $i < $num ) {
    // Get values
    $first = mysql_result( $result, $i, "first_name" );
    $last  = mysql_result( $result, $i, "last_name" );

    // Feedback for end user
    $html .= "<pre>ID: {$id}<br />First name: {$first}<br />Surname: {$last}</pre>";

    // Increase loop count
    $i++;
}

mysql_close();
```

}

?>

`
and it works for me ! any problem with this modification ?

**Comment by douchka** [comment]
the same thin with medium level

**Comment by mike-bailey** [comment]
Deprecation isn't fatal but I believe we have moved away from mysql_* properly since then. I don't see it in source/low.php anymore. If you think this issue still exists please let me know. Closing.

**Comment by mike-bailey** [comment]
To clarify if you think this issue still exists, or any other issue, please open a new one here.
