### ISSUE TITLE
Uncaught Error: Call to undefined function mysql_result()

### ISSUE THREAD

**Issue by stuartflewis** [ethicalhack3r/DVWA#93]
Deprecated: Function mysql_result on brute force low / medium level test 
the function is deprecated as you see and possible fix shown below using  mysqli_data_seek and mysqli_fetch_assoc

if( $result && mysqli_num_rows( $result ) == 1 ) {
        // Get users details
        //$avatar = mysql_result( $result, 0, "avatar" );
        //Fatal error: Uncaught Error: Call to undefined function mysql_result()
        // in DVWA\vulnerabilities\brute\source\medium.php:19
        // Stack trace: #0 DVWA\vulnerabilities\brute\index.php(33): require_once() #1 {main}
        // thrown in DVWA\vulnerabilities\brute\source\medium.php on line 19
        /\* seek to row no. 0 _/
        mysqli_data_seek($result, 0);
        /_ fetch associative array _/
        $row = mysqli_fetch_assoc($result);
        /_ fetch avatar */
        $avatar = $row["avatar"];

It looks like you use mysql_result in various other places too....

**Comment by mike-bailey** [comment]
That section appears to now use mysqli. If you have any other issues feel free to open one.

**Comment by stuartflewis** [comment]
Agreed, sorted now. Thanks
