### ISSUE TITLE
PHP7 shows PHP code

### ISSUE THREAD

**Issue by devrajashwin** [ethicalhack3r/DVWA#94]
Need to run 'setup.php'." ); dvwaRedirect( DVWA_WEB_PAGE_TO_ROOT . 'setup.php' ); } $query = "SELECT \* FROM `users` WHERE user='$user' AND password='$pass';"; $result = @mysqli_query($GLOBALS["___mysqli_ston"], $query ) or die( '

' . ((is_object($GLOBALS["___mysqli_ston"])) ? mysqli_error($GLOBALS["___mysqli_ston"]) : (($___mysqli_res = mysqli_connect_error()) ? $___mysqli_res : false)) . '.
Try installing again.

' ); if( $result && mysqli_num_rows( $result ) == 1 ) { // Login Successful... dvwaMessagePush( "You have logged in as '{$user}'" ); dvwaLogin( $user ); dvwaRedirect( DVWA_WEB_PAGE_TO_ROOT . 'index.php' ); } // Login failed dvwaMessagePush( 'Login failed' ); dvwaRedirect( 'login.php' ); } $messagesHtml = messagesPopAllToHtml(); Header( 'Cache-Control: no-cache, must-revalidate'); // HTTP/1.1 Header( 'Content-Type: text/html;charset=utf-8' ); // TODO- proper XHTML headers... Header( 'Expires: Tue, 23 Jun 2009 12:00:00 GMT' ); // Date in the past // Anti-CSRF generateSessionToken(); echo "

**Comment by digininja** [comment]
"some this wrong with this" - I fully agree, there is no context, no information about what is going on and so nothing for us to work on.

Ask a question and give some context rather than just dumping a chunk of code.

**Comment by devrajashwin** [comment]
just this only displayed on my browser when i typed localhost://

**Comment by digininja** [comment]
You've not got php enabled. Search these issues and google, there are loads of resources on how to enable it in ever different environment.

**Comment by NoWishGranted** [comment]
Hello,

I have the same problem. I installed DVWA on Linux. And I got php enabled, apache2 and mysql running plus my permissions are set. But unfortunatly the login.php and update.php are not loading properly. 

Any ideas how to fix it?

**Comment by digininja** [comment]
If you are seeing the same you don't have php enabled.

**Comment by NoWishGranted** [comment]
But i have php enabled. Other scripts are working properly.

**Comment by digininja** [comment]
If you get source code on screen it means the php interpreter isn't parsing
it before the web server or sending it out.

**Comment by NoWishGranted** [comment]
Yeah, I understand. But it is happening only with two scripts - setup.php and login.php. For example instructions.php is loading normally, without any errors or code on the website.

**Comment by NoWishGranted** [comment]
To your information, PHP7 was problem, had do downgrade to 5.6
