### ISSUE TITLE
Can't find php5-gd on kali2 by apt-get install php5-gd

### ISSUE THREAD

**Issue by ZanderChang** [ethicalhack3r/DVWA#96]
Package php5-gd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5-gd' has no installation candidate

**Comment by jroyal808** [comment]
try this, worked for me... 
apt-get install php-gd

**Comment by ethicalhack3r** [comment]
@ZanderChang did that work?

**Comment by ZanderChang** [comment]
@jroyal808 @ethicalhack3r No, it still doesn't work

PHP module php-gd: Missing

**Comment by mohamedation** [comment]
any solutions yet?

**Comment by kmanwar89** [comment]
need solution

**Comment by kmanwar89** [comment]
please send solution

**Comment by digininja** [comment]
did you enable gd and restart Apache?
